/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA;
typedef struct tySequence__jwzrUFjG9akTIJTBBFvvqxw tySequence__jwzrUFjG9akTIJTBBFvvqxw;
typedef struct tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content;
typedef struct tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NU8 tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A;
struct tySequence__jwzrUFjG9akTIJTBBFvvqxw {
  NI len; tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content* p;
};
typedef NU8 tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg;
typedef NU8 tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw;
struct tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA {
	tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw backend;
	NU16 frameNumber;
	tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* model;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
struct tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content { NI cap; tyTuple__XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(size_t, isp1181_state_size)(void);
N_LIB_EXPORT N_CDECL(void, isp1181_tick)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 sofFrames_p1);
N_LIB_PRIVATE N_NIMCALL(void, advanceFrames__isp1181Zstub_u52)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NI frames_p1);
N_LIB_EXPORT N_CDECL(void, isp1181_state_save)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* dst_p1);
N_LIB_PRIVATE N_NIMCALL(void, putBe32__isp1181Zstate_u49)(NU8* buf_p0, NI at_p1, NU32 value_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, isp1181StateWalk__isp1181Zstate_u90)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU8* buf_p1, tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A op_p2, tySequence__jwzrUFjG9akTIJTBBFvvqxw* layout_p3, tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg* status_p4);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__mcf5407Zstate_u122)(tySequence__jwzrUFjG9akTIJTBBFvvqxw* x_p0, tyTuple__XOVT24GHXwqiEj5GCsEGCA y_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, putBe16__isp1181Zstate_u33)(NU8* buf_p0, NI at_p1, NU16 value_p2);
N_LIB_PRIVATE N_NIMCALL(NU16, getBe16__isp1181Zstate_u41)(NU8* buf_p0, NI at_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, isp1181StateChecksum__isp1181Zstate_u81)(NU8* buf_p0, NI upTo_p1);
N_LIB_EXPORT N_CDECL(void, isp1181_state_load)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg, isp1181Restore__isp1181Zstate_u218)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* src_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u84)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, getBe32__isp1181Zstate_u65)(NU8* buf_p0, NI at_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__BhBjtTN9abKbC0dL7pDSNxw_6 = { 7 | NIM_STRLIT_FLAG, "backend" };
static const NimStringV2 TM__BhBjtTN9abKbC0dL7pDSNxw_7 = {7, (NimStrPayload*)&TM__BhBjtTN9abKbC0dL7pDSNxw_6};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__BhBjtTN9abKbC0dL7pDSNxw_12 = { 11 | NIM_STRLIT_FLAG, "frameNumber" };
static const NimStringV2 TM__BhBjtTN9abKbC0dL7pDSNxw_13 = {11, (NimStrPayload*)&TM__BhBjtTN9abKbC0dL7pDSNxw_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__BhBjtTN9abKbC0dL7pDSNxw_15 = { 5 | NIM_STRLIT_FLAG, "model" };
static const NimStringV2 TM__BhBjtTN9abKbC0dL7pDSNxw_16 = {5, (NimStrPayload*)&TM__BhBjtTN9abKbC0dL7pDSNxw_15};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3441;
N_LIB_EXPORT N_CDECL(size_t, isp1181_state_size)(void) {
	size_t result;
	result = ((size_t)19);
	return result;
}
N_LIB_EXPORT N_CDECL(void, isp1181_tick)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 sofFrames_p1) {
	advanceFrames__isp1181Zstub_u52(ctx_p0, ((NI) (sofFrames_p1)));
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, putBe32__isp1181Zstate_u49)(NU8* buf_p0, NI at_p1, NU32 value_p2) {
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_2;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_3;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_4;
{	buf_p0[at_p1] = ((NU8) ((NU32)((NU32)((NU32)(value_p2) >> (NU64)(((NI)24) & (32 - 1))) & ((NU32)255))));
	if (nimAddInt(at_p1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_2)) { raiseOverflow(); goto BeforeRet_;
	};
	buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_2)] = ((NU8) ((NU32)((NU32)((NU32)(value_p2) >> (NU64)(((NI)16) & (32 - 1))) & ((NU32)255))));
	if (nimAddInt(at_p1, ((NI)2), &TM__BhBjtTN9abKbC0dL7pDSNxw_3)) { raiseOverflow(); goto BeforeRet_;
	};
	buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_3)] = ((NU8) ((NU32)((NU32)((NU32)(value_p2) >> (NU64)(((NI)8) & (32 - 1))) & ((NU32)255))));
	if (nimAddInt(at_p1, ((NI)3), &TM__BhBjtTN9abKbC0dL7pDSNxw_4)) { raiseOverflow(); goto BeforeRet_;
	};
	buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_4)] = ((NU8) ((NU32)(value_p2 & ((NU32)255))));
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, putBe16__isp1181Zstate_u33)(NU8* buf_p0, NI at_p1, NU16 value_p2) {
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_9;
{	buf_p0[at_p1] = ((NU8) ((NU16)((NU16)((NU16)(value_p2) >> (NU64)(((NI)8) & (16 - 1))) & ((NU16)255))));
	if (nimAddInt(at_p1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_9)) { raiseOverflow(); goto BeforeRet_;
	};
	buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_9)] = ((NU8) ((NU16)(value_p2 & ((NU16)255))));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU16, getBe16__isp1181Zstate_u41)(NU8* buf_p0, NI at_p1) {
	NU16 result;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_10;
{	result = (NU16)0;
	if (nimAddInt(at_p1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_10)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NU16)((NU16)((NU64)(((NU16) (buf_p0[at_p1]))) << (NU64)(((NI)8) & (16 - 1))) | ((NU16) (buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_10)])));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, isp1181StateWalk__isp1181Zstate_u90)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU8* buf_p1, tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A op_p2, tySequence__jwzrUFjG9akTIJTBBFvvqxw* layout_p3, tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg* status_p4) {
	NI result;
	NI at_1;
{	result = (NI)0;
	at_1 = ((NI)0);
	{
		NI started_1;
		NI TM__BhBjtTN9abKbC0dL7pDSNxw_5;
		if (!NIM_TRUE) goto LA3_;
		started_1 = at_1;
		{
			if (!(op_p2 == ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)2))) goto LA7_;
			buf_p1[at_1] = ((NU8) ((*ctx_p0).backend));
		}
		goto LA5_;
LA7_: ;
		{
			if (!(op_p2 == ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)1))) goto LA10_;
			{
				NIM_BOOL T14_;
				T14_ = (NIM_BOOL)0;
				T14_ = (((NI) (buf_p1[at_1])) < ((NI)0));
				if (T14_) goto LA15_;
				T14_ = (((NI)1) < ((NI) (buf_p1[at_1])));
LA15_: ;
				if (!T14_) goto LA16_;
				(*status_p4) = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)6);
			}
LA16_: ;
		}
		goto LA5_;
LA10_: ;
		{
			if (!(op_p2 == ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)3))) goto LA19_;
			if ((buf_p1[at_1]) < ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0) || (buf_p1[at_1]) > ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1)){ raiseRangeErrorI(buf_p1[at_1], ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0), ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1)); goto BeforeRet_;
			}
			(*ctx_p0).backend = ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw) (buf_p1[at_1]));
		}
		goto LA5_;
LA19_: ;
LA5_: ;
		if (nimAddInt(at_1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_5)) { raiseOverflow(); goto BeforeRet_;
		};
		at_1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_5);
		{
			tyTuple__XOVT24GHXwqiEj5GCsEGCA T25_;
			NI TM__BhBjtTN9abKbC0dL7pDSNxw_8;
			if (!!((layout_p3 == ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL)))) goto LA23_;
			T25_.Field0 = TM__BhBjtTN9abKbC0dL7pDSNxw_7;
			if (nimSubInt(at_1, started_1, &TM__BhBjtTN9abKbC0dL7pDSNxw_8)) { raiseOverflow(); goto BeforeRet_;
			};
			T25_.Field1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_8);
			add__mcf5407Zstate_u122((&(*layout_p3)), T25_);
		}
LA23_: ;
	}
LA3_: ;
	{
		NI started_2;
		NI TM__BhBjtTN9abKbC0dL7pDSNxw_11;
		if (!NIM_TRUE) goto LA28_;
		started_2 = at_1;
		{
			if (!(op_p2 == ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)2))) goto LA32_;
			putBe16__isp1181Zstate_u33(buf_p1, at_1, (*ctx_p0).frameNumber);
		}
		goto LA30_;
LA32_: ;
		{
			if (!(op_p2 == ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)3))) goto LA35_;
			(*ctx_p0).frameNumber = getBe16__isp1181Zstate_u41(buf_p1, at_1);
		}
		goto LA30_;
LA35_: ;
LA30_: ;
		if (nimAddInt(at_1, ((NI)2), &TM__BhBjtTN9abKbC0dL7pDSNxw_11)) { raiseOverflow(); goto BeforeRet_;
		};
		at_1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_11);
		{
			tyTuple__XOVT24GHXwqiEj5GCsEGCA T41_;
			NI TM__BhBjtTN9abKbC0dL7pDSNxw_14;
			if (!!((layout_p3 == ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL)))) goto LA39_;
			T41_.Field0 = TM__BhBjtTN9abKbC0dL7pDSNxw_13;
			if (nimSubInt(at_1, started_2, &TM__BhBjtTN9abKbC0dL7pDSNxw_14)) { raiseOverflow(); goto BeforeRet_;
			};
			T41_.Field1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_14);
			add__mcf5407Zstate_u122((&(*layout_p3)), T41_);
		}
LA39_: ;
	}
LA28_: ;
	{
		NI started_3;
		if (!NIM_TRUE) goto LA44_;
		started_3 = at_1;
		{
			tyTuple__XOVT24GHXwqiEj5GCsEGCA T50_;
			NI TM__BhBjtTN9abKbC0dL7pDSNxw_17;
			if (!!((layout_p3 == ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL)))) goto LA48_;
			T50_.Field0 = TM__BhBjtTN9abKbC0dL7pDSNxw_16;
			if (nimSubInt(at_1, started_3, &TM__BhBjtTN9abKbC0dL7pDSNxw_17)) { raiseOverflow(); goto BeforeRet_;
			};
			T50_.Field1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_17);
			add__mcf5407Zstate_u122((&(*layout_p3)), T50_);
		}
LA48_: ;
	}
LA44_: ;
	result = at_1;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, isp1181StateChecksum__isp1181Zstate_u81)(NU8* buf_p0, NI upTo_p1) {
	NU32 result;
{	result = ((NU32)IL64(2166136261));
	{
		NI index_1;
		NI i_1;
		index_1 = (NI)0;
		i_1 = ((NI)0);
		{
			while (1) {
				NI TM__BhBjtTN9abKbC0dL7pDSNxw_18;
				if (!(i_1 < upTo_p1)) goto LA3;
				index_1 = i_1;
				result = (NU32)((NU32)((NU32)(result ^ ((NU32) (buf_p0[index_1])))) * (NU32)(((NU32)16777619)));
				if (nimAddInt(i_1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_18)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_18);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, isp1181_state_save)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* dst_p1) {
	NU8* buf_1;
	NI T7_;
	NU32 T8_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = (dst_p1 == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	buf_1 = ((NU8*) (dst_p1));
	putBe32__isp1181Zstate_u49(buf_1, ((NI)0), ((NU32)1230196785));
	putBe32__isp1181Zstate_u49(buf_1, ((NI)4), ((NU32)1));
	putBe32__isp1181Zstate_u49(buf_1, ((NI)8), ((NU32)3));
	T7_ = (NI)0;
	T7_ = isp1181StateWalk__isp1181Zstate_u90((&(*ctx_p0)), ((NU8*) ((&buf_1[((NI)12)]))), ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)2), ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL), ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg*) NIM_NIL));
	(void)(T7_);
	T8_ = (NU32)0;
	T8_ = isp1181StateChecksum__isp1181Zstate_u81(buf_1, ((NI)15));
	putBe32__isp1181Zstate_u49(buf_1, ((NI)15), T8_);
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NU32, getBe32__isp1181Zstate_u65)(NU8* buf_p0, NI at_p1) {
	NU32 result;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_19;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_20;
	NI TM__BhBjtTN9abKbC0dL7pDSNxw_21;
{	result = (NU32)0;
	if (nimAddInt(at_p1, ((NI)1), &TM__BhBjtTN9abKbC0dL7pDSNxw_19)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt(at_p1, ((NI)2), &TM__BhBjtTN9abKbC0dL7pDSNxw_20)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt(at_p1, ((NI)3), &TM__BhBjtTN9abKbC0dL7pDSNxw_21)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (buf_p0[at_p1]))) << (NU64)(((NI)24) & (32 - 1))) | (NU32)((NU64)(((NU32) (buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_19)]))) << (NU64)(((NI)16) & (32 - 1)))) | (NU32)((NU64)(((NU32) (buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_20)]))) << (NU64)(((NI)8) & (32 - 1)))) | ((NU32) (buf_p0[(NI)(TM__BhBjtTN9abKbC0dL7pDSNxw_21)])));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3441);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg, isp1181Restore__isp1181Zstate_u218)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* src_p1) {
	tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg result;
	tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA probe_1;
	NU8* buf_1;
	tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg fieldStatus_1;
	NI T29_;
	NI T34_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)0;
	nimZeroMem((void*)(&probe_1), sizeof(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA));
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = (src_p1 == 0);
LA5_: ;
		if (!T4_) goto LA6_;
		result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)1);
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA6_: ;
	buf_1 = ((NU8*) (src_p1));
	{
		NU32 T10_;
		T10_ = (NU32)0;
		T10_ = getBe32__isp1181Zstate_u65(buf_1, ((NI)0));
		if (!!((T10_ == ((NU32)1230196785)))) goto LA11_;
		result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)2);
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA11_: ;
	{
		NU32 T15_;
		T15_ = (NU32)0;
		T15_ = getBe32__isp1181Zstate_u65(buf_1, ((NI)4));
		if (!!((T15_ == ((NU32)1)))) goto LA16_;
		result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)3);
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA16_: ;
	{
		NU32 T20_;
		T20_ = (NU32)0;
		T20_ = getBe32__isp1181Zstate_u65(buf_1, ((NI)8));
		if (!!((T20_ == ((NU32)3)))) goto LA21_;
		result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)4);
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA21_: ;
	{
		NU32 T25_;
		NU32 T26_;
		T25_ = (NU32)0;
		T25_ = getBe32__isp1181Zstate_u65(buf_1, ((NI)15));
		T26_ = (NU32)0;
		T26_ = isp1181StateChecksum__isp1181Zstate_u81(buf_1, ((NI)15));
		if (!!((T25_ == T26_))) goto LA27_;
		result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)5);
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA27_: ;
	fieldStatus_1 = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)0);
	T29_ = (NI)0;
	T29_ = isp1181StateWalk__isp1181Zstate_u90((&probe_1), ((NU8*) ((&buf_1[((NI)12)]))), ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)1), ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL), (&fieldStatus_1));
	(void)(T29_);
	{
		if (!!((fieldStatus_1 == ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)0)))) goto LA32_;
		result = fieldStatus_1;
		eqdestroy___isp1181Zstub_u84((&probe_1));
		goto BeforeRet_;
	}
LA32_: ;
	T34_ = (NI)0;
	T34_ = isp1181StateWalk__isp1181Zstate_u90((&(*ctx_p0)), ((NU8*) ((&buf_1[((NI)12)]))), ((tyEnum_Isp1181StateOp__hFhCU59bt9bh4k0sipfXRj6A)3), ((tySequence__jwzrUFjG9akTIJTBBFvvqxw*) NIM_NIL), ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg*) NIM_NIL));
	(void)(T34_);
	result = ((tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)0);
	{
		LA1_:;
	}
	{
		eqdestroy___isp1181Zstub_u84((&probe_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, isp1181_state_load)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, void* src_p1) {
	tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg T1_;
	T1_ = (tyEnum_Isp1181StateStatus__3zbzR8j2eq8O30ybTknemg)0;
	T1_ = isp1181Restore__isp1181Zstate_u218(ctx_p0, src_p1);
	(void)(T1_);
}
