/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg tySequence__aLjCOs9bu5l2rz6ENM6m6Sg;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content;
typedef struct tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw;
typedef struct tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ;
typedef struct tyTuple__XuEptoDfXTC1e9cYOa19bnsw tyTuple__XuEptoDfXTC1e9cYOa19bnsw;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg {
  NI len; tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content* p;
};
struct tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ {
	NI capacityBytes;
	NI bufferCount;
	tySequence__aLjCOs9bu5l2rz6ENM6m6Sg packets;
};
struct tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw {
	NIM_BOOL Field0;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ Field1;
};
struct tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ {
	NI len;
	void* p;
};
struct tyTuple__XuEptoDfXTC1e9cYOa19bnsw {
	NIM_BOOL Field0;
	NU8 Field1;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content { NI cap; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zfifo_u16)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zfifo_u34)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__isp1181Zfifo_u130)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___isp1181Zfifo_u31)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, eqdup___isp1181Zfifo_u40)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__isp1181Zfifo_u51)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* s_p0, NI newlen_p1);
static N_INLINE(void, nimCopySeqPayload)(void* dest_p0, void* src_p1, NI elemSize_p2, NI elemAlign_p3);
N_LIB_PRIVATE N_NIMCALL(NI, align__system_u1648)(NI address_p0, NI alignment_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0);
static N_INLINE(NF, abs__system_u4290)(NF x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___isp1181Zfifo_u37)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, delete__isp1181Zfifo_u469)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg* x_p0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isFull__isp1181Zfifo_u299)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__isp1181Zfifo_u331)(NI len_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__isp1181Zfifo_u357)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg* x_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ y_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3441;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zfifo_u34)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NU8));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___isp1181Zfifo_u274)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* dest_p0, tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* src_p1) {
	(*dest_p0).capacityBytes = (*src_p1).capacityBytes;
	(*dest_p0).bufferCount = (*src_p1).bufferCount;
	if ((*dest_p0).packets.p != (*src_p1).packets.p) {	eqdestroy___isp1181Zfifo_u16((*dest_p0).packets);
	}
(*dest_p0).packets.len = (*src_p1).packets.len; (*dest_p0).packets.p = (*src_p1).packets.p;
}
N_LIB_PRIVATE N_NIMCALL(void, initFifo__isp1181Zfifo_u5)(NI capacity_p0, NI buffers_p1, tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* Result) {
	(*Result).capacityBytes = capacity_p0;
	(*Result).bufferCount = buffers_p1;
	(*Result).packets.len = 0; (*Result).packets.p = (tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content*) newSeqPayload(0, sizeof(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ), NIM_ALIGNOF(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ));
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___isp1181Zfifo_u43)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___isp1181Zfifo_u34((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___isp1181Zfifo_u31)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, clear__isp1181Zfifo_u540)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	setLen__isp1181Zfifo_u130((&(*f_p0).packets), ((NI)0));
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, abs__system_u4290)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__system_u1705(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1705(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__system_u1705(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u4290(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u4290(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
static N_INLINE(void, nimCopySeqPayload)(void* dest_p0, void* src_p1, NI elemSize_p2, NI elemAlign_p3) {
	tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ* d_1;
	tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ* s_1;
{	d_1 = ((tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ*) (dest_p0));
	s_1 = ((tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ*) (src_p1));
	{
		NI headerSize_1;
		NI TM__6hqqLio23emlcjjsEa9cJlw_2;
		if (!(((NI)0) < (*s_1).len)) goto LA3_;
		headerSize_1 = align__system_u1648(((NI)8), elemAlign_p3);
		if (nimMulInt((*s_1).len, elemSize_p2, &TM__6hqqLio23emlcjjsEa9cJlw_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__6hqqLio23emlcjjsEa9cJlw_2)) < ((NI)0) || ((NI)(TM__6hqqLio23emlcjjsEa9cJlw_2)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__6hqqLio23emlcjjsEa9cJlw_2), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1755(((void*) ((NU)((NU64)(((NU) (ptrdiff_t) ((*d_1).p))) + (NU64)(((NU) (headerSize_1)))))), ((void*) ((NU)((NU64)(((NU) (ptrdiff_t) ((*s_1).p))) + (NU64)(((NU) (headerSize_1)))))), ((NI)(TM__6hqqLio23emlcjjsEa9cJlw_2)));
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, eqdup___isp1181Zfifo_u40)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI T1_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__isp1181Zfifo_u51((&result), T1_);
	nimCopySeqPayload((&result), (&src_p0), ((NI)1), ((NI)1));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3441);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw, peekPacket__isp1181Zfifo_u409)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp_;
		NIM_BOOL colontmp__2;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_1;
		T3_ = (*f_p0).packets.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		colontmp__2 = NIM_FALSE;
		colontmp_.len = 0; colontmp_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__2;
		blitTmp_1 = colontmp_;
		eqwasMoved___isp1181Zfifo_u31((&colontmp_));
		result.Field1 = blitTmp_1;
		eqdestroy___isp1181Zfifo_u34(colontmp_);
		goto BeforeRet_;
		{
			LA6_:;
		}
		{
			eqdestroy___isp1181Zfifo_u34(colontmp_);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	result.Field0 = NIM_TRUE;
	if (((NI)0) < 0 || ((NI)0) >= (*f_p0).packets.len){ raiseIndexError2(((NI)0),(*f_p0).packets.len-1); goto BeforeRet_;
	}
	colontmpD_ = eqdup___isp1181Zfifo_u40((*f_p0).packets.p->data[((NI)0)]);
	result.Field1 = colontmpD_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ*) (x_p0))).p == (*((tyObject_NimRawSeq__Y28CPnYVTzfVXMyO7kfS9aQ*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___isp1181Zfifo_u37)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1) {
	NI T6_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__isp1181Zfifo_u51((&(*dest_p0)), T6_);
	nimCopySeqPayload(dest_p0, (&src_p1), ((NI)1), ((NI)1));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zfifo_u444)(tyTuple__vQrhkkpKKvr9c9cWOQD9cAXuw* dest_p0) {
	eqdestroy___isp1181Zfifo_u34((*dest_p0).Field1);
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, take__isp1181Zfifo_u459)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
{	result.len = 0; result.p = NIM_NIL;
	{
		NI T3_;
		T3_ = (*f_p0).packets.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		goto BeforeRet_;
	}
LA4_: ;
	if (((NI)0) < 0 || ((NI)0) >= (*f_p0).packets.len){ raiseIndexError2(((NI)0),(*f_p0).packets.len-1); goto BeforeRet_;
	}
	eqcopy___isp1181Zfifo_u37((&result), (*f_p0).packets.p->data[((NI)0)]);
	delete__isp1181Zfifo_u469((&(*f_p0).packets), ((NI)0));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, capacity__isp1181Zfifo_u281)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	NI result;
	result = (*f_p0).capacityBytes;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isFull__isp1181Zfifo_u299)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	NIM_BOOL result;
	NI T1_;
	T1_ = (*f_p0).packets.len;
	result = ((*f_p0).bufferCount <= T1_);
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, accept__isp1181Zfifo_u305)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0, NU8* data_p1, NI data_p1Len_0) {
	NIM_BOOL result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ packet_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	packet_1.len = 0; packet_1.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = isFull__isp1181Zfifo_u299((&(*f_p0)));
		if (T4_) goto LA5_;
		T4_ = ((*f_p0).capacityBytes < data_p1Len_0);
LA5_: ;
		if (!T4_) goto LA6_;
		result = NIM_FALSE;
		eqdestroy___isp1181Zfifo_u34(packet_1);
		goto BeforeRet_;
	}
LA6_: ;
	if ((data_p1Len_0) < ((NI)0) || (data_p1Len_0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(data_p1Len_0, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	packet_1 = newSeq__isp1181Zfifo_u331((data_p1Len_0));
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = data_p1Len_0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__6hqqLio23emlcjjsEa9cJlw_3;
				if (!(i_2 < colontmp_)) goto LA10;
				i_1 = i_2;
				if (i_1 < 0 || i_1 >= packet_1.len){ raiseIndexError2(i_1,packet_1.len-1); goto LA1_;
				}
				if (i_1 < 0 || i_1 >= data_p1Len_0){ raiseIndexError2(i_1,data_p1Len_0-1); goto LA1_;
				}
				packet_1.p->data[i_1] = data_p1[i_1];
				if (nimAddInt(i_2, ((NI)1), &TM__6hqqLio23emlcjjsEa9cJlw_3)) { raiseOverflow(); goto LA1_;
				};
				i_2 = (NI)(TM__6hqqLio23emlcjjsEa9cJlw_3);
			} LA10: ;
		}
	}
	blitTmp_1 = packet_1;
	eqwasMoved___isp1181Zfifo_u31((&packet_1));
	add__isp1181Zfifo_u357((&(*f_p0).packets), blitTmp_1);
	result = NIM_TRUE;
	{
		LA1_:;
	}
	{
		eqdestroy___isp1181Zfifo_u34(packet_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, pending__isp1181Zfifo_u287)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	NI result;
	NI T1_;
	T1_ = (*f_p0).packets.len;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, buffers__isp1181Zfifo_u284)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	NI result;
	result = (*f_p0).bufferCount;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__XuEptoDfXTC1e9cYOa19bnsw, peek__isp1181Zfifo_u377)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	tyTuple__XuEptoDfXTC1e9cYOa19bnsw result;
{	{
		NIM_BOOL T3_;
		NI T4_;
		NI T6_;
		NIM_BOOL colontmp_;
		NU8 colontmp__2;
		T3_ = (NIM_BOOL)0;
		T4_ = (*f_p0).packets.len;
		T3_ = (T4_ == ((NI)0));
		if (T3_) goto LA5_;
		if (((NI)0) < 0 || ((NI)0) >= (*f_p0).packets.len){ raiseIndexError2(((NI)0),(*f_p0).packets.len-1); goto BeforeRet_;
		}
		T6_ = (*f_p0).packets.p->data[((NI)0)].len;
		T3_ = (T6_ == ((NI)0));
LA5_: ;
		if (!T3_) goto LA7_;
		colontmp_ = NIM_FALSE;
		colontmp__2 = ((NU8)0);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA7_: ;
	result.Field0 = NIM_TRUE;
	if (((NI)0) < 0 || ((NI)0) >= (*f_p0).packets.len){ raiseIndexError2(((NI)0),(*f_p0).packets.len-1); goto BeforeRet_;
	}
	if (((NI)0) < 0 || ((NI)0) >= (*f_p0).packets.p->data[((NI)0)].len){ raiseIndexError2(((NI)0),(*f_p0).packets.p->data[((NI)0)].len-1); goto BeforeRet_;
	}
	result.Field1 = (*f_p0).packets.p->data[((NI)0)].p->data[((NI)0)];
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEmpty__isp1181Zfifo_u293)(tyObject_Fifo__COOcx0Y6cjjRkI7fa6lrnQ* f_p0) {
	NIM_BOOL result;
	NI T1_;
	T1_ = (*f_p0).packets.len;
	result = (T1_ == ((NI)0));
	return result;
}
