/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew;
typedef struct tyObject_Decoded__7Dbj6AEfD9alAhGfE7g37sg tyObject_Decoded__7Dbj6AEfD9alAhGfE7g37sg;
typedef struct tyObject_EA__KI3RB4YzJz8SR6dkI0rRzQ tyObject_EA__KI3RB4YzJz8SR6dkI0rRzQ;
typedef NU8 tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww;
typedef NU8 tyEnum_EAMode__3aOOvktwifK3OZLaWIYGHQ;
struct tyObject_EA__KI3RB4YzJz8SR6dkI0rRzQ {
	tyEnum_EAMode__3aOOvktwifK3OZLaWIYGHQ mode;
	NU8 reg;
};
struct tyObject_Decoded__7Dbj6AEfD9alAhGfE7g37sg {
	tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww op;
	tyObject_EA__KI3RB4YzJz8SR6dkI0rRzQ ea;
	NU8 size;
	NU8 destReg;
	NU8 destMode;
	NIM_BOOL memDir;
	NIM_BOOL dirToEa;
	NU8 imm;
	NIM_BOOL regOperand;
};
typedef NI32 tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA;
typedef N_CDECL_PTR(NU32, tyProc__m3YPy7Spfk9bnIuzLyo9bUPA) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* status_p3);
typedef N_CDECL_PTR(void, tyProc__DPk5mmlbc0hvn8CHsxMHlw) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew {
	void* user;
	void* sim;
	tyProc__m3YPy7Spfk9bnIuzLyo9bUPA readFn;
	tyProc__DPk5mmlbc0hvn8CHsxMHlw writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
typedef NU8 tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, movecPrivilegeViolation__mcf5407Zmovec_u20)(NU32 sr_p0);
N_LIB_PRIVATE N_NIMCALL(void, takeException__mcf5407Zmachine_u389)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3);
N_LIB_PRIVATE N_NIMCALL(NU16, fetchExt__mcf5407Zmachine_u241)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ, controlRegisterFor__mcf5407Zmovec_u37)(NU16 rc_p0);
N_LIB_PRIVATE N_NIMCALL(NU16, movecControlField__mcf5407Zmovec_u7)(NU16 ext_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, movecSourceIsAddressRegister__mcf5407Zmovec_u10)(NU16 ext_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, regA__mcf5407Zmachine_u11)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU8 n_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, movecSourceRegister__mcf5407Zmovec_u13)(NU16 ext_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, regD__mcf5407Zmachine_u7)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU8 n_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, setRegD__mcf5407Zmachine_u32)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU8 n_p1, NU32 v_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, mergeSized__mcf5407Zmachine_u153)(NU32 old_p0, NU32 value_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, eaRead__mcf5407Zmachine_u294)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, tyObject_EA__KI3RB4YzJz8SR6dkI0rRzQ ea_p1, NU8 size_p2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3441;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, movecPrivilegeViolation__mcf5407Zmovec_u20)(NU32 sr_p0) {
	NIM_BOOL result;
	result = ((NU32)(sr_p0 & ((NU32)8192)) == ((NU32)0));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ, controlRegisterFor__mcf5407Zmovec_u37)(NU16 rc_p0) {
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ result;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD_;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__2;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__3;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__4;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__5;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__6;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__7;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__8;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__9;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ colontmpD__10;
	colontmpD_ = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__2 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__3 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__4 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__5 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__6 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__7 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__8 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__9 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	colontmpD__10 = (tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0;
	switch (rc_p0) {
	case ((NU16)2):
	{
		colontmpD_ = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)1);
		result = colontmpD_;
	}
	break;
	case ((NU16)4):
	{
		colontmpD__2 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)2);
		result = colontmpD__2;
	}
	break;
	case ((NU16)5):
	{
		colontmpD__3 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)3);
		result = colontmpD__3;
	}
	break;
	case ((NU16)6):
	{
		colontmpD__4 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)4);
		result = colontmpD__4;
	}
	break;
	case ((NU16)7):
	{
		colontmpD__5 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)5);
		result = colontmpD__5;
	}
	break;
	case ((NU16)2049):
	{
		colontmpD__6 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)6);
		result = colontmpD__6;
	}
	break;
	case ((NU16)3076):
	{
		colontmpD__7 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)7);
		result = colontmpD__7;
	}
	break;
	case ((NU16)3077):
	{
		colontmpD__8 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)8);
		result = colontmpD__8;
	}
	break;
	case ((NU16)3087):
	{
		colontmpD__9 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)9);
		result = colontmpD__9;
	}
	break;
	default:
	{
		colontmpD__10 = ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0);
		result = colontmpD__10;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU16, movecControlField__mcf5407Zmovec_u7)(NU16 ext_p0) {
	NU16 result;
	result = (NU16)(ext_p0 & ((NU16)4095));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, movecSourceIsAddressRegister__mcf5407Zmovec_u10)(NU16 ext_p0) {
	NIM_BOOL result;
	result = !(((NU16)(ext_p0 & ((NU16)32768)) == ((NU16)0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, movecSourceRegister__mcf5407Zmovec_u13)(NU16 ext_p0) {
	NU8 result;
	result = (NU8)0;
	result = ((NU8) ((NU16)((NU16)((NU16)(ext_p0) >> (NU64)(((NI)12) & (16 - 1))) & ((NU16)7))));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3441);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, movecFamily__mcf5407Zmovec_u58)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU16 word_p1, tyObject_Decoded__7Dbj6AEfD9alAhGfE7g37sg d_p2) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU16 ext_1;
	tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ destination_1;
	NU16 T10_;
	NU32 source_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = movecPrivilegeViolation__mcf5407Zmovec_u20((*ctx_p0).sr);
		if (!T3_) goto LA4_;
		takeException__mcf5407Zmachine_u389(ctx_p0, ((NU8)8), (NU32)((NU32)((*ctx_p0).pc) - (NU32)(((NU32)2))), ((NU32)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA4_: ;
	ext_1 = fetchExt__mcf5407Zmachine_u241(ctx_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA8_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA8_: ;
	T10_ = (NU16)0;
	T10_ = movecControlField__mcf5407Zmovec_u7(ext_1);
	destination_1 = controlRegisterFor__mcf5407Zmovec_u37(T10_);
	{
		if (!(destination_1 == ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0))) goto LA13_;
		(*ctx_p0).halted = NIM_TRUE;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA13_: ;
	{
		NIM_BOOL T17_;
		NU8 T20_;
		T17_ = (NIM_BOOL)0;
		T17_ = movecSourceIsAddressRegister__mcf5407Zmovec_u10(ext_1);
		if (!T17_) goto LA18_;
		T20_ = (NU8)0;
		T20_ = movecSourceRegister__mcf5407Zmovec_u13(ext_1);
		colontmpD_ = regA__mcf5407Zmachine_u11(ctx_p0, T20_);
		source_1 = colontmpD_;
	}
	goto LA15_;
LA18_: ;
	{
		NU8 T22_;
		T22_ = (NU8)0;
		T22_ = movecSourceRegister__mcf5407Zmovec_u13(ext_1);
		colontmpD__2 = regD__mcf5407Zmachine_u7(ctx_p0, T22_);
		source_1 = colontmpD__2;
	}
LA15_: ;
	switch (destination_1) {
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)1):
	{
		(*ctx_p0).cacr = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)2):
	{
		(*ctx_p0).acr0 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)3):
	{
		(*ctx_p0).acr1 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)4):
	{
		(*ctx_p0).acr2 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)5):
	{
		(*ctx_p0).acr3 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)6):
	{
		(*ctx_p0).vbr = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)7):
	{
		(*ctx_p0).rambar0 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)8):
	{
		(*ctx_p0).rambar1 = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)9):
	{
		(*ctx_p0).mbar = source_1;
	}
	break;
	case ((tyEnum_ControlRegister__jZ59ajE4LkK3Cqqfzo6yYLQ)0):
	{
	}
	break;
	default: __builtin_unreachable();
	}
	result = ((NU32)9);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, systemControlFamily__mcf5407Zmovec_u73)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0, NU16 word_p1, tyObject_Decoded__7Dbj6AEfD9alAhGfE7g37sg d_p2) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	NU32 colontmpD__4;
	NU32 colontmpD__5;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	colontmpD__4 = (NU32)0;
	colontmpD__5 = (NU32)0;
	switch (d_p2.op) {
	case ((tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww)61):
	{
		NU32 T8_;
		NU32 T9_;
		{
			NIM_BOOL T5_;
			T5_ = (NIM_BOOL)0;
			T5_ = movecPrivilegeViolation__mcf5407Zmovec_u20((*ctx_p0).sr);
			if (!T5_) goto LA6_;
			takeException__mcf5407Zmachine_u389(ctx_p0, ((NU8)8), (NU32)((NU32)((*ctx_p0).pc) - (NU32)(((NU32)2))), ((NU32)0));
			if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA6_: ;
		T8_ = (NU32)0;
		T8_ = regD__mcf5407Zmachine_u7(ctx_p0, d_p2.destReg);
		T9_ = (NU32)0;
		T9_ = mergeSized__mcf5407Zmachine_u153(T8_, (NU32)((*ctx_p0).sr & ((NU32)65535)), ((NU8)2));
		setRegD__mcf5407Zmachine_u32(ctx_p0, d_p2.destReg, T9_);
		colontmpD_ = ((NU32)1);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww)62):
	{
		NU32 T13_;
		NU32 T14_;
		T13_ = (NU32)0;
		T13_ = regD__mcf5407Zmachine_u7(ctx_p0, d_p2.destReg);
		T14_ = (NU32)0;
		T14_ = mergeSized__mcf5407Zmachine_u153(T13_, (NU32)((*ctx_p0).sr & ((NU32)31)), ((NU8)2));
		setRegD__mcf5407Zmachine_u32(ctx_p0, d_p2.destReg, T14_);
		colontmpD__2 = ((NU32)1);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww)63):
	{
		NU32 src_1;
		src_1 = eaRead__mcf5407Zmachine_u294(ctx_p0, d_p2.ea, ((NU8)2));
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		{
			if (!(*ctx_p0).halted) goto LA19_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA19_: ;
		(*ctx_p0).sr = (NU32)((NU32)((*ctx_p0).sr & ((NU32)IL64(4294967264))) | (NU32)(src_1 & ((NU32)31)));
		colontmpD__3 = ((NU32)1);
		result = colontmpD__3;
		{
			LA16_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__6TLKcNpVQyj7eqVm9aG23ww)64):
	{
		NU32 src_2;
		{
			NIM_BOOL T27_;
			T27_ = (NIM_BOOL)0;
			T27_ = movecPrivilegeViolation__mcf5407Zmovec_u20((*ctx_p0).sr);
			if (!T27_) goto LA28_;
			takeException__mcf5407Zmachine_u389(ctx_p0, ((NU8)8), (NU32)((NU32)((*ctx_p0).pc) - (NU32)(((NU32)2))), ((NU32)0));
			if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA28_: ;
		src_2 = eaRead__mcf5407Zmachine_u294(ctx_p0, d_p2.ea, ((NU8)2));
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		{
			if (!(*ctx_p0).halted) goto LA32_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA32_: ;
		(*ctx_p0).sr = (NU32)(src_2 & ((NU32)65535));
		colontmpD__4 = ((NU32)1);
		result = colontmpD__4;
		{
			LA24_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
		colontmpD__5 = ((NU32)0);
		result = colontmpD__5;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
