/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NI32 tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg;
typedef NU8 tyEnum_BusAccess__Ku2g49bUN5G9alQAkxLYckAA;
N_LIB_PRIVATE N_NIMCALL(NU32, faultStatusFor__coldfireZbus_u21)(tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg status_p0, tyEnum_BusAccess__Ku2g49bUN5G9alQAkxLYckAA access_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	switch (status_p0) {
	case ((tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg)0):
	{
		colontmpD_ = ((NU32)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg)3):
	{
		colontmpD__2 = ((NU32)9);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg)1):
	case ((tyEnum_Mcf5407BusStatus__hPLjpdUuhhj56zjPigmtzg)2):
	{
		NU32 colontmpD__4;
		NU32 colontmpD__5;
		colontmpD__4 = (NU32)0;
		colontmpD__5 = (NU32)0;
		switch (access_p1) {
		case ((tyEnum_BusAccess__Ku2g49bUN5G9alQAkxLYckAA)0):
		{
			colontmpD__4 = ((NU32)12);
			colontmpD__3 = colontmpD__4;
		}
		break;
		case ((tyEnum_BusAccess__Ku2g49bUN5G9alQAkxLYckAA)1):
		{
			colontmpD__5 = ((NU32)8);
			colontmpD__3 = colontmpD__5;
		}
		break;
		default: __assume(0);
		}
		result = colontmpD__3;
	}
	break;
	default: __assume(0);
	}
	return result;
}
