/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ;
typedef struct tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA;
typedef struct tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw;
typedef struct tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g;
typedef struct tyObject_EaRef__pKu825coD8roQenraSdRvw tyObject_EaRef__pKu825coD8roQenraSdRvw;
typedef NU8 tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ;
typedef NU8 tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw;
struct tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw {
	tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw mode;
	NU8 reg;
};
struct tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA {
	tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ op;
	tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea;
	NU8 size;
	NU8 destReg;
	NU8 destMode;
	NIM_BOOL memDir;
	NIM_BOOL dirToEa;
	NU8 imm;
	NIM_BOOL regOperand;
};
typedef NI32 tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow;
typedef N_CDECL_PTR(NU32, tyProc__48NbZWzqN9c65MTL6aqhyoQ) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p3);
typedef N_CDECL_PTR(void, tyProc__Z520qbkX3ihqF4aEH1pYnQ) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ {
	void* user;
	void* sim;
	void* cfgIsa;
	void* cfgVbrMask;
	tyProc__48NbZWzqN9c65MTL6aqhyoQ readFn;
	tyProc__Z520qbkX3ihqF4aEH1pYnQ writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
typedef NU8 tySet_tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw;
typedef NU8 tySet_tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A;
struct tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g {
	tySet_tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw modes;
	tySet_tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A ea7;
};
typedef NU8 tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw;
struct tyObject_EaRef__pKu825coD8roQenraSdRvw {
	tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw kind;
	NU8 reg;
	NU32 address;
};
N_LIB_PRIVATE N_NIMCALL(NU32, execAndOr__coldfireZlogic_u12)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, trap__coldfireZlogic_u4)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eaIsLegalFor__coldfireZdecode95types_u243)(tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ op_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, eaRead__coldfireZmachine_u305)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, combine__coldfireZlogic_u7)(tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ op_p0, NU32 src_p1, NU32 dst_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, regD__coldfireZmachine_u7)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1);
N_LIB_PRIVATE N_NIMCALL(void, setRegD__coldfireZmachine_u32)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1, NU32 v_p2);
N_LIB_PRIVATE N_NIMCALL(void, setNzClearVc__coldfireZmachine_u158)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 value_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEaLegal__coldfireZea_u90)(tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g leg_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_EaRef__pKu825coD8roQenraSdRvw, eaResolve__coldfireZmachine_u333)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, eaRefRead__coldfireZmachine_u372)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EaRef__pKu825coD8roQenraSdRvw r_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eaRefWrite__coldfireZmachine_u377)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EaRef__pKu825coD8roQenraSdRvw r_p1, NU8 size_p2, NU32 value_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NU32, execEor__coldfireZlogic_u21)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, execImmediate__coldfireZlogic_u32)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
N_LIB_PRIVATE N_NIMCALL(NU16, fetchExt__coldfireZmachine_u252)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, execNot__coldfireZlogic_u44)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, execBitOp__coldfireZlogic_u49)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g, eaLegalityFor__coldfireZdecode95types_u229)(tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ op_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, execShift__coldfireZlogic_u73)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
extern NIM_CONST tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g eaMemoryAlterable__coldfireZdecode95types_u163;
extern NIM_CONST tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g eaBitStatic__coldfireZdecode95types_u171;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3415;
N_LIB_PRIVATE N_NIMCALL(NU32, trap__coldfireZlogic_u4)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	NU32 result;
	(*ctx_p0).fault = NIM_TRUE;
	(*ctx_p0).halted = NIM_TRUE;
	result = ((NU32)0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, combine__coldfireZlogic_u7)(tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ op_p0, NU32 src_p1, NU32 dst_p2) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	switch (op_p0) {
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)24):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)44):
	{
		colontmpD_ = (NU32)(src_p1 & dst_p2);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)25):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)45):
	{
		colontmpD__2 = (NU32)(src_p1 | dst_p2);
		result = colontmpD__2;
	}
	break;
	default:
	{
		colontmpD__3 = (NU32)(src_p1 ^ dst_p2);
		result = colontmpD__3;
	}
	break;
	}
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3415);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, execAndOr__coldfireZlogic_u12)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	tyObject_EaRef__pKu825coD8roQenraSdRvw dest_1;
	NU32 dst_1;
	NU32 res_2;
	NU32 T32_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	{
		if (!!((d_p1.size == ((NU8)4)))) goto LA3_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NU32 src_1;
		NU32 res_1;
		NU32 T18_;
		if (!!(d_p1.dirToEa)) goto LA7_;
		{
			NIM_BOOL T11_;
			T11_ = (NIM_BOOL)0;
			T11_ = eaIsLegalFor__coldfireZdecode95types_u243(d_p1.op, d_p1.ea);
			if (!!(T11_)) goto LA12_;
			result = trap__coldfireZlogic_u4(ctx_p0);
			goto BeforeRet_;
		}
LA12_: ;
		src_1 = eaRead__coldfireZmachine_u305(ctx_p0, d_p1.ea, ((NU8)4));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(*ctx_p0).halted) goto LA16_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA16_: ;
		T18_ = (NU32)0;
		T18_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.destReg);
		res_1 = combine__coldfireZlogic_u7(d_p1.op, src_1, T18_);
		setRegD__coldfireZmachine_u32(ctx_p0, d_p1.destReg, res_1);
		setNzClearVc__coldfireZmachine_u158(ctx_p0, res_1, ((NU8)4));
		result = ((NU32)4);
		goto BeforeRet_;
	}
LA7_: ;
	{
		NIM_BOOL T21_;
		T21_ = (NIM_BOOL)0;
		T21_ = isEaLegal__coldfireZea_u90(eaMemoryAlterable__coldfireZdecode95types_u163, d_p1.ea);
		if (!!(T21_)) goto LA22_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA22_: ;
	dest_1 = eaResolve__coldfireZmachine_u333(ctx_p0, d_p1.ea, ((NU8)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA26_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA26_: ;
	dst_1 = eaRefRead__coldfireZmachine_u372(ctx_p0, dest_1, ((NU8)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA30_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA30_: ;
	T32_ = (NU32)0;
	T32_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.destReg);
	res_2 = combine__coldfireZlogic_u7(d_p1.op, T32_, dst_1);
	eaRefWrite__coldfireZmachine_u377(ctx_p0, dest_1, ((NU8)4), res_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA35_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA35_: ;
	setNzClearVc__coldfireZmachine_u158(ctx_p0, res_2, ((NU8)4));
	result = ((NU32)1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, execEor__coldfireZlogic_u21)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	tyObject_EaRef__pKu825coD8roQenraSdRvw dest_1;
	NU32 dst_1;
	NU32 res_1;
	NU32 T18_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		if (!!((d_p1.size == ((NU8)4)))) goto LA3_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = eaIsLegalFor__coldfireZdecode95types_u243(((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)43), d_p1.ea);
		if (!!(T7_)) goto LA8_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA8_: ;
	dest_1 = eaResolve__coldfireZmachine_u333(ctx_p0, d_p1.ea, ((NU8)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA12_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA12_: ;
	dst_1 = eaRefRead__coldfireZmachine_u372(ctx_p0, dest_1, ((NU8)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA16_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA16_: ;
	T18_ = (NU32)0;
	T18_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.destReg);
	res_1 = (NU32)(dst_1 ^ T18_);
	eaRefWrite__coldfireZmachine_u377(ctx_p0, dest_1, ((NU8)4), res_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA21_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA21_: ;
	setNzClearVc__coldfireZmachine_u158(ctx_p0, res_1, ((NU8)4));
	{
		if (!(d_p1.ea.mode == ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)0))) goto LA25_;
		colontmpD_ = ((NU32)4);
		result = colontmpD_;
	}
	goto LA23_;
LA25_: ;
	{
		colontmpD__2 = ((NU32)6);
		result = colontmpD__2;
	}
LA23_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, execImmediate__coldfireZlogic_u32)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	NU16 hi_1;
	NU16 lo_1;
	NU32 src_1;
	NU32 res_1;
	NU32 T14_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	{
		if (!!((d_p1.size == ((NU8)4)))) goto LA3_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = eaIsLegalFor__coldfireZdecode95types_u243(d_p1.op, d_p1.ea);
		if (!!(T7_)) goto LA8_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA8_: ;
	hi_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	lo_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA12_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA12_: ;
	src_1 = (NU32)((NU32)((NU64)(((NU32) (hi_1))) << (NU64)(((NI)16) & (32 - 1))) | ((NU32) (lo_1)));
	T14_ = (NU32)0;
	T14_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.ea.reg);
	res_1 = combine__coldfireZlogic_u7(d_p1.op, src_1, T14_);
	setRegD__coldfireZmachine_u32(ctx_p0, d_p1.ea.reg, res_1);
	setNzClearVc__coldfireZmachine_u158(ctx_p0, res_1, ((NU8)4));
	result = ((NU32)1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, execNot__coldfireZlogic_u44)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	NU32 res_1;
	NU32 T10_;
{	{
		if (!!((d_p1.size == ((NU8)4)))) goto LA3_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = eaIsLegalFor__coldfireZdecode95types_u243(((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)27), d_p1.ea);
		if (!!(T7_)) goto LA8_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA8_: ;
	T10_ = (NU32)0;
	T10_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.ea.reg);
	res_1 = (NU32)((NU32) ~(T10_));
	setRegD__coldfireZmachine_u32(ctx_p0, d_p1.ea.reg, res_1);
	setNzClearVc__coldfireZmachine_u158(ctx_p0, res_1, ((NU8)4));
	result = ((NU32)1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NU32, execBitOp__coldfireZlogic_u49)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g colontmpD_;
	tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g colontmpD__2;
	NU32 colontmpD__3;
	NU32 colontmpD__4;
	tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g mask_1;
	NU32 bitNumber_1;
	NU32 bit_1;
	NU32 selector_1;
	NU32 value_1;
	NIM_BOOL wasSet_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_EaLegality__NN9aA0XZPSGhd7aTgkLbX6g));
	colontmpD__3 = (NU32)0;
	colontmpD__4 = (NU32)0;
	{
		if (!d_p1.regOperand) goto LA3_;
		colontmpD_ = eaLegalityFor__coldfireZdecode95types_u229(d_p1.op);
		mask_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = eaBitStatic__coldfireZdecode95types_u171;
		mask_1 = colontmpD__2;
	}
LA1_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = isEaLegal__coldfireZea_u90(mask_1, d_p1.ea);
		if (!!(T8_)) goto LA9_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA9_: ;
	bitNumber_1 = (NU32)0;
	{
		if (!d_p1.regOperand) goto LA13_;
		bitNumber_1 = regD__coldfireZmachine_u7(ctx_p0, d_p1.destReg);
	}
	goto LA11_;
LA13_: ;
	{
		NU16 T16_;
		T16_ = (NU16)0;
		T16_ = fetchExt__coldfireZmachine_u252(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		bitNumber_1 = ((NU32) (T16_));
		{
			if (!(*ctx_p0).halted) goto LA19_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA19_: ;
	}
LA11_: ;
	bit_1 = (NU32)(bitNumber_1 & (NU32)((NU32)((NU32)((NU32)(((NU32)8)) * (NU32)(((NU32) (d_p1.size))))) - (NU32)(((NU32)1))));
	selector_1 = (NU32)((NU32)(((NU32)1)) << (NU32)(bit_1 & (32 - 1)));
	value_1 = (NU32)0;
	{
		if (!(d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)30))) goto LA23_;
		value_1 = eaRead__coldfireZmachine_u305(ctx_p0, d_p1.ea, d_p1.size);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(*ctx_p0).halted) goto LA27_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA27_: ;
	}
	goto LA21_;
LA23_: ;
	{
		NU32 colontmpD__5;
		NU32 colontmpD__6;
		NU32 colontmpD__7;
		tyObject_EaRef__pKu825coD8roQenraSdRvw dest_1;
		NU32 written_1;
		colontmpD__5 = (NU32)0;
		colontmpD__6 = (NU32)0;
		colontmpD__7 = (NU32)0;
		dest_1 = eaResolve__coldfireZmachine_u333(ctx_p0, d_p1.ea, d_p1.size);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(*ctx_p0).halted) goto LA32_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA32_: ;
		value_1 = eaRefRead__coldfireZmachine_u372(ctx_p0, dest_1, d_p1.size);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(*ctx_p0).halted) goto LA36_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA36_: ;
		switch (d_p1.op) {
		case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)33):
		{
			colontmpD__5 = (NU32)(value_1 | selector_1);
			written_1 = colontmpD__5;
		}
		break;
		case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)32):
		{
			colontmpD__6 = (NU32)(value_1 & (NU32)((NU32) ~(selector_1)));
			written_1 = colontmpD__6;
		}
		break;
		default:
		{
			colontmpD__7 = (NU32)(value_1 ^ selector_1);
			written_1 = colontmpD__7;
		}
		break;
		}
		eaRefWrite__coldfireZmachine_u377(ctx_p0, dest_1, d_p1.size, written_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(*ctx_p0).halted) goto LA43_;
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA43_: ;
	}
LA21_: ;
	wasSet_1 = !(((NU32)(value_1 & selector_1) == ((NU32)0)));
	(*ctx_p0).sr = (NU32)((*ctx_p0).sr & ((NU32)IL64(4294967291)));
	{
		if (!!(wasSet_1)) goto LA47_;
		(*ctx_p0).sr = (NU32)((*ctx_p0).sr | ((NU32)4));
	}
LA47_: ;
	{
		if (!(d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)30))) goto LA51_;
		colontmpD__3 = ((NU32)4);
		result = colontmpD__3;
	}
	goto LA49_;
LA51_: ;
	{
		colontmpD__4 = ((NU32)6);
		result = colontmpD__4;
	}
LA49_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, execShift__coldfireZlogic_u73)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 count_1;
	NIM_BOOL toLeft_1;
	NIM_BOOL T16_;
	NIM_BOOL arithmetic_1;
	NIM_BOOL T18_;
	NU32 value_1;
	NIM_BOOL carry_1;
	NU32 sr_1;
{	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eaIsLegalFor__coldfireZdecode95types_u243(d_p1.op, d_p1.ea);
		if (!!(T3_)) goto LA4_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA4_: ;
	{
		if (!!((d_p1.size == ((NU8)4)))) goto LA8_;
		result = trap__coldfireZlogic_u4(ctx_p0);
		goto BeforeRet_;
	}
LA8_: ;
	{
		NU32 T14_;
		if (!d_p1.regOperand) goto LA12_;
		T14_ = (NU32)0;
		T14_ = regD__coldfireZmachine_u7(ctx_p0, d_p1.destReg);
		colontmpD_ = (NU32)(T14_ & ((NU32)63));
		count_1 = colontmpD_;
	}
	goto LA10_;
LA12_: ;
	{
		colontmpD__2 = ((NU32) (d_p1.imm));
		count_1 = colontmpD__2;
	}
LA10_: ;
	T16_ = (NIM_BOOL)0;
	T16_ = (d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)47));
	if (T16_) goto LA17_;
	T16_ = (d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)49));
LA17_: ;
	toLeft_1 = T16_;
	T18_ = (NIM_BOOL)0;
	T18_ = (d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)47));
	if (T18_) goto LA19_;
	T18_ = (d_p1.op == ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)48));
LA19_: ;
	arithmetic_1 = T18_;
	value_1 = regD__coldfireZmachine_u7(ctx_p0, d_p1.ea.reg);
	carry_1 = NIM_FALSE;
	{
		NI __1;
		NI colontmp_;
		NI i_1;
		__1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (count_1));
		i_1 = ((NI)0);
		{
			while (1) {
				NU32 before_1;
				NI TM__pNdIfJ1qTNtvZN3PcuRynw_2;
				if (!(i_1 < colontmp_)) goto LA22;
				__1 = i_1;
				before_1 = value_1;
				{
					if (!toLeft_1) goto LA25_;
					carry_1 = !(((NU32)(before_1 & ((NU32)IL64(2147483648))) == ((NU32)0)));
					value_1 = (NU32)((NU64)(before_1) << (NU64)(((NI)1) & (32 - 1)));
				}
				goto LA23_;
LA25_: ;
				{
					carry_1 = !(((NU32)(before_1 & ((NU32)1)) == ((NU32)0)));
					value_1 = (NU32)((NU32)(before_1) >> (NU64)(((NI)1) & (32 - 1)));
					{
						NIM_BOOL T30_;
						T30_ = (NIM_BOOL)0;
						T30_ = arithmetic_1;
						if (!(T30_)) goto LA31_;
						T30_ = !(((NU32)(before_1 & ((NU32)IL64(2147483648))) == ((NU32)0)));
LA31_: ;
						if (!T30_) goto LA32_;
						value_1 = (NU32)(value_1 | ((NU32)IL64(2147483648)));
					}
LA32_: ;
				}
LA23_: ;
				if (nimAddInt(i_1, ((NI)1), &TM__pNdIfJ1qTNtvZN3PcuRynw_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__pNdIfJ1qTNtvZN3PcuRynw_2);
			} LA22: ;
		}
	}
	setRegD__coldfireZmachine_u32(ctx_p0, d_p1.ea.reg, value_1);
	sr_1 = (NU32)((*ctx_p0).sr & ((NU32)IL64(4294967280)));
	{
		if (!!(((NU32)(value_1 & ((NU32)IL64(2147483648))) == ((NU32)0)))) goto LA36_;
		sr_1 = (NU32)(sr_1 | ((NU32)8));
	}
LA36_: ;
	{
		if (!(value_1 == ((NU32)0))) goto LA40_;
		sr_1 = (NU32)(sr_1 | ((NU32)4));
	}
LA40_: ;
	{
		if (!carry_1) goto LA44_;
		sr_1 = (NU32)(sr_1 | ((NU32)1));
	}
LA44_: ;
	{
		if (!!((count_1 == ((NU32)0)))) goto LA48_;
		sr_1 = (NU32)(sr_1 & ((NU32)IL64(4294967279)));
		{
			if (!carry_1) goto LA52_;
			sr_1 = (NU32)(sr_1 | ((NU32)16));
		}
LA52_: ;
	}
LA48_: ;
	(*ctx_p0).sr = sr_1;
	result = ((NU32)1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, logicFamily__coldfireZlogic_u113)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU16 word_p1, tyObject_Decoded__5TcmPDN5hGIQQiyUugATWA d_p2) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	NU32 colontmpD__4;
	NU32 colontmpD__5;
	NU32 colontmpD__6;
	NU32 colontmpD__7;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	colontmpD__4 = (NU32)0;
	colontmpD__5 = (NU32)0;
	colontmpD__6 = (NU32)0;
	colontmpD__7 = (NU32)0;
	switch (d_p2.op) {
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)24):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)25):
	{
		colontmpD_ = execAndOr__coldfireZlogic_u12(ctx_p0, d_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)43):
	{
		colontmpD__2 = execEor__coldfireZlogic_u21(ctx_p0, d_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		result = colontmpD__2;
		{
			LA6_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)44):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)45):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)46):
	{
		colontmpD__3 = execImmediate__coldfireZlogic_u32(ctx_p0, d_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		result = colontmpD__3;
		{
			LA10_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)27):
	{
		colontmpD__4 = execNot__coldfireZlogic_u44(ctx_p0, d_p2);
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)30):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)33):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)32):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)31):
	{
		colontmpD__5 = execBitOp__coldfireZlogic_u49(ctx_p0, d_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		result = colontmpD__5;
		{
			LA15_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)47):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)48):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)49):
	case ((tyEnum_Operation__pNMdRDkk0kUJ0kZTzV9cpfQ)50):
	{
		colontmpD__6 = execShift__coldfireZlogic_u73(ctx_p0, d_p2);
		result = colontmpD__6;
	}
	break;
	default:
	{
		colontmpD__7 = trap__coldfireZlogic_u4(ctx_p0);
		result = colontmpD__7;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
