/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ;
typedef struct tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA;
typedef struct tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw;
typedef struct tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA;
typedef struct tyObject_EaRef__pKu825coD8roQenraSdRvw tyObject_EaRef__pKu825coD8roQenraSdRvw;
struct tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA {
	NI a;
	NI b;
};
typedef NI32 tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow;
typedef N_CDECL_PTR(NU32, tyProc__48NbZWzqN9c65MTL6aqhyoQ) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p3);
typedef N_CDECL_PTR(void, tyProc__Z520qbkX3ihqF4aEH1pYnQ) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ {
	void* user;
	void* sim;
	void* cfgIsa;
	void* cfgVbrMask;
	tyProc__48NbZWzqN9c65MTL6aqhyoQ readFn;
	tyProc__Z520qbkX3ihqF4aEH1pYnQ writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
typedef NU8 tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw;
struct tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw {
	tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw mode;
	NU8 reg;
};
typedef NU8 tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A;
typedef NU8 tyEnum_BusAccess__tJiPx6okfC8SVMjGqkKdBA;
typedef NU8 tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw;
struct tyObject_EaRef__pKu825coD8roQenraSdRvw {
	tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw kind;
	NU8 reg;
	NU32 address;
};
N_LIB_EXPORT N_CDECL(int, cf_set_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1, NU32 value_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, regFileSet__coldfireZmachine_u110)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NI index_p1, NU32 v_p2);
static N_INLINE(NIM_BOOL, contains__coldfireZmachine_u90)(tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA s_p0, NI value_p1);
static N_INLINE(tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA, dotdot___coldfireZmachine_u45)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(NU32, cf_get_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, regFileGet__coldfireZmachine_u41)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NI index_p1);
N_LIB_EXPORT N_CDECL(int, cf_halted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_EXPORT N_CDECL(int, cf_faulted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(void, takeExceptionCopiedSr__coldfireZmachine_u391)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3, NU32 stackedSr_p4);
N_LIB_PRIVATE N_NIMCALL(NU32, exceptionFormat__coldfireZmachine_u388)(NU32 sp_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, exceptionFrameBase__coldfireZmachine_u385)(NU32 sp_p0);
N_LIB_PRIVATE N_NIMCALL(void, stackingWrite__coldfireZmachine_u199)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3);
N_LIB_PRIVATE N_NIMCALL(void, boardWrite__coldfireZmachine_u178)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p4);
N_LIB_PRIVATE N_NIMCALL(NU32, sizeMask__coldfireZmachine_u146)(NU8 size_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NU32, frameFirstLongword__coldfireZexception_u6)(NU32 format_p0, NU32 fs_p1, NU8 vector_p2, NU32 sr_p3);
N_LIB_PRIVATE N_NIMCALL(NU32, stackingRead__coldfireZmachine_u189)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, boardRead__coldfireZmachine_u167)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p3);
N_LIB_PRIVATE N_NIMCALL(NU32, vectorAddress__coldfireZexception_u89)(NU32 vbr_p0, NU8 vector_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, regD__coldfireZmachine_u7)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, regA__coldfireZmachine_u11)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, readMem__coldfireZmachine_u214)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isMbarHit__coldfireZmachine_u209)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, simRead__coldfireZsim_u153)(tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA* sim_p0, NU32 offset_p1, NU8 size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p3);
N_LIB_PRIVATE N_NIMCALL(tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA*, ensureSim__coldfireZsim_u111)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, eaAddr__coldfireZmachine_u290)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(void, setRegA__coldfireZmachine_u36)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1, NU32 v_p2);
N_LIB_PRIVATE N_NIMCALL(NI32, s16__coldfireZmachine_u263)(NU16 x_p0);
N_LIB_PRIVATE N_NIMCALL(NU16, fetchExt__coldfireZmachine_u252)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NI32, s8__coldfireZmachine_u266)(NU16 x_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, indexOperand__coldfireZmachine_u269)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU16 ext_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setRegD__coldfireZmachine_u32)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1, NU32 v_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, mergeSized__coldfireZmachine_u153)(NU32 old_p0, NU32 value_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeMem__coldfireZmachine_u233)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3);
N_LIB_PRIVATE N_NIMCALL(void, simWrite__coldfireZsim_u185)(tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA* sim_p0, NU32 offset_p1, NU8 size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p4);
N_LIB_PRIVATE N_NIMCALL(NU32, faultStatusFor__coldfireZbus_u21)(tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow status_p0, tyEnum_BusAccess__tJiPx6okfC8SVMjGqkKdBA access_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, takeException__coldfireZmachine_u400)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3415;
static N_INLINE(NIM_BOOL, contains__coldfireZmachine_u90)(tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA s_p0, NI value_p1) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (s_p0.a <= value_p1);
	if (!(T1_)) goto LA2_;
	T1_ = (value_p1 <= s_p0.b);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA, dotdot___coldfireZmachine_u45)(NI a_p0, NI b_p1) {
	tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, regFileSet__coldfireZmachine_u110)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NI index_p1, NU32 v_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
{	T1_ = (NIM_BOOL)0;
	{
		tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA T4_;
		NIM_BOOL T5_;
		T4_ = dotdot___coldfireZmachine_u45(((NI)0), ((NI)7));
		T5_ = (NIM_BOOL)0;
		T5_ = contains__coldfireZmachine_u90(T4_, index_p1);
		if (!T5_) goto LA6_;
		if ((NU)(index_p1) > (NU)(7)){ raiseIndexError2(index_p1, 7); goto BeforeRet_;
		}
		(*ctx_p0).dRegs[(index_p1)- 0] = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA6_: ;
	{
		tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA T9_;
		NIM_BOOL T10_;
		NI TM__u0VhQuSwCceR4Ho39aRhxrA_2;
		T9_ = dotdot___coldfireZmachine_u45(((NI)8), ((NI)14));
		T10_ = (NIM_BOOL)0;
		T10_ = contains__coldfireZmachine_u90(T9_, index_p1);
		if (!T10_) goto LA11_;
		if (nimSubInt(index_p1, ((NI)8), &TM__u0VhQuSwCceR4Ho39aRhxrA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NU)((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_2)) > (NU)(6)){ raiseIndexError2((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_2), 6); goto BeforeRet_;
		}
		(*ctx_p0).aRegs[((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_2))- 0] = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA11_: ;
	{
		if (!(index_p1 == ((NI)15))) goto LA14_;
		(*ctx_p0).sp = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA14_: ;
	{
		if (!(index_p1 == ((NI)16))) goto LA17_;
		(*ctx_p0).sr = (NU32)(v_p2 & ((NU32)65535));
		result = NIM_TRUE;
	}
	goto LA2_;
LA17_: ;
	{
		if (!(index_p1 == ((NI)18))) goto LA20_;
		(*ctx_p0).vbr = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA20_: ;
	{
		if (!(index_p1 == ((NI)19))) goto LA23_;
		(*ctx_p0).cacr = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA23_: ;
	{
		if (!(index_p1 == ((NI)20))) goto LA26_;
		(*ctx_p0).acr0 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA26_: ;
	{
		if (!(index_p1 == ((NI)21))) goto LA29_;
		(*ctx_p0).acr1 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA29_: ;
	{
		if (!(index_p1 == ((NI)22))) goto LA32_;
		(*ctx_p0).rambar0 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA32_: ;
	{
		if (!(index_p1 == ((NI)23))) goto LA35_;
		(*ctx_p0).rambar1 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA35_: ;
	{
		if (!(index_p1 == ((NI)24))) goto LA38_;
		(*ctx_p0).mbar = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA38_: ;
	{
		if (!(index_p1 == ((NI)25))) goto LA41_;
		(*ctx_p0).acr2 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA41_: ;
	{
		if (!(index_p1 == ((NI)26))) goto LA44_;
		(*ctx_p0).acr3 = v_p2;
		result = NIM_TRUE;
	}
	goto LA2_;
LA44_: ;
	{
		result = NIM_FALSE;
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, cf_set_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1, NU32 value_p2) {
	int result;
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = (index_p1 < ((NI32)0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T3_ = (((NI32)26) < index_p1);
LA6_: ;
		if (!T3_) goto LA7_;
		result = ((int) (((NI)0)));
		goto BeforeRet_;
	}
LA7_: ;
	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = regFileSet__coldfireZmachine_u110(ctx_p0, ((NI) (index_p1)), value_p2);
		if (!T11_) goto LA12_;
		result = ((int) (((NI)1)));
		goto BeforeRet_;
	}
LA12_: ;
	result = ((int) (((NI)0)));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, regFileGet__coldfireZmachine_u41)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NI index_p1) {
	NU32 result;
	NU32 T1_;
{	result = (NU32)0;
	T1_ = (NU32)0;
	{
		tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA T4_;
		NIM_BOOL T5_;
		T4_ = dotdot___coldfireZmachine_u45(((NI)0), ((NI)7));
		T5_ = (NIM_BOOL)0;
		T5_ = contains__coldfireZmachine_u90(T4_, index_p1);
		if (!T5_) goto LA6_;
		if ((NU)(index_p1) > (NU)(7)){ raiseIndexError2(index_p1, 7); goto BeforeRet_;
		}
		result = (*ctx_p0).dRegs[(index_p1)- 0];
	}
	goto LA2_;
LA6_: ;
	{
		tyObject_HSlice__Xds12lJEPVUfUpMuvUCkoA T9_;
		NIM_BOOL T10_;
		NI TM__u0VhQuSwCceR4Ho39aRhxrA_3;
		T9_ = dotdot___coldfireZmachine_u45(((NI)8), ((NI)14));
		T10_ = (NIM_BOOL)0;
		T10_ = contains__coldfireZmachine_u90(T9_, index_p1);
		if (!T10_) goto LA11_;
		if (nimSubInt(index_p1, ((NI)8), &TM__u0VhQuSwCceR4Ho39aRhxrA_3)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NU)((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_3)) > (NU)(6)){ raiseIndexError2((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_3), 6); goto BeforeRet_;
		}
		result = (*ctx_p0).aRegs[((NI)(TM__u0VhQuSwCceR4Ho39aRhxrA_3))- 0];
	}
	goto LA2_;
LA11_: ;
	{
		if (!(index_p1 == ((NI)15))) goto LA14_;
		result = (*ctx_p0).sp;
	}
	goto LA2_;
LA14_: ;
	{
		if (!(index_p1 == ((NI)16))) goto LA17_;
		result = (*ctx_p0).sr;
	}
	goto LA2_;
LA17_: ;
	{
		if (!(index_p1 == ((NI)17))) goto LA20_;
		result = (*ctx_p0).pc;
	}
	goto LA2_;
LA20_: ;
	{
		if (!(index_p1 == ((NI)18))) goto LA23_;
		result = (*ctx_p0).vbr;
	}
	goto LA2_;
LA23_: ;
	{
		if (!(index_p1 == ((NI)19))) goto LA26_;
		result = (*ctx_p0).cacr;
	}
	goto LA2_;
LA26_: ;
	{
		if (!(index_p1 == ((NI)20))) goto LA29_;
		result = (*ctx_p0).acr0;
	}
	goto LA2_;
LA29_: ;
	{
		if (!(index_p1 == ((NI)21))) goto LA32_;
		result = (*ctx_p0).acr1;
	}
	goto LA2_;
LA32_: ;
	{
		if (!(index_p1 == ((NI)22))) goto LA35_;
		result = (*ctx_p0).rambar0;
	}
	goto LA2_;
LA35_: ;
	{
		if (!(index_p1 == ((NI)23))) goto LA38_;
		result = (*ctx_p0).rambar1;
	}
	goto LA2_;
LA38_: ;
	{
		if (!(index_p1 == ((NI)24))) goto LA41_;
		result = (*ctx_p0).mbar;
	}
	goto LA2_;
LA41_: ;
	{
		if (!(index_p1 == ((NI)25))) goto LA44_;
		result = (*ctx_p0).acr2;
	}
	goto LA2_;
LA44_: ;
	{
		if (!(index_p1 == ((NI)26))) goto LA47_;
		result = (*ctx_p0).acr3;
	}
	goto LA2_;
LA47_: ;
	{
		result = ((NU32)0);
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NU32, cf_get_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1) {
	NU32 result;
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = (index_p1 < ((NI32)0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T3_ = (((NI32)26) < index_p1);
LA6_: ;
		if (!T3_) goto LA7_;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA7_: ;
	result = regFileGet__coldfireZmachine_u41(ctx_p0, ((NI) (index_p1)));
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, cf_halted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	int result;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !((*ctx_p0).halted);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((int) (((NI)0)));
		goto BeforeRet_;
	}
LA5_: ;
	result = ((int) (((NI)1)));
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, cf_faulted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	int result;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !((*ctx_p0).fault);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((int) (((NI)0)));
		goto BeforeRet_;
	}
LA5_: ;
	result = ((int) (((NI)1)));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, exceptionFormat__coldfireZmachine_u388)(NU32 sp_p0) {
	NU32 result;
	result = (NU32)((NU32)(((NU32)4)) + (NU32)((NU32)(sp_p0 & ((NU32)3))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, exceptionFrameBase__coldfireZmachine_u385)(NU32 sp_p0) {
	NU32 result;
	result = (NU32)((NU32)((NU32)(sp_p0) - (NU32)(((NU32)8))) & ((NU32)IL64(4294967292)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, sizeMask__coldfireZmachine_u146)(NU8 size_p0) {
	NU32 result;
	NU32 T1_;
	T1_ = (NU32)0;
	{
		if (!(size_p0 == ((NU8)4))) goto LA4_;
		result = ((NU32)IL64(4294967295));
	}
	goto LA2_;
LA4_: ;
	{
		result = (NU32)((NU32)((NU32)((NU32)(((NU32)1)) << (NU32)((NU8)((NU8)(((NU8)8)) * (NU8)(size_p0)) & (32 - 1)))) - (NU32)(((NU32)1)));
	}
LA2_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, boardWrite__coldfireZmachine_u178)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p4) {
	NU32 T5_;
{	(*st_p4) = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	{
		if (!((*ctx_p0).writeFn == 0)) goto LA3_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
		goto BeforeRet_;
	}
LA3_: ;
	T5_ = (NU32)0;
	T5_ = sizeMask__coldfireZmachine_u146(size_p2);
	(*ctx_p0).writeFn((*ctx_p0).user, address_p1, ((int) (size_p2)), (NU32)(value_p3 & T5_), st_p4);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3415);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stackingWrite__coldfireZmachine_u199)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3) {
	tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow st_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	boardWrite__coldfireZmachine_u178(ctx_p0, address_p1, size_p2, value_p3, (&st_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!((st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0)))) goto LA3_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, boardRead__coldfireZmachine_u167)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* st_p3) {
	NU32 result;
{	(*st_p3) = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	{
		if (!((*ctx_p0).readFn == 0)) goto LA3_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA3_: ;
	result = (*ctx_p0).readFn((*ctx_p0).user, address_p1, ((int) (size_p2)), st_p3);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, stackingRead__coldfireZmachine_u189)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2) {
	NU32 result;
	tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow st_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	result = boardRead__coldfireZmachine_u167(ctx_p0, address_p1, size_p2, (&st_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!((st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0)))) goto LA3_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, takeExceptionCopiedSr__coldfireZmachine_u391)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3, NU32 stackedSr_p4) {
	NU32 format_1;
	NU32 base_1;
	NU32 T1_;
	NU32 handler_1;
	NU32 T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	(*ctx_p0).sr = (NU32)((NU32)((*ctx_p0).sr | ((NU32)8192)) & ((NU32)IL64(4294934527)));
	format_1 = exceptionFormat__coldfireZmachine_u388((*ctx_p0).sp);
	base_1 = exceptionFrameBase__coldfireZmachine_u385((*ctx_p0).sp);
	T1_ = (NU32)0;
	T1_ = frameFirstLongword__coldfireZexception_u6(format_1, fs_p3, vector_p1, stackedSr_p4);
	stackingWrite__coldfireZmachine_u199(ctx_p0, base_1, ((NU8)4), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	stackingWrite__coldfireZmachine_u199(ctx_p0, (NU32)((NU32)(base_1) + (NU32)(((NU32)4))), ((NU8)4), stackedPc_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA8_;
		goto BeforeRet_;
	}
LA8_: ;
	(*ctx_p0).sp = base_1;
	T10_ = (NU32)0;
	T10_ = vectorAddress__coldfireZexception_u89((*ctx_p0).vbr, vector_p1);
	handler_1 = stackingRead__coldfireZmachine_u189(ctx_p0, T10_, ((NU8)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA13_;
		goto BeforeRet_;
	}
LA13_: ;
	(*ctx_p0).pc = handler_1;
	(*ctx_p0).atHandlerEntry = NIM_TRUE;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, takeException__coldfireZmachine_u400)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	takeExceptionCopiedSr__coldfireZmachine_u391(ctx_p0, vector_p1, stackedPc_p2, fs_p3, (NU32)((*ctx_p0).sr & ((NU32)65535)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, regD__coldfireZmachine_u7)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1) {
	NU32 result;
{	if ((NU)((NU8)(n_p1 & ((NU8)7))) > (NU)(7)){ raiseIndexError2((NU8)(n_p1 & ((NU8)7)), 7); goto BeforeRet_;
	}
	result = (*ctx_p0).dRegs[((NU8)(n_p1 & ((NU8)7)))- 0];
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, regA__coldfireZmachine_u11)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU8 k_1;
{	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	k_1 = (NU8)(n_p1 & ((NU8)7));
	{
		if (!(k_1 == ((NU8)7))) goto LA3_;
		colontmpD_ = (*ctx_p0).sp;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		if ((NU)(k_1) > (NU)(6)){ raiseIndexError2(k_1, 6); goto BeforeRet_;
		}
		colontmpD__2 = (*ctx_p0).aRegs[(k_1)- 0];
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isMbarHit__coldfireZmachine_u209)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	{
		NU32 base_1;
		if (!!(((NU32)((*ctx_p0).mbar & ((NU32)1)) == ((NU32)0)))) goto LA4_;
		base_1 = (NU32)((*ctx_p0).mbar & ((NU32)IL64(4294963200)));
		result = ((NU32)(address_p1 & ((NU32)IL64(4294963200))) == base_1);
	}
	goto LA2_;
LA4_: ;
	{
		result = NIM_FALSE;
	}
LA2_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, readMem__coldfireZmachine_u214)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2) {
	NU32 result;
	tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow st_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	result = boardRead__coldfireZmachine_u167(ctx_p0, address_p1, size_p2, (&st_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NU32 offset_1;
		tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA* T11_;
		T7_ = (NIM_BOOL)0;
		T7_ = (st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)1));
		if (!(T7_)) goto LA8_;
		T7_ = isMbarHit__coldfireZmachine_u209(ctx_p0, address_p1);
LA8_: ;
		if (!T7_) goto LA9_;
		st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
		offset_1 = (NU32)(address_p1 & ((NU32)4095));
		T11_ = (tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA*)0;
		T11_ = ensureSim__coldfireZsim_u111(ctx_p0);
		result = simRead__coldfireZsim_u153(T11_, offset_1, size_p2, (&st_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	{
		if (!!((st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0)))) goto LA14_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
	}
LA14_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setRegA__coldfireZmachine_u36)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1, NU32 v_p2) {
	NU8 k_1;
{	k_1 = (NU8)(n_p1 & ((NU8)7));
	{
		if (!(k_1 == ((NU8)7))) goto LA3_;
		(*ctx_p0).sp = v_p2;
	}
	goto LA1_;
LA3_: ;
	{
		if ((NU)(k_1) > (NU)(6)){ raiseIndexError2(k_1, 6); goto BeforeRet_;
		}
		(*ctx_p0).aRegs[(k_1)- 0] = v_p2;
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI32, s16__coldfireZmachine_u263)(NU16 x_p0) {
	NI32 result;
	result = ((NI32) (((NI16) (x_p0))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU16, fetchExt__coldfireZmachine_u252)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	NU16 result;
	tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow st_1;
	NU32 v_1;
{	result = (NU16)0;
	st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	v_1 = (*ctx_p0).readFn((*ctx_p0).user, (*ctx_p0).pc, ((int)2), (&st_1));
	{
		if (!!((st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0)))) goto LA3_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
		result = ((NU16)0);
		goto BeforeRet_;
	}
LA3_: ;
	(*ctx_p0).pc = (NU32)((NU32)((*ctx_p0).pc) + (NU32)(((NU32)2)));
	result = ((NU16) ((NU32)(v_1 & ((NU32)65535))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, s8__coldfireZmachine_u266)(NU16 x_p0) {
	NI32 result;
	result = (NI32)0;
	result = ((NI32) (((NI8) (((NU8) ((NU16)(x_p0 & ((NU16)255))))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, indexOperand__coldfireZmachine_u269)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU16 ext_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NIM_BOOL isAn_1;
	NU16 n_1;
	NU16 scale_1;
	NIM_BOOL longIndex_1;
	NU32 v_1;
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	isAn_1 = !(((NU16)(ext_p1 & ((NU16)32768)) == ((NU16)0)));
	n_1 = (NU16)((NU16)((NU16)(ext_p1) >> (NU64)(((NI)12) & (16 - 1))) & ((NU16)7));
	scale_1 = (NU16)((NU16)((NU16)(ext_p1) >> (NU64)(((NI)9) & (16 - 1))) & ((NU16)3));
	longIndex_1 = !(((NU16)(ext_p1 & ((NU16)2048)) == ((NU16)0)));
	{
		if (!isAn_1) goto LA3_;
		colontmpD_ = regA__coldfireZmachine_u11(ctx_p0, ((NU8) (n_1)));
		v_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = regD__coldfireZmachine_u7(ctx_p0, ((NU8) (n_1)));
		v_1 = colontmpD__2;
	}
LA1_: ;
	{
		NI32 T10_;
		if (!!(longIndex_1)) goto LA8_;
		T10_ = (NI32)0;
		T10_ = s16__coldfireZmachine_u263(((NU16) ((NU32)(v_1 & ((NU32)65535)))));
		v_1 = ((NU32) (T10_));
	}
LA8_: ;
	result = (NU32)((NU32)(v_1) << (NU32)(scale_1 & (32 - 1)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, eaAddr__coldfireZmachine_u290)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2) {
	NU32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	switch (ea_p1.mode) {
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)2):
	{
		result = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)3):
	{
		result = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
		setRegA__coldfireZmachine_u36(ctx_p0, ea_p1.reg, (NU32)((NU32)(result) + (NU32)(((NU32) (size_p2)))));
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)4):
	{
		NU32 T4_;
		T4_ = (NU32)0;
		T4_ = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
		result = (NU32)((NU32)(T4_) - (NU32)(((NU32) (size_p2))));
		setRegA__coldfireZmachine_u36(ctx_p0, ea_p1.reg, result);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)5):
	{
		NU32 T6_;
		NU16 T7_;
		NI32 T8_;
		T6_ = (NU32)0;
		T6_ = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
		T7_ = (NU16)0;
		T7_ = fetchExt__coldfireZmachine_u252(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T8_ = (NI32)0;
		T8_ = s16__coldfireZmachine_u263(T7_);
		result = (NU32)((NU32)(T6_) + (NU32)(((NU32) (T8_))));
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)6):
	{
		NU16 ext_1;
		NU32 T10_;
		NI32 T11_;
		NU32 T12_;
		ext_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = (NU32)0;
		T10_ = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
		T11_ = (NI32)0;
		T11_ = s8__coldfireZmachine_u266(ext_1);
		T12_ = (NU32)0;
		T12_ = indexOperand__coldfireZmachine_u269(ctx_p0, ext_1);
		result = (NU32)((NU32)((NU32)((NU32)(T10_) + (NU32)(((NU32) (T11_))))) + (NU32)(T12_));
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)7):
	{
		if ((ea_p1.reg) < ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0) || (ea_p1.reg) > ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)){ raiseRangeErrorI(ea_p1.reg, ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0), ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)); goto BeforeRet_;
		}
		switch (((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A) (ea_p1.reg))) {
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0):
		{
			NU16 T15_;
			NI32 T16_;
			T15_ = (NU16)0;
			T15_ = fetchExt__coldfireZmachine_u252(ctx_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T16_ = (NI32)0;
			T16_ = s16__coldfireZmachine_u263(T15_);
			result = ((NU32) (T16_));
		}
		break;
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)1):
		{
			NU16 hi_1;
			NU16 lo_1;
			hi_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			lo_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = (NU32)((NU32)((NU64)(((NU32) (hi_1))) << (NU64)(((NI)16) & (32 - 1))) | ((NU32) (lo_1)));
		}
		break;
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)2):
		{
			NU32 base_1;
			NU16 T19_;
			NI32 T20_;
			base_1 = (*ctx_p0).pc;
			T19_ = (NU16)0;
			T19_ = fetchExt__coldfireZmachine_u252(ctx_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T20_ = (NI32)0;
			T20_ = s16__coldfireZmachine_u263(T19_);
			result = (NU32)((NU32)(base_1) + (NU32)(((NU32) (T20_))));
		}
		break;
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)3):
		{
			NU32 base_2;
			NU16 ext_2;
			NI32 T22_;
			NU32 T23_;
			base_2 = (*ctx_p0).pc;
			ext_2 = fetchExt__coldfireZmachine_u252(ctx_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T22_ = (NI32)0;
			T22_ = s8__coldfireZmachine_u266(ext_2);
			T23_ = (NU32)0;
			T23_ = indexOperand__coldfireZmachine_u269(ctx_p0, ext_2);
			result = (NU32)((NU32)((NU32)((NU32)(base_2) + (NU32)(((NU32) (T22_))))) + (NU32)(T23_));
		}
		break;
		default:
		{
			(*ctx_p0).fault = NIM_TRUE;
			(*ctx_p0).halted = NIM_TRUE;
			result = ((NU32)0);
		}
		break;
		}
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, eaRead__coldfireZmachine_u305)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2) {
	NU32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	switch (ea_p1.mode) {
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)0):
	{
		result = regD__coldfireZmachine_u7(ctx_p0, ea_p1.reg);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)1):
	{
		result = regA__coldfireZmachine_u11(ctx_p0, ea_p1.reg);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)2):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)3):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)4):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)5):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)6):
	{
		NU32 T4_;
		T4_ = (NU32)0;
		T4_ = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = readMem__coldfireZmachine_u214(ctx_p0, T4_, size_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)7):
	{
		if ((ea_p1.reg) < ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0) || (ea_p1.reg) > ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)){ raiseRangeErrorI(ea_p1.reg, ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0), ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)); goto BeforeRet_;
		}
		switch (((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A) (ea_p1.reg))) {
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0):
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)1):
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)2):
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)3):
		{
			NU32 T7_;
			T7_ = (NU32)0;
			T7_ = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = readMem__coldfireZmachine_u214(ctx_p0, T7_, size_p2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)4):
		{
			{
				NU16 hi_1;
				NU16 lo_1;
				if (!(size_p2 == ((NU8)4))) goto LA11_;
				hi_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				lo_1 = fetchExt__coldfireZmachine_u252(ctx_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result = (NU32)((NU32)((NU64)(((NU32) (hi_1))) << (NU64)(((NI)16) & (32 - 1))) | ((NU32) (lo_1)));
			}
			goto LA9_;
LA11_: ;
			{
				NU16 T14_;
				T14_ = (NU16)0;
				T14_ = fetchExt__coldfireZmachine_u252(ctx_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result = ((NU32) (T14_));
			}
LA9_: ;
		}
		break;
		default:
		{
			(*ctx_p0).fault = NIM_TRUE;
			(*ctx_p0).halted = NIM_TRUE;
			result = ((NU32)0);
		}
		break;
		}
	}
	break;
	default: __assume(0);
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setRegD__coldfireZmachine_u32)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 n_p1, NU32 v_p2) {
{	if ((NU)((NU8)(n_p1 & ((NU8)7))) > (NU)(7)){ raiseIndexError2((NU8)(n_p1 & ((NU8)7)), 7); goto BeforeRet_;
	}
	(*ctx_p0).dRegs[((NU8)(n_p1 & ((NU8)7)))- 0] = v_p2;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, mergeSized__coldfireZmachine_u153)(NU32 old_p0, NU32 value_p1, NU8 size_p2) {
	NU32 result;
	NU32 T1_;
	NU32 T2_;
	T1_ = (NU32)0;
	T1_ = sizeMask__coldfireZmachine_u146(size_p2);
	T2_ = (NU32)0;
	T2_ = sizeMask__coldfireZmachine_u146(size_p2);
	result = (NU32)((NU32)(old_p0 & (NU32)((NU32) ~(T1_))) | (NU32)(value_p1 & T2_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeMem__coldfireZmachine_u233)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 address_p1, NU8 size_p2, NU32 value_p3) {
	tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow st_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
	boardWrite__coldfireZmachine_u178(ctx_p0, address_p1, size_p2, value_p3, (&st_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NU32 offset_1;
		tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA* T11_;
		T7_ = (NIM_BOOL)0;
		T7_ = (st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)1));
		if (!(T7_)) goto LA8_;
		T7_ = isMbarHit__coldfireZmachine_u209(ctx_p0, address_p1);
LA8_: ;
		if (!T7_) goto LA9_;
		st_1 = ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0);
		offset_1 = (NU32)(address_p1 & ((NU32)4095));
		T11_ = (tyObject_SimObj__BpVhl06QQC3N9bA8zEV8uSA*)0;
		T11_ = ensureSim__coldfireZsim_u111(ctx_p0);
		simWrite__coldfireZsim_u185(T11_, offset_1, size_p2, value_p3, (&st_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = !((st_1 == ((tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow)0)));
		if (!(T14_)) goto LA15_;
		T14_ = !((*ctx_p0).pendingWriteFault);
LA15_: ;
		if (!T14_) goto LA16_;
		(*ctx_p0).pendingWriteFault = NIM_TRUE;
		(*ctx_p0).pendingFaultStatus = faultStatusFor__coldfireZbus_u21(st_1, ((tyEnum_BusAccess__tJiPx6okfC8SVMjGqkKdBA)1));
		(*ctx_p0).pendingStackedSr = (NU32)((*ctx_p0).sr & ((NU32)65535));
	}
LA16_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eaWrite__coldfireZmachine_u316)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2, NU32 value_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch (ea_p1.mode) {
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)0):
	{
		NU32 T2_;
		NU32 T3_;
		T2_ = (NU32)0;
		T2_ = regD__coldfireZmachine_u7(ctx_p0, ea_p1.reg);
		T3_ = (NU32)0;
		T3_ = mergeSized__coldfireZmachine_u153(T2_, value_p3, size_p2);
		setRegD__coldfireZmachine_u32(ctx_p0, ea_p1.reg, T3_);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)1):
	{
		setRegA__coldfireZmachine_u36(ctx_p0, ea_p1.reg, value_p3);
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)2):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)3):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)4):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)5):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)6):
	{
		NU32 T6_;
		T6_ = (NU32)0;
		T6_ = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		writeMem__coldfireZmachine_u233(ctx_p0, T6_, size_p2, value_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)7):
	{
		if ((ea_p1.reg) < ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0) || (ea_p1.reg) > ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)){ raiseRangeErrorI(ea_p1.reg, ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0), ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)); goto BeforeRet_;
		}
		switch (((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A) (ea_p1.reg))) {
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0):
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)1):
		{
			NU32 T9_;
			T9_ = (NU32)0;
			T9_ = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			writeMem__coldfireZmachine_u233(ctx_p0, T9_, size_p2, value_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		default:
		{
			(*ctx_p0).fault = NIM_TRUE;
			(*ctx_p0).halted = NIM_TRUE;
		}
		break;
		}
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setNzClearVc__coldfireZmachine_u158)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 value_p1, NU8 size_p2) {
	NU8 msb_1;
	(*ctx_p0).sr = (NU32)((*ctx_p0).sr & ((NU32)IL64(4294967280)));
	msb_1 = (NU8)((NU8)((NU8)((NU8)(((NU8)8)) * (NU8)(size_p2))) - (NU8)(((NU8)1)));
	{
		if (!!(((NU32)((NU32)((NU32)(value_p1) >> (NU32)(msb_1 & (32 - 1))) & ((NU32)1)) == ((NU32)0)))) goto LA3_;
		(*ctx_p0).sr = (NU32)((*ctx_p0).sr | ((NU32)8));
	}
LA3_: ;
	{
		NU32 T7_;
		T7_ = (NU32)0;
		T7_ = sizeMask__coldfireZmachine_u146(size_p2);
		if (!((NU32)(value_p1 & T7_) == ((NU32)0))) goto LA8_;
		(*ctx_p0).sr = (NU32)((*ctx_p0).sr | ((NU32)4));
	}
LA8_: ;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EaRef__pKu825coD8roQenraSdRvw, eaResolve__coldfireZmachine_u333)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EA__vu8s1WzZCV8fpGlcLcKNYw ea_p1, NU8 size_p2) {
	tyObject_EaRef__pKu825coD8roQenraSdRvw result;
	tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD_;
	tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD__2;
	tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD__3;
	tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD__4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
	nimZeroMem((void*)(&colontmpD__4), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
	switch (ea_p1.mode) {
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)0):
	{
		nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
		colontmpD_.kind = ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)1);
		colontmpD_.reg = ea_p1.reg;
		result = colontmpD_;
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)1):
	{
		nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
		colontmpD__2.kind = ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)2);
		colontmpD__2.reg = ea_p1.reg;
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)2):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)3):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)4):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)5):
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)6):
	{
		nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
		colontmpD__3.kind = ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)3);
		colontmpD__3.address = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		result = colontmpD__3;
		{
			LA4_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_EAMode__GYzbIutsW1sIc5APH3Hm9bw)7):
	{
		tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD__5;
		tyObject_EaRef__pKu825coD8roQenraSdRvw colontmpD__6;
		nimZeroMem((void*)(&colontmpD__5), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
		nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
		if ((ea_p1.reg) < ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0) || (ea_p1.reg) > ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)){ raiseRangeErrorI(ea_p1.reg, ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0), ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)7)); goto LA8_;
		}
		switch (((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A) (ea_p1.reg))) {
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)0):
		case ((tyEnum_EA7__FaSzBWDgPqsFk7cyrHU07A)1):
		{
			nimZeroMem((void*)(&colontmpD__5), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
			colontmpD__5.kind = ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)3);
			colontmpD__5.address = eaAddr__coldfireZmachine_u290(ctx_p0, ea_p1, size_p2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			colontmpD__4 = colontmpD__5;
			{
				LA10_:;
			}
			{
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		}
		break;
		default:
		{
			(*ctx_p0).fault = NIM_TRUE;
			(*ctx_p0).halted = NIM_TRUE;
			nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_EaRef__pKu825coD8roQenraSdRvw));
			colontmpD__6.kind = ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)0);
			colontmpD__4 = colontmpD__6;
		}
		break;
		}
		result = colontmpD__4;
		{
			LA8_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __assume(0);
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, eaRefRead__coldfireZmachine_u372)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EaRef__pKu825coD8roQenraSdRvw r_p1, NU8 size_p2) {
	NU32 result;
	NU32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	T1_ = (NU32)0;
	switch (r_p1.kind) {
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)1):
	{
		result = regD__coldfireZmachine_u7(ctx_p0, r_p1.reg);
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)2):
	{
		result = regA__coldfireZmachine_u11(ctx_p0, r_p1.reg);
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)3):
	{
		result = readMem__coldfireZmachine_u214(ctx_p0, r_p1.address, size_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)0):
	{
		result = ((NU32)0);
	}
	break;
	default: __assume(0);
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eaRefWrite__coldfireZmachine_u377)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, tyObject_EaRef__pKu825coD8roQenraSdRvw r_p1, NU8 size_p2, NU32 value_p3) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch (r_p1.kind) {
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)1):
	{
		NU32 T2_;
		NU32 T3_;
		T2_ = (NU32)0;
		T2_ = regD__coldfireZmachine_u7(ctx_p0, r_p1.reg);
		T3_ = (NU32)0;
		T3_ = mergeSized__coldfireZmachine_u153(T2_, value_p3, size_p2);
		setRegD__coldfireZmachine_u32(ctx_p0, r_p1.reg, T3_);
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)2):
	{
		setRegA__coldfireZmachine_u36(ctx_p0, r_p1.reg, value_p3);
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)3):
	{
		writeMem__coldfireZmachine_u233(ctx_p0, r_p1.address, size_p2, value_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_EaRefKind__NEiQPwr1n1wIVBCQJ6lm9bw)0):
	{
	}
	break;
	default: __assume(0);
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, pendingWriteFaultTakesCc__coldfireZmachine_u410)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	{
		if (!(*ctx_p0).pendingWriteFault) goto LA3_;
		(*ctx_p0).pendingStackedSr = (NU32)((*ctx_p0).sr & ((NU32)65535));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, transferControl__coldfireZmachine_u412)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 target_p1, NU32 faultPc_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!(((NU32)(target_p1 & ((NU32)1)) == ((NU32)0)))) goto LA3_;
		takeException__coldfireZmachine_u400(ctx_p0, ((NU8)3), faultPc_p2, ((NU32)4));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		(*ctx_p0).pc = target_p1;
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, takePendingWriteFault__coldfireZmachine_u405)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 insnPc_p1) {
	NU32 stackedSr_1;
	NU32 fs_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((*ctx_p0).pendingWriteFault)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	stackedSr_1 = (*ctx_p0).pendingStackedSr;
	fs_1 = (*ctx_p0).pendingFaultStatus;
	(*ctx_p0).pendingWriteFault = NIM_FALSE;
	(*ctx_p0).pendingStackedSr = ((NU32)0);
	(*ctx_p0).pendingFaultStatus = ((NU32)0);
	{
		if (!(*ctx_p0).halted) goto LA7_;
		goto BeforeRet_;
	}
LA7_: ;
	{
		if (!(*ctx_p0).atHandlerEntry) goto LA11_;
		(*ctx_p0).fault = NIM_TRUE;
		(*ctx_p0).halted = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	takeExceptionCopiedSr__coldfireZmachine_u391(ctx_p0, ((NU8)2), insnPc_p1, fs_1, stackedSr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
