/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ;
typedef struct tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw;
typedef N_CDECL_PTR(void, tyProc__ojFZVXWdl1RoZhPnbPZUvQ) (void* user_p0, NU8 byte_p1);
typedef NU8 tyArray__ZphrDPKIBlVgF9aQajgV8qQ[4];
struct tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ {
	NI interruptIndex;
	tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc;
	tyProc__ojFZVXWdl1RoZhPnbPZUvQ txCallback;
	void* txUser;
	NU8 umr1;
	NU8 umr2;
	NIM_BOOL modeUmr1;
	NU8 ucsr;
	NU8 uacr;
	NU8 uimr;
	NU8 ubg1;
	NU8 ubg2;
	NU8 uivr;
	tyArray__ZphrDPKIBlVgF9aQajgV8qQ rxFifo;
	NI rxCount;
	NI rxHead;
	NIM_BOOL txEnabled;
	NIM_BOOL rxEnabled;
	NU8 txHolding;
	NIM_BOOL txHoldingValid;
	NIM_BOOL interruptAsserted;
};
typedef NU8 tyArray__Pu3SVivFPiiTdvogs5S4RQ[12];
typedef NIM_BOOL tyArray__v9awdnBJNClaxp5DAvHayvQ[10];
typedef NIM_BOOL tyArray__oQcYT9cTpIXElOJwwEHsv5g[4];
typedef NU8 tyArray__kAtU2KkWJ4IWiiLIkcMTHQ[10];
struct tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw {
	void* ctx;
	NU8 irqpar;
	NU8 avr;
	tyArray__Pu3SVivFPiiTdvogs5S4RQ icr;
	NU32 ipr;
	NU32 imr;
	tyArray__v9awdnBJNClaxp5DAvHayvQ internalPending;
	tyArray__oQcYT9cTpIXElOJwwEHsv5g externalPending;
	tyArray__kAtU2KkWJ4IWiiLIkcMTHQ internalVector;
	tyArray__ZphrDPKIBlVgF9aQajgV8qQ externalVector;
	NI lastLevel;
	NU8 lastVector;
	NIM_BOOL lastAutovector;
	NIM_BOOL presentedToCore;
};
N_LIB_PRIVATE N_NIMCALL(void, recomputeInterrupt__mcf5407Zuart_u53)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0);
N_LIB_PRIVATE N_NIMCALL(NU8, uisr__mcf5407Zuart_u49)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0);
N_LIB_PRIVATE N_NIMCALL(void, setInternalVector__mcf5407Zintc_u222)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0, NI index_p1, NU8 vector_p2);
N_LIB_PRIVATE N_NIMCALL(void, setInternalPending__mcf5407Zintc_u214)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0, NI index_p1, NIM_BOOL asserted_p2);
N_LIB_PRIVATE N_NIMCALL(NU8, usr__mcf5407Zuart_u45)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zuart_u60)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0);
N_LIB_PRIVATE N_NIMCALL(void, command__mcf5407Zuart_u96)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU8 cmd_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, uisr__mcf5407Zuart_u49)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0) {
	NU8 result;
	NU8 res_1;
	res_1 = ((NU8)0);
	{
		if (!(((NI)0) < (*u_p0).rxCount)) goto LA3_;
		res_1 = (NU8)(res_1 | ((NU8)4));
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (*u_p0).txEnabled;
		if (!(T7_)) goto LA8_;
		T7_ = !((*u_p0).txHoldingValid);
LA8_: ;
		if (!T7_) goto LA9_;
		res_1 = (NU8)(res_1 | ((NU8)2));
	}
LA9_: ;
	result = res_1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, recomputeInterrupt__mcf5407Zuart_u53)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0) {
	NU8 st_1;
	NIM_BOOL asserted_1;
	st_1 = uisr__mcf5407Zuart_u49(u_p0);
	asserted_1 = !(((NU8)(st_1 & (*u_p0).uimr) == ((NU8)0)));
	{
		if (!!((asserted_1 == (*u_p0).interruptAsserted))) goto LA3_;
		(*u_p0).interruptAsserted = asserted_1;
		{
			if (!!(((*u_p0).intc == 0))) goto LA7_;
			setInternalVector__mcf5407Zintc_u222((*u_p0).intc, (*u_p0).interruptIndex, (*u_p0).uivr);
			setInternalPending__mcf5407Zintc_u214((*u_p0).intc, (*u_p0).interruptIndex, asserted_1);
		}
LA7_: ;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zuart_u60)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0) {
	(*u_p0).umr1 = ((NU8)0);
	(*u_p0).umr2 = ((NU8)0);
	(*u_p0).modeUmr1 = NIM_TRUE;
	(*u_p0).ucsr = ((NU8)0);
	(*u_p0).uacr = ((NU8)0);
	(*u_p0).uimr = ((NU8)0);
	(*u_p0).ubg1 = ((NU8)0);
	(*u_p0).ubg2 = ((NU8)0);
	(*u_p0).uivr = ((NU8)15);
	(*u_p0).rxCount = ((NI)0);
	(*u_p0).rxHead = ((NI)0);
	(*u_p0).txEnabled = NIM_FALSE;
	(*u_p0).rxEnabled = NIM_FALSE;
	(*u_p0).txHoldingValid = NIM_FALSE;
	(*u_p0).interruptAsserted = NIM_FALSE;
	recomputeInterrupt__mcf5407Zuart_u53(u_p0);
}
N_LIB_PRIVATE N_NIMCALL(NU8, usr__mcf5407Zuart_u45)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0) {
	NU8 result;
	NU8 res_1;
	res_1 = ((NU8)0);
	{
		if (!(*u_p0).txEnabled) goto LA3_;
		{
			if (!!((*u_p0).txHoldingValid)) goto LA7_;
			res_1 = (NU8)(res_1 | ((NU8)12));
		}
		goto LA5_;
LA7_: ;
		{
			res_1 = (NU8)(res_1 | ((NU8)4));
		}
LA5_: ;
	}
	goto LA1_;
LA3_: ;
	{
		res_1 = (NU8)(res_1 | ((NU8)8));
	}
LA1_: ;
	{
		if (!(((NI)0) < (*u_p0).rxCount)) goto LA13_;
		res_1 = (NU8)(res_1 | ((NU8)1));
	}
LA13_: ;
	{
		if (!(((NI)4) <= (*u_p0).rxCount)) goto LA17_;
		res_1 = (NU8)(res_1 | ((NU8)2));
	}
LA17_: ;
	result = res_1;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__mcf5407Zuart_u110)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU32 offset_p1) {
	NU8 result;
	NU8 T1_;
{	result = (NU8)0;
	T1_ = (NU8)0;
	switch (offset_p1) {
	case ((NU32)0):
	{
		NU8 colontmpD_;
		NU8 colontmpD__2;
		colontmpD_ = (NU8)0;
		colontmpD__2 = (NU8)0;
		{
			if (!(*u_p0).modeUmr1) goto LA5_;
			(*u_p0).modeUmr1 = NIM_FALSE;
			colontmpD_ = (*u_p0).umr1;
			result = colontmpD_;
		}
		goto LA3_;
LA5_: ;
		{
			colontmpD__2 = (*u_p0).umr2;
			result = colontmpD__2;
		}
LA3_: ;
	}
	break;
	case ((NU32)4):
	{
		result = usr__mcf5407Zuart_u45(u_p0);
	}
	break;
	case ((NU32)12):
	{
		NU8 colontmpD__3;
		NU8 colontmpD__4;
		colontmpD__3 = (NU8)0;
		colontmpD__4 = (NU8)0;
		{
			NU8 byte_1;
			NI TM__WRV4qATsPXb7XfllB2fyCg_2;
			NI TM__WRV4qATsPXb7XfllB2fyCg_3;
			if (!(((NI)0) < (*u_p0).rxCount)) goto LA12_;
			if ((NU)((*u_p0).rxHead) > (NU)(3)){ raiseIndexError2((*u_p0).rxHead, 3); goto BeforeRet_;
			}
			byte_1 = (*u_p0).rxFifo[((*u_p0).rxHead)- 0];
			if (nimAddInt((*u_p0).rxHead, ((NI)1), &TM__WRV4qATsPXb7XfllB2fyCg_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*u_p0).rxHead = (NI)(((NI)(TM__WRV4qATsPXb7XfllB2fyCg_2)) % (((NI)4)));
			if (nimSubInt((*u_p0).rxCount, ((NI)1), &TM__WRV4qATsPXb7XfllB2fyCg_3)) { raiseOverflow(); goto BeforeRet_;
			};
			(*u_p0).rxCount = (NI)(TM__WRV4qATsPXb7XfllB2fyCg_3);
			recomputeInterrupt__mcf5407Zuart_u53(u_p0);
			colontmpD__3 = byte_1;
			result = colontmpD__3;
		}
		goto LA10_;
LA12_: ;
		{
			colontmpD__4 = ((NU8)0);
			result = colontmpD__4;
		}
LA10_: ;
	}
	break;
	case ((NU32)16):
	{
		result = ((NU8)14);
	}
	break;
	case ((NU32)20):
	{
		result = uisr__mcf5407Zuart_u49(u_p0);
	}
	break;
	case ((NU32)24):
	{
		result = (*u_p0).ubg1;
	}
	break;
	case ((NU32)28):
	{
		result = (*u_p0).ubg2;
	}
	break;
	case ((NU32)48):
	{
		result = (*u_p0).uivr;
	}
	break;
	case ((NU32)52):
	{
		result = ((NU8)255);
	}
	break;
	default:
	{
		result = ((NU8)0);
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initUart__mcf5407Zuart_u62)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NI interruptIndex_p1, tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p2) {
	(*u_p0).interruptIndex = interruptIndex_p1;
	(*u_p0).intc = intc_p2;
	(*u_p0).txCallback = NIM_NIL;
	(*u_p0).txUser = NIM_NIL;
	reset__mcf5407Zuart_u60(u_p0);
}
N_LIB_PRIVATE N_NIMCALL(void, command__mcf5407Zuart_u96)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU8 cmd_p1) {
	NU8 rc_1;
	NU8 txCmd_1;
	NU8 rxCmd_1;
	rc_1 = (NU8)((NU8)((NU8)(cmd_p1) >> (NU64)(((NI)4) & (8 - 1))) & ((NU8)7));
	switch (rc_1) {
	case ((NU8)1):
	{
		(*u_p0).modeUmr1 = NIM_TRUE;
	}
	break;
	case ((NU8)2):
	{
		(*u_p0).rxEnabled = NIM_FALSE;
		(*u_p0).rxCount = ((NI)0);
		(*u_p0).rxHead = ((NI)0);
	}
	break;
	case ((NU8)3):
	{
		(*u_p0).txEnabled = NIM_FALSE;
		(*u_p0).txHoldingValid = NIM_FALSE;
	}
	break;
	case ((NU8)4):
	{
	}
	break;
	case ((NU8)5):
	{
	}
	break;
	default:
	{
	}
	break;
	}
	txCmd_1 = (NU8)((NU8)((NU8)(cmd_p1) >> (NU64)(((NI)2) & (8 - 1))) & ((NU8)3));
	switch (txCmd_1) {
	case ((NU8)1):
	{
		(*u_p0).txEnabled = NIM_TRUE;
	}
	break;
	case ((NU8)2):
	{
		(*u_p0).txEnabled = NIM_FALSE;
	}
	break;
	default:
	{
	}
	break;
	}
	rxCmd_1 = (NU8)(cmd_p1 & ((NU8)3));
	switch (rxCmd_1) {
	case ((NU8)1):
	{
		(*u_p0).rxEnabled = NIM_TRUE;
	}
	break;
	case ((NU8)2):
	{
		(*u_p0).rxEnabled = NIM_FALSE;
	}
	break;
	default:
	{
	}
	break;
	}
	recomputeInterrupt__mcf5407Zuart_u53(u_p0);
}
N_LIB_PRIVATE N_NIMCALL(void, writeByte__mcf5407Zuart_u119)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU32 offset_p1, NU8 val_p2) {
	switch (offset_p1) {
	case ((NU32)0):
	{
		{
			if (!(*u_p0).modeUmr1) goto LA4_;
			(*u_p0).umr1 = val_p2;
			(*u_p0).modeUmr1 = NIM_FALSE;
		}
		goto LA2_;
LA4_: ;
		{
			(*u_p0).umr2 = val_p2;
		}
LA2_: ;
	}
	break;
	case ((NU32)4):
	{
		(*u_p0).ucsr = val_p2;
	}
	break;
	case ((NU32)8):
	{
		command__mcf5407Zuart_u96(u_p0, val_p2);
	}
	break;
	case ((NU32)12):
	{
		{
			if (!(*u_p0).txEnabled) goto LA12_;
			(*u_p0).txHolding = val_p2;
			(*u_p0).txHoldingValid = NIM_TRUE;
			{
				if (!!(((*u_p0).txCallback == 0))) goto LA16_;
				(*u_p0).txCallback((*u_p0).txUser, val_p2);
				(*u_p0).txHoldingValid = NIM_FALSE;
			}
LA16_: ;
			recomputeInterrupt__mcf5407Zuart_u53(u_p0);
		}
LA12_: ;
	}
	break;
	case ((NU32)16):
	{
		(*u_p0).uacr = val_p2;
	}
	break;
	case ((NU32)20):
	{
		(*u_p0).uimr = val_p2;
		recomputeInterrupt__mcf5407Zuart_u53(u_p0);
	}
	break;
	case ((NU32)24):
	{
		(*u_p0).ubg1 = val_p2;
	}
	break;
	case ((NU32)28):
	{
		(*u_p0).ubg2 = val_p2;
	}
	break;
	case ((NU32)48):
	{
		(*u_p0).uivr = val_p2;
		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = !(((*u_p0).intc == 0));
			if (!(T25_)) goto LA26_;
			T25_ = (*u_p0).interruptAsserted;
LA26_: ;
			if (!T25_) goto LA27_;
			setInternalVector__mcf5407Zintc_u222((*u_p0).intc, (*u_p0).interruptIndex, (*u_p0).uivr);
		}
LA27_: ;
	}
	break;
	case ((NU32)56):
	case ((NU32)60):
	{
	}
	break;
	default:
	{
	}
	break;
	}
}
