/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <io.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(unsigned int, tyProc__rXUriTjpoKqEo8PAmJmKqQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc__6fyjfWNeKFW9aeUK79c9c8S4g) (unsigned int codepage_p0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_CLOSURE_PTR(void, TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14) (void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17) (void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(void, addExitProc__stdZexitprocs_u172)(tyProc__HzVCwACFYM9cx9aV62PdjtuA cl_p0);
N_LIB_PRIVATE N_NIMCALL(void, restoreConsoleOutputCP__stdZsyncio_u587)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, restoreConsoleCP__stdZsyncio_u588)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5 = {8, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = {8, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6};
N_LIB_PRIVATE unsigned int consoleOutputCP__stdZsyncio_u585;
static void* TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2;
tyProc__rXUriTjpoKqEo8PAmJmKqQ Dl_553648710_;
N_LIB_PRIVATE unsigned int consoleCP__stdZsyncio_u586;
tyProc__rXUriTjpoKqEo8PAmJmKqQ Dl_553648711_;
tyProc__6fyjfWNeKFW9aeUK79c9c8S4g Dl_553648706_;
tyProc__6fyjfWNeKFW9aeUK79c9c8S4g Dl_553648708_;
N_LIB_PRIVATE N_NIMCALL(void, restoreConsoleOutputCP__stdZsyncio_u587)(void) {
	NI32 T1_;
	T1_ = (NI32)0;
	T1_ = Dl_553648706_(consoleOutputCP__stdZsyncio_u585);
	(void)(T1_);
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, restoreConsoleCP__stdZsyncio_u588)(void) {
	NI32 T1_;
	T1_ = (NI32)0;
	T1_ = Dl_553648708_(consoleCP__stdZsyncio_u586);
	(void)(T1_);
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void) {
{
	int T1_;
	int T2_;
	int T3_;
	T1_ = (int)0;
	T1_ = _fileno(stdin);
	_setmode(T1_, _O_BINARY);
	T2_ = (int)0;
	T2_ = _fileno(stdout);
	_setmode(T2_, _O_BINARY);
	T3_ = (int)0;
	T3_ = _fileno(stderr);
	_setmode(T3_, _O_BINARY);
	consoleOutputCP__stdZsyncio_u585 = Dl_553648710_();
	consoleCP__stdZsyncio_u586 = Dl_553648711_();
	{
		NI32 T8_;
		tyProc__HzVCwACFYM9cx9aV62PdjtuA T9_;
		if (!!((consoleOutputCP__stdZsyncio_u585 == ((NU32)65001)))) goto LA6_;
		T8_ = (NI32)0;
		T8_ = Dl_553648706_(((NU32)65001));
		(void)(T8_);
		nimZeroMem((void*)(&T9_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
		T9_.ClP_0 = ((TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14) (restoreConsoleOutputCP__stdZsyncio_u587)); T9_.ClE_0 = NIM_NIL;
		addExitProc__stdZexitprocs_u172(T9_);
	}
LA6_: ;
	{
		NI32 T14_;
		tyProc__HzVCwACFYM9cx9aV62PdjtuA T15_;
		if (!!((consoleCP__stdZsyncio_u586 == ((NU32)65001)))) goto LA12_;
		T14_ = (NI32)0;
		T14_ = Dl_553648708_(((NU32)65001));
		(void)(T14_);
		nimZeroMem((void*)(&T15_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
		T15_.ClP_0 = ((TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17) (restoreConsoleCP__stdZsyncio_u588)); T15_.ClE_0 = NIM_NIL;
		addExitProc__stdZexitprocs_u172(T15_);
	}
LA12_: ;
	nimTestErrorFlag();
}
}

N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_DatInit000)(void) {
if (!((TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2 = nimLoadLibrary(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5))
)) nimLoadLibraryError(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7);
	Dl_553648710_ = (tyProc__rXUriTjpoKqEo8PAmJmKqQ) nimGetProcAddr(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2, "GetConsoleOutputCP");
	Dl_553648711_ = (tyProc__rXUriTjpoKqEo8PAmJmKqQ) nimGetProcAddr(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2, "GetConsoleCP");
	Dl_553648706_ = (tyProc__6fyjfWNeKFW9aeUK79c9c8S4g) nimGetProcAddr(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2, "SetConsoleOutputCP");
	Dl_553648708_ = (tyProc__6fyjfWNeKFW9aeUK79c9c8S4g) nimGetProcAddr(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2, "SetConsoleCP");
}

