/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g;
typedef struct tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg;
typedef struct tyObject_BaseChunk__MfGUFd9avD6apZq4NquoFPQ tyObject_BaseChunk__MfGUFd9avD6apZq4NquoFPQ;
typedef struct tyObject_MemRegion__shMb9cZVR8qIRWk65wjaJLA tyObject_MemRegion__shMb9cZVR8qIRWk65wjaJLA;
struct tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g {
	tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* next;
	NI alignment;
};
struct tyObject_BaseChunk__MfGUFd9avD6apZq4NquoFPQ {
	NI prevSize;
	NI size;
	tyObject_MemRegion__shMb9cZVR8qIRWk65wjaJLA* owner;
};
struct tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg {
	tyObject_BaseChunk__MfGUFd9avD6apZq4NquoFPQ Sup;
	tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* next;
	tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* prev;
	NIM_ALIGN(16) NU8 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g*, atomicExchangeN__system_u6163)(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g** p_p0, tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* val_p1, int mem_p2) {
	tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* result;
	NI64 T1_;
	T1_ = (NI64)0;
	T1_ = _InterlockedExchange64(((void*) (p_p0)), ((NI64) (ptrdiff_t) (val_p1)));
	result = ((tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g*) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg*, atomicExchangeN__system_u6286)(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg** p_p0, tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* val_p1, int mem_p2) {
	tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* result;
	NI64 T1_;
	T1_ = (NI64)0;
	T1_ = _InterlockedExchange64(((void*) (p_p0)), ((NI64) (ptrdiff_t) (val_p1)));
	result = ((tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg*) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg*, atomicLoadN__system_u5948)(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg** p_p0) {
	tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* result;
	result = (*p_p0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atomicStoreN__system_u5954)(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg** p_p0, tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* val_p1) {
	(*p_p0) = val_p1;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atomicCompareExchangeN__system_u5960)(tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg** p_p0, tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg** expected_p1, tyObject_BigChunk__KpFaoXWO9b3p9cbfE5WxsAKg* desired_p2, NIM_BOOL weak_p3, int success_memmodel_p4, int failure_memmodel_p5) {
	NIM_BOOL result;
	NI64 T1_;
	T1_ = (NI64)0;
	T1_ = _InterlockedCompareExchange64(((void*) (p_p0)), ((NI64) (ptrdiff_t) (desired_p2)), ((NI64) (ptrdiff_t) ((*expected_p1))));
	result = (T1_ == ((NI64) (ptrdiff_t) ((*expected_p1))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atomicStoreN__system_u6014)(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g** p_p0, tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* val_p1) {
	(*p_p0) = val_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g*, atomicLoadN__system_u5992)(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g** p_p0) {
	tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* result;
	result = (*p_p0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atomicCompareExchangeN__system_u6020)(tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g** p_p0, tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g** expected_p1, tyObject_FreeCell__9bgFuYDj7Lr2UWxn2TCKG4g* desired_p2, NIM_BOOL weak_p3, int success_memmodel_p4, int failure_memmodel_p5) {
	NIM_BOOL result;
	NI64 T1_;
	T1_ = (NI64)0;
	T1_ = _InterlockedCompareExchange64(((void*) (p_p0)), ((NI64) (ptrdiff_t) (desired_p2)), ((NI64) (ptrdiff_t) ((*expected_p1))));
	result = (T1_ == ((NI64) (ptrdiff_t) ((*expected_p1))));
	return result;
}
