/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg {
	NI bytes;
	NI16* data;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
N_LIB_PRIVATE N_NIMCALL(NI16*, getEnvImpl__stdZenvvars_u11)(NCSTRING env_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u46)(tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg, newWideCString__stdZwidestrs_u310)(NCSTRING s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg a_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2693)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u382)(NI16* s_p0);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u46)(tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, getEnvImpl__stdZenvvars_u11)(NCSTRING env_p0) {
	NI16* result;
	tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg colontmpD_;
	NI16* r_1;
	wchar_t* T1_;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__Bn29c34hEoo8h9cZ0kltBm9cg));
	colontmpD_ = newWideCString__stdZwidestrs_u310(env_p0);
	r_1 = toWideCString__stdZwidestrs_u46(colontmpD_);
	T1_ = (wchar_t*)0;
	T1_ = _wgetenv(((wchar_t*) (r_1)));
	result = ((NI16*) (T1_));
	eqdestroy___stdZwidestrs_u7(colontmpD_);
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u31)(NimStringV2 key_p0, NimStringV2 default_p1) {
	NimStringV2 result;
	NI16* env_1;
	result.len = 0; result.p = NIM_NIL;
	env_1 = getEnvImpl__stdZenvvars_u11(nimToCStringConv(key_p0));
	{
		if (!(env_1 == ((NI16*) NIM_NIL))) goto LA3_;
		eqcopy___system_u2693((&result), default_p1);
	}
	goto LA1_;
LA3_: ;
	{
		result = dollar___stdZwidestrs_u382(env_1);
	}
LA1_: ;
	return result;
}
