/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <windows.h>
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__U1qxT9bTl0U8vVBWWx0loYA tySequence__U1qxT9bTl0U8vVBWWx0loYA;
typedef struct tySequence__U1qxT9bTl0U8vVBWWx0loYA_Content tySequence__U1qxT9bTl0U8vVBWWx0loYA_Content;
typedef struct tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA;
typedef struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__U1qxT9bTl0U8vVBWWx0loYA {
  NI len; tySequence__U1qxT9bTl0U8vVBWWx0loYA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef NU8 tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg;
typedef N_NOCONV_PTR(void, tyProc__vhjNbzH0Mvv2fTvoe1717Q) (void);
struct tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA {
	tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg kind;
union{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA fun1;
	tyProc__vhjNbzH0Mvv2fTvoe1717Q fun2;
};
};
struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw {
	NI rc;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_CLOSURE_PTR(void, TM__JXL39bfraktrl3ZkJ5EQGjw_11) (void);
struct tySequence__U1qxT9bTl0U8vVBWWx0loYA_Content { NI cap; tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0);
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0);
N_LIB_PRIVATE N_NOCONV(void, callClosures__stdZexitprocs_u19)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZexitprocs_u94)(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA* dest_p0, tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA src_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZexitprocs_u6)(tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZexitprocs_u91)(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__stdZexitprocs_u31)(tySequence__U1qxT9bTl0U8vVBWWx0loYA* s_p0, NI newlen_p1);
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZexitprocs_u178)(tySequence__U1qxT9bTl0U8vVBWWx0loYA* x_p0, tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdup___system_u4787)(tyProc__HzVCwACFYM9cx9aV62PdjtuA src_p0, tyProc__HzVCwACFYM9cx9aV62PdjtuA* Result);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_3 = { 60 | NIM_STRLIT_FLAG, "field \'fun1\' is not accessible for type \'Fun\' using \'kind = " };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_4 = {60, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_3};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_5 = { 8 | NIM_STRLIT_FLAG, "kClosure" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_6 = {8, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_5};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_7 = { 7 | NIM_STRLIT_FLAG, "kNoconv" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_8 = {7, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_7};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_9 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_10 = {0, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_9};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_12 = { 60 | NIM_STRLIT_FLAG, "field \'fun2\' is not accessible for type \'Fun\' using \'kind = " };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_13 = {60, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_12};
N_LIB_PRIVATE tySequence__U1qxT9bTl0U8vVBWWx0loYA gFuns__stdZexitprocs_u15;
N_LIB_PRIVATE CRITICAL_SECTION gFunsLock__stdZexitprocs_u14;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3415;
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0) {
	InitializeCriticalSection(lock_p0);
}
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0) {
	EnterCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	(*((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T2_))).rc, ((NI)8));
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T5_));
		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)3) & (64 - 1))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)8));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZexitprocs_u94)(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA* dest_p0, tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA src_p1) {
	tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA colontmp_;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA));
	colontmp_ = (*dest_p0);
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA));
	(*dest_p0).kind = src_p1.kind;
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
	{
		nimZeroMem((void*)(&(*dest_p0).fun1), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
		{
			if (!src_p1.fun1.ClE_0) goto LA4_;
			nimIncRef(src_p1.fun1.ClE_0);
		}
LA4_: ;
		{
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = nimDecRefIsLast((*dest_p0).fun1.ClE_0);
			if (!T8_) goto LA9_;
			nimDestroyAndDispose((*dest_p0).fun1.ClE_0);
		}
LA9_: ;
		(*dest_p0).fun1.ClE_0 = src_p1.fun1.ClE_0;
		(*dest_p0).fun1.ClP_0 = src_p1.fun1.ClP_0;
	}
	break;
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
	{
		(*dest_p0).fun2 = 0;
		(*dest_p0).fun2 = src_p1.fun2;
	}
	break;
	default: __assume(0);
	}
	switch (colontmp_.kind) {
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
	{
		{
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = nimDecRefIsLast(colontmp_.fun1.ClE_0);
			if (!T15_) goto LA16_;
			nimDestroyAndDispose(colontmp_.fun1.ClE_0);
		}
LA16_: ;
	}
	break;
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
	{
	}
	break;
	default: __assume(0);
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZexitprocs_u6)(tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_6;
	}
	break;
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_8;
	}
	break;
	default:
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_10;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZexitprocs_u91)(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
	{
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = nimDecRefIsLast((*dest_p0).fun1.ClE_0);
			if (!T4_) goto LA5_;
			nimDestroyAndDispose((*dest_p0).fun1.ClE_0);
		}
LA5_: ;
	}
	break;
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
	{
	}
	break;
	default: __assume(0);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___stdZexitprocs_u88)(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA* dest_p0) {
	(*dest_p0).kind = 0;
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
	{
		nimZeroMem((void*)(&(*dest_p0).fun1), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	}
	break;
	case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
	{
		(*dest_p0).fun2 = 0;
	}
	break;
	default: __assume(0);
	}
}
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0) {
	LeaveCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3415);
	return result;
}
N_LIB_PRIVATE N_NOCONV(void, callClosures__stdZexitprocs_u19)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	acquire__coreZlocks_u14((&gFunsLock__stdZexitprocs_u14));
	{
		NI i_1;
		NI colontmp_;
		NI T3_;
		NI TM__JXL39bfraktrl3ZkJ5EQGjw_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T3_ = gFuns__stdZexitprocs_u15.len;
		if (nimSubInt(T3_, ((NI)1), &TM__JXL39bfraktrl3ZkJ5EQGjw_2)) { raiseOverflow(); goto LA1_;
		};
		colontmp_ = (NI)(TM__JXL39bfraktrl3ZkJ5EQGjw_2);
		res_1 = colontmp_;
		{
			while (1) {
				tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA fun_1;
				NI TM__JXL39bfraktrl3ZkJ5EQGjw_14;
				if (!(((NI)0) <= res_1)) goto LA5;
				nimZeroMem((void*)(&fun_1), sizeof(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA));
				i_1 = ((NI) (res_1));
				if (i_1 < 0 || i_1 >= gFuns__stdZexitprocs_u15.len){ raiseIndexError2(i_1,gFuns__stdZexitprocs_u15.len-1); goto LA1_;
				}
				eqcopy___stdZexitprocs_u94((&fun_1), gFuns__stdZexitprocs_u15.p->data[i_1]);
				switch (fun_1.kind) {
				case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0):
				{
					if (!(((1 &((NU8)1<<((NU)((fun_1.kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__JXL39bfraktrl3ZkJ5EQGjw_4, dollar___stdZexitprocs_u6(fun_1.kind)); goto LA1_;
					}
					fun_1.fun1.ClE_0? fun_1.fun1.ClP_0(fun_1.fun1.ClE_0):((TM__JXL39bfraktrl3ZkJ5EQGjw_11)(fun_1.fun1.ClP_0))();
				}
				break;
				case ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)1):
				{
					if (!(((2 &((NU8)1<<((NU)((fun_1.kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__JXL39bfraktrl3ZkJ5EQGjw_13, dollar___stdZexitprocs_u6(fun_1.kind)); goto LA1_;
					}
					fun_1.fun2();
				}
				break;
				default: __assume(0);
				}
				if (nimSubInt(res_1, ((NI)1), &TM__JXL39bfraktrl3ZkJ5EQGjw_14)) { raiseOverflow(); goto LA1_;
				};
				res_1 = (NI)(TM__JXL39bfraktrl3ZkJ5EQGjw_14);
				eqdestroy___stdZexitprocs_u91((&fun_1));
			} LA5: ;
		}
	}
	setLen__stdZexitprocs_u31((&gFuns__stdZexitprocs_u15), ((NI)0));
	{
		LA1_:;
	}
	{
		release__coreZlocks_u16((&gFunsLock__stdZexitprocs_u14));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addExitProc__stdZexitprocs_u172)(tyProc__HzVCwACFYM9cx9aV62PdjtuA cl_p0) {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA colontmpD_;
	tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	acquire__coreZlocks_u14((&gFunsLock__stdZexitprocs_u14));
	{
		NI T4_;
		T4_ = gFuns__stdZexitprocs_u15.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		atexit(callClosures__stdZexitprocs_u19);
	}
LA5_: ;
	nimZeroMem((void*)(&T7_), sizeof(tyObject_Fun__AfTjFb80bAcTvCDLTzhWlA));
	T7_.kind = ((tyEnum_FunKind__Xjj1dpcjvgjuOl2QPVHzCg)0);
	eqdup___system_u4787(cl_p0, (&colontmpD_));
	T7_.fun1.ClE_0 = colontmpD_.ClE_0;
	T7_.fun1.ClP_0 = colontmpD_.ClP_0;
	add__stdZexitprocs_u178((&gFuns__stdZexitprocs_u15), T7_);
	{
		LA1_:;
	}
	{
		release__coreZlocks_u16((&gFunsLock__stdZexitprocs_u14));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void) {
{
	initLock__coreZlocks_u7((&gFunsLock__stdZexitprocs_u14));
	nimTestErrorFlag();
}
}

