/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NI8 tyArray__RGsHGOi9bnu5uBb7LyMV9aPg[8];
struct tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ {
	NI32 D1;
	NI16 D2;
	NI16 D3;
	tyArray__RGsHGOi9bnu5uBb7LyMV9aPg D4;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (int family_p0, void* paddr_p1, NCSTRING pStringBuffer_p2, NI32 stringBufSize_p3);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u57)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_2 = { 10 | NIM_STRLIT_FLAG, "Ws2_32.dll" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_3 = {10, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_2};
N_LIB_PRIVATE tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ WSAID_CONNECTEX__windowsZwinlean_u720 = {((NI32)631375801), ((NI16)-8717), ((NI16)18016), {((NI8)-114),
((NI8)-23),
((NI8)118),
((NI8)-27),
((NI8)-116),
((NI8)116),
((NI8)6),
((NI8)62)}
}
;
N_LIB_PRIVATE tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ WSAID_ACCEPTEX__windowsZwinlean_u721 = {((NI32)-1254720015), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyObject_GUID__5mTEykUqFugUX9aSEYd1G9bQ WSAID_GETACCEPTEXSOCKADDRS__windowsZwinlean_u722 = {((NI32)-1254720014), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyProc__zlYMfOxBV4VSYbrZMjd2xQ inet_ntop_real__windowsZwinlean_u793 = NIM_NIL;
N_LIB_PRIVATE void* ws2__windowsZwinlean_u794;
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void) {
{
	ws2__windowsZwinlean_u794 = loadLib__pureZdynlib_u3(TM__k6kyf4Co79a84IkK9blFuQVA_3, NIM_FALSE);
	{
		void* T5_;
		if (!!((ws2__windowsZwinlean_u794 == NIM_NIL))) goto LA3_;
		T5_ = (void*)0;
		T5_ = symAddr__pureZdynlib_u57(ws2__windowsZwinlean_u794, "inet_ntop");
		inet_ntop_real__windowsZwinlean_u793 = ((tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (T5_));
	}
LA3_: ;
	nimTestErrorFlag();
}
}

