/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ;
typedef struct tyTuple__by4HgyFfCXk326I9cE7T3dg tyTuple__by4HgyFfCXk326I9cE7T3dg;
typedef NI32 tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow;
typedef N_CDECL_PTR(NU32, tyProc__48NbZWzqN9c65MTL6aqhyoQ) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p3);
typedef N_CDECL_PTR(void, tyProc__Z520qbkX3ihqF4aEH1pYnQ) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__C9cb6BUv8oWgRdRLqOWt2Ow* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ {
	void* user;
	void* sim;
	void* cfgIsa;
	void* cfgVbrMask;
	tyProc__48NbZWzqN9c65MTL6aqhyoQ readFn;
	tyProc__Z520qbkX3ihqF4aEH1pYnQ writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
struct tyTuple__by4HgyFfCXk326I9cE7T3dg {
	NIM_BOOL Field0;
	NI Field1;
	NU8 Field2;
};
N_LIB_EXPORT N_CDECL(void, cf_set_irq)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int level_p1, NU8 vector_p2, int autovector_p3);
N_LIB_PRIVATE N_NIMCALL(tyTuple__by4HgyFfCXk326I9cE7T3dg, pendingInterrupt__coldfireZirq_u39)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NU8, vectorFor__coldfireZirq_u13)(NI level_p0, NU8 vector_p1, NIM_BOOL autovector_p2);
N_LIB_PRIVATE N_NIMCALL(NU8, autovectorFor__coldfireZexception_u70)(NI level_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NU32, srIpm__coldfireZirq_u6)(NU32 sr_p0);
N_LIB_PRIVATE N_NIMCALL(void, takeException__coldfireZmachine_u389)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU8 vector_p1, NU32 stackedPc_p2, NU32 fs_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static NIM_CONST tyTuple__by4HgyFfCXk326I9cE7T3dg TM__0xRZp3H9cHgeuOhm7vEmXCQ_2 = {NIM_FALSE,
((NI)0),
((NU8)0)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3456;
N_LIB_EXPORT N_CDECL(void, cf_set_irq)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int level_p1, NU8 vector_p2, int autovector_p3) {
{	{
		if (!(ctx_p0 == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (level_p1 == ((NI32)7));
		if (!(T7_)) goto LA8_;
		T7_ = !(((*ctx_p0).irqLevel == ((NI32)7)));
LA8_: ;
		if (!T7_) goto LA9_;
		(*ctx_p0).irq7Armed = NIM_TRUE;
		(*ctx_p0).irq7Vector = vector_p2;
		(*ctx_p0).irq7Autovector = !((autovector_p3 == ((NI32)0)));
	}
LA9_: ;
	(*ctx_p0).irqLevel = level_p1;
	(*ctx_p0).irqVector = vector_p2;
	(*ctx_p0).irqAutovector = !((autovector_p3 == ((NI32)0)));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, resetInterruptEdge__coldfireZirq_u26)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	int colontmpD_;
	int colontmpD__2;
	int level_1;
	NU8 vector_1;
	int autovector_1;
{	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	level_1 = (*ctx_p0).irqLevel;
	vector_1 = (*ctx_p0).irqVector;
	{
		if (!(*ctx_p0).irqAutovector) goto LA7_;
		colontmpD_ = ((int)1);
		autovector_1 = colontmpD_;
	}
	goto LA5_;
LA7_: ;
	{
		colontmpD__2 = ((int)0);
		autovector_1 = colontmpD__2;
	}
LA5_: ;
	(*ctx_p0).irq7Armed = 0;
	(*ctx_p0).irqLevel = ((int)0);
	cf_set_irq(ctx_p0, level_1, vector_1, autovector_1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU8, vectorFor__coldfireZirq_u13)(NI level_p0, NU8 vector_p1, NIM_BOOL autovector_p2) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
{	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!autovector_p2) goto LA3_;
		if ((level_p0) < ((NI)1) || (level_p0) > ((NI)7)){ raiseRangeErrorI(level_p0, ((NI)1), ((NI)7)); goto BeforeRet_;
		}
		colontmpD_ = autovectorFor__coldfireZexception_u70((level_p0));
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = vector_p1;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, srIpm__coldfireZirq_u6)(NU32 sr_p0) {
	NU32 result;
	result = (NU32)((NU32)((NU32)(sr_p0 & ((NU32)1792))) >> (NU64)(((NI)8) & (32 - 1)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__by4HgyFfCXk326I9cE7T3dg, pendingInterrupt__coldfireZirq_u39)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	tyTuple__by4HgyFfCXk326I9cE7T3dg result;
	NI level_1;
{	{
		NIM_BOOL colontmp_;
		NI colontmp__2;
		NU8 colontmp__3;
		if (!(*ctx_p0).irq7Armed) goto LA3_;
		colontmp_ = NIM_TRUE;
		colontmp__2 = ((NI)7);
		colontmp__3 = vectorFor__coldfireZirq_u13(((NI)7), (*ctx_p0).irq7Vector, (*ctx_p0).irq7Autovector);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		result.Field2 = colontmp__3;
		goto BeforeRet_;
	}
LA3_: ;
	level_1 = ((NI) ((*ctx_p0).irqLevel));
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NU32 T11_;
		NIM_BOOL colontmp__4;
		NI colontmp__5;
		NU8 colontmp__6;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T8_ = (((NI)1) <= level_1);
		if (!(T8_)) goto LA9_;
		T8_ = (level_1 <= ((NI)6));
LA9_: ;
		T7_ = T8_;
		if (!(T7_)) goto LA10_;
		T11_ = (NU32)0;
		T11_ = srIpm__coldfireZirq_u6((*ctx_p0).sr);
		T7_ = ((NU32)(T11_) < (NU32)(((NU32) (level_1))));
LA10_: ;
		if (!T7_) goto LA12_;
		colontmp__4 = NIM_TRUE;
		colontmp__5 = level_1;
		colontmp__6 = vectorFor__coldfireZirq_u13(level_1, (*ctx_p0).irqVector, (*ctx_p0).irqAutovector);
		result.Field0 = colontmp__4;
		result.Field1 = colontmp__5;
		result.Field2 = colontmp__6;
		goto BeforeRet_;
	}
LA12_: ;
	result = TM__0xRZp3H9cHgeuOhm7vEmXCQ_2;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3456);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, takeInterrupt__coldfireZirq_u64)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0) {
	NIM_BOOL result;
	tyTuple__by4HgyFfCXk326I9cE7T3dg pending_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	pending_1 = pendingInterrupt__coldfireZirq_u39(ctx_p0);
	{
		if (!!(pending_1.Field0)) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(pending_1.Field1 == ((NI)7))) goto LA7_;
		(*ctx_p0).irq7Armed = NIM_FALSE;
	}
LA7_: ;
	takeException__coldfireZmachine_u389(ctx_p0, pending_1.Field2, (*ctx_p0).pc, ((NU32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*ctx_p0).halted) goto LA11_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	(*ctx_p0).sr = (NU32)((NU32)((NU32)((*ctx_p0).sr & ((NU32)IL64(4294963199))) & ((NU32)IL64(4294965503))) | (NU32)((NU64)(((NU32) (pending_1.Field1))) << (NU64)(((NI)8) & (32 - 1))));
	{
		if (!!(((*ctx_p0).iackFn == 0))) goto LA15_;
		if ((pending_1.Field1) < ((int)(-2147483647 -1)) || (pending_1.Field1) > ((int)2147483647)){ raiseRangeErrorI(pending_1.Field1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		(*ctx_p0).iackFn((*ctx_p0).user, ((int) (pending_1.Field1)), pending_1.Field2);
	}
LA15_: ;
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
