/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NU8, autovectorFor__coldfireZexception_u70)(NI level_p0) {
	NU8 result;
	NI TM__EISBHqlRRr34gqvera8Y5w_2;
{	result = (NU8)0;
	if (nimAddInt(((NI)24), level_p0, &TM__EISBHqlRRr34gqvera8Y5w_2)) { raiseOverflow(); goto BeforeRet_;
	};
	result = ((NU8) ((NI)(TM__EISBHqlRRr34gqvera8Y5w_2)));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, frameFirstLongword__coldfireZexception_u6)(NU32 format_p0, NU32 fs_p1, NU8 vector_p2, NU32 sr_p3) {
	NU32 result;
	result = (NU32)((NU32)((NU32)((NU32)((NU32)((NU64)((NU32)(format_p0 & ((NU32)15))) << (NU64)(((NI)28) & (32 - 1))) | (NU32)((NU64)((NU32)((NU32)((NU32)(fs_p1) >> (NU64)(((NI)2) & (32 - 1))) & ((NU32)3))) << (NU64)(((NI)26) & (32 - 1)))) | (NU32)((NU64)(((NU32) (vector_p2))) << (NU64)(((NI)18) & (32 - 1)))) | (NU32)((NU64)((NU32)(fs_p1 & ((NU32)3))) << (NU64)(((NI)16) & (32 - 1)))) | (NU32)(sr_p3 & ((NU32)65535)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, vectorAddress__coldfireZexception_u89)(NU32 vbr_p0, NU8 vector_p1) {
	NU32 result;
	result = (NU32)((NU32)((NU32)(vbr_p0 & ((NU32)IL64(4293918720)))) + (NU32)((NU32)((NU32)(((NU32)4)) * (NU32)(((NU32) (vector_p1))))));
	return result;
}
