/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdatomic.h>
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA;
typedef struct tyObject_RuntimeLatch__FvwLkoo8lInKmmveZ6rFRQ tyObject_RuntimeLatch__FvwLkoo8lInKmmveZ6rFRQ;
typedef struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ;
typedef struct tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw;
typedef struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Fifo__ErSmCEoZDaGh9aY1bZdjjoQ tyObject_Fifo__ErSmCEoZDaGh9aY1bZdjjoQ;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg tySequence__aLjCOs9bu5l2rz6ENM6m6Sg;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__vrjNl4awzOmCciafmd8lLQ tySequence__vrjNl4awzOmCciafmd8lLQ;
typedef struct tySequence__vrjNl4awzOmCciafmd8lLQ_Content tySequence__vrjNl4awzOmCciafmd8lLQ_Content;
typedef struct tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg;
typedef struct tyTuple__dvA2kj9bKNi9abr3Htzo9afFw tyTuple__dvA2kj9bKNi9abr3Htzo9afFw;
typedef struct tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ;
typedef N_CDECL_PTR(void, tyProc__EMiXzHvwqlVf9ayQvmgDdgw) (void* user_p0, int asserted_p1);
typedef N_CDECL_PTR(void, tyProc__uu7v9a49cyeuzEN3J2FaWf1Q) (void* user_p0, int endpoint_p1, NU8* data_p2, size_t length_p3);
struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ {
	_Atomic NI64 value;
};
struct tyObject_RuntimeLatch__FvwLkoo8lInKmmveZ6rFRQ {
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ state;
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ reported;
};
typedef NU8 tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw;
struct tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA {
	tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw backend;
	NU16 frameNumber;
	tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* model;
};
struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw {
	NI rc;
};
typedef NU8 tyEnum_Transfer__3DcNCEKBEskcLgmN3rb9b9cA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyArray__dnD8kjh6rJ1Yy5jHvid0Ow[16];
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg {
  NI len; tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content* p;
};
struct tyObject_Fifo__ErSmCEoZDaGh9aY1bZdjjoQ {
	NI capacityBytes;
	NI bufferCount;
	tySequence__aLjCOs9bu5l2rz6ENM6m6Sg packets;
};
typedef tyObject_Fifo__ErSmCEoZDaGh9aY1bZdjjoQ tyArray__7FtwJO6QKwcORUsOvTpwuA[5];
typedef NIM_BOOL tyArray__T3VM4dxxwfhILe0asXG9c7A[5];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NIM_BOOL tyArray__3nI9aTuncP9aWL9a1JmrkLjBQ[16];
typedef NI tyArray__7OPiTiN9cF1exmTSlz4rAZg[16];
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw {
	void* user;
	tyProc__EMiXzHvwqlVf9ayQvmgDdgw irq;
	tyProc__uu7v9a49cyeuzEN3J2FaWf1Q tx;
	NI pending;
	tyEnum_Transfer__3DcNCEKBEskcLgmN3rb9b9cA transfer;
	NI width;
	NI index;
	NU32 latch;
	NimStringV2 absentNote;
	NU16 hwConfig;
	NU8 mode;
	NU8 deviceAddress;
	NU32 interruptEnable;
	NU32 interruptRegister;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow endpointConfig;
	NI selected;
	NIM_BOOL setupHeld;
	NIM_BOOL setupUnacknowledged;
	NIM_BOOL asserted;
	tyArray__7FtwJO6QKwcORUsOvTpwuA fifos;
	tyArray__T3VM4dxxwfhILe0asXG9c7A stalled;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ stage;
	NI stageFifo;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ readBuf;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ log;
	NI written;
	tyArray__3nI9aTuncP9aWL9a1JmrkLjBQ configWritten;
	tyArray__7OPiTiN9cF1exmTSlz4rAZg configOrdinal;
	tySequence__qwqHTkRvwhrRyENtudHQ7g logOrdinal;
	NI events;
};
typedef NU8 tyEnum_FileMode__Emd9bK9bdqM63yA9cTr3Vt9b5g;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__vrjNl4awzOmCciafmd8lLQ {
  NI len; tySequence__vrjNl4awzOmCciafmd8lLQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__vrjNl4awzOmCciafmd8lLQ trace;
	Exception* up;
};
struct tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg {
	Exception Sup;
};
typedef NU8 tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew;
struct tyTuple__dvA2kj9bKNi9abr3Htzo9afFw {
	tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew Field0;
	NI Field1;
	NI Field2;
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content { NI cap; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__vrjNl4awzOmCciafmd8lLQ_Content { NI cap; tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA*, isp1181_create)(void* user_p0, tyProc__EMiXzHvwqlVf9ayQvmgDdgw irq_p1, tyProc__uu7v9a49cyeuzEN3J2FaWf1Q tx_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runtimeAbandoned__mcf5407Zlatch_u51)(tyObject_RuntimeLatch__FvwLkoo8lInKmmveZ6rFRQ* latch_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u69)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u84)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zisp1181_u246)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___isp1181Zisp1181_u414)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw** dest_p0, tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw*, newISP1181__isp1181Zisp1181_u230)(void* user_p0, tyProc__EMiXzHvwqlVf9ayQvmgDdgw irq_p1, tyProc__uu7v9a49cyeuzEN3J2FaWf1Q tx_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zisp1181_u405)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_EXPORT N_CDECL(void, isp1181_destroy)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeTeardownReport__isp1181Zstub_u111)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u391)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__Emd9bK9bdqM63yA9cTr3Vt9b5g mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u231)(FILE* f_p0, NimStringV2 s_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, reportText__isp1181Zreport_u11)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3027)(Exception** dest_p0, Exception* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u119)(tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg* dest_p0);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u245)(FILE* f_p0);
N_LIB_EXPORT N_CDECL(NU8, isp1181_read)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 address_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, portRead__isp1181Zisp1181_u1250)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NU32 address_p1);
N_LIB_EXPORT N_CDECL(void, isp1181_write)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 address_p1, NU8 value_p2);
N_LIB_PRIVATE N_NIMCALL(void, portWrite__isp1181Zisp1181_u1243)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NU32 address_p1, NU8 value_p2);
N_LIB_EXPORT N_CDECL(int, isp1181_rx)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int endpoint_p1, NU8* data_p2, size_t length_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, deliver__isp1181Zisp1181_u620)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI endpoint_p1, NU8* data_p2, NI data_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(int, isp1181_setup)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU8* data_p1, size_t length_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, deliverSetup__isp1181Zisp1181_u649)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NU8* data_p1, NI data_p1Len_0);
N_LIB_EXPORT N_CDECL(int, isp1181_in_token)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int endpoint_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, transmit__isp1181Zisp1181_u688)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI endpoint_p1);
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_written)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NI, logWritten__isp1181Zisp1181_u471)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0);
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_retained)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NI, logRetained__isp1181Zisp1181_u477)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0);
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_line)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t index_p1, char* dst_p2, size_t capacity_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, logLine__isp1181Zisp1181_u486)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI index_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_EXPORT N_CDECL(size_t, isp1181_config_slots)(void);
N_LIB_EXPORT N_CDECL(int, isp1181_config_slot)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t slot_p1, NU8* value_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, configSlotWritten__isp1181Zisp1181_u506)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI slot_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, configSlotValue__isp1181Zisp1181_u513)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI slot_p1);
N_LIB_EXPORT N_CDECL(int, isp1181_slot_buffer)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t slot_p1, size_t* max_packet_bytes_p2, size_t* buffer_count_p3);
N_LIB_PRIVATE N_NIMCALL(tyTuple__dvA2kj9bKNi9abr3Htzo9afFw, slotBufferGeometry__isp1181Zisp1181_u541)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0, NI slot_p1);
N_LIB_EXPORT N_CDECL(size_t, isp1181_report)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, char* dst_p1, size_t capacity_p2);
N_LIB_EXPORT N_CDECL(int, isp1181_set_backend)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int backend_p1);
N_LIB_PRIVATE N_NIMCALL(void, setBackend__isp1181Zstub_u40)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw value_p1);
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__FkASmaITY2HNgFUq3lkV7g_2 = { 22 | NIM_STRLIT_FLAG, "MCF5407_ISP1181_REPORT" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_3 = {22, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__FkASmaITY2HNgFUq3lkV7g_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_5 = {0, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_4};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__FkASmaITY2HNgFUq3lkV7g_6 = { 39 | NIM_STRLIT_FLAG, "isp1181: MCF5407_ISP1181_REPORT names \"" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_7 = {39, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_6};
static const struct {
  NI cap; NIM_CHAR data[63+1];
} TM__FkASmaITY2HNgFUq3lkV7g_8 = { 63 | NIM_STRLIT_FLAG, "\" and it could not be opened for append; no report was written\012" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_9 = {63, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_8};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__FkASmaITY2HNgFUq3lkV7g_10 = { 45 | NIM_STRLIT_FLAG, "isp1181: the report could not be written to \"" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_11 = {45, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_10};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__FkASmaITY2HNgFUq3lkV7g_12 = { 3 | NIM_STRLIT_FLAG, "\": " };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_13 = {3, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__FkASmaITY2HNgFUq3lkV7g_14 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__FkASmaITY2HNgFUq3lkV7g_15 = {1, (NimStrPayload*)&TM__FkASmaITY2HNgFUq3lkV7g_14};
extern tyObject_RuntimeLatch__FvwLkoo8lInKmmveZ6rFRQ runtimeLatch__mcf5407Zlatch_u49;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3456;
extern NIM_THREADVAR Exception* currException__system_u2997;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T5_));
		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)3) & (64 - 1))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)8));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u84)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).model);
		if (!T3_) goto LA4_;
		eqdestroy___isp1181Zisp1181_u246((&(*(*dest_p0).model)));
		nimRawDispose((*dest_p0).model, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___isp1181Zstub_u69)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___isp1181Zstub_u84((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3456);
	return result;
}
N_LIB_EXPORT N_CDECL(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA*, isp1181_create)(void* user_p0, tyProc__EMiXzHvwqlVf9ayQvmgDdgw irq_p1, tyProc__uu7v9a49cyeuzEN3J2FaWf1Q tx_p2) {
	tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* result;
	tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = runtimeAbandoned__mcf5407Zlatch_u51((&runtimeLatch__mcf5407Zlatch_u49));
		if (!T3_) goto LA4_;
		result = ((tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA*) NIM_NIL);
		goto BeforeRet_;
	}
LA4_: ;
	eqdestroy___isp1181Zstub_u69(result);
	result = (tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA*) nimNewObj(sizeof(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA), NIM_ALIGNOF(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA));
	(*result).backend = ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0);
	(*result).frameNumber = ((NU16)0);
	T6_ = NIM_NIL;
	T6_ = newISP1181__isp1181Zisp1181_u230(user_p0, irq_p1, tx_p2);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___isp1181Zisp1181_u405(T6_); goto BeforeRet_;}
	eqsink___isp1181Zisp1181_u414(&(*result).model, T6_);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u2997;
	return result;
}
static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	eqcopy___system_u3027(&result, currException__system_u2997);
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3027(&currException__system_u2997, (*currException__system_u2997).up);
}
N_LIB_PRIVATE N_NIMCALL(void, writeTeardownReport__isp1181Zstub_u111)(tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw* m_p0) {
	NimStringV2 destination_1;
	FILE* handle_1;
	NimStringV2 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	destination_1.len = 0; destination_1.p = NIM_NIL;
	destination_1 = getEnv__stdZenvvars_u15(TM__FkASmaITY2HNgFUq3lkV7g_3, TM__FkASmaITY2HNgFUq3lkV7g_5);
	{
		if (!(destination_1.len == ((NI)0))) goto LA4_;
		if (destination_1.p && !(destination_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(destination_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	handle_1 = (FILE*)0;
	{
		NIM_BOOL T8_;
		NimStringV2 colontmpD_;
		NimStringV2 T12_;
		T8_ = (NIM_BOOL)0;
		T8_ = open__stdZsyncio_u391(&handle_1, destination_1, ((tyEnum_FileMode__Emd9bK9bdqM63yA9cTr3Vt9b5g)4), ((NI)-1));
		if (!!(T8_)) goto LA9_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T12_.len = 0; T12_.p = NIM_NIL;
		T12_ = rawNewString(destination_1.len + 102);
appendString((&T12_), TM__FkASmaITY2HNgFUq3lkV7g_7);
appendString((&T12_), destination_1);
appendString((&T12_), TM__FkASmaITY2HNgFUq3lkV7g_9);
		colontmpD_ = T12_;
		write__stdZsyncio_u231(stderr, colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (destination_1.p && !(destination_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(destination_1.p);
}
		goto BeforeRet_;
		{
			LA11_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA9_: ;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__2 = reportText__isp1181Zreport_u11(m_p0);
	write__stdZsyncio_u231(handle_1, colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
	{
		LA16_:;
	}
	{
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA15_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 3025789184)) {
			tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg* err_1;
			NimStringV2 colontmpD__3;
			Exception* T23_;
			NimStringV2 T24_;
			*nimErr_ = NIM_FALSE;
			err_1 = NIM_NIL;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			T23_ = NIM_NIL;
			T23_ = getCurrentException();
			err_1 = ((tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg*) (T23_));
			T24_.len = 0; T24_.p = NIM_NIL;
			T24_ = rawNewString(destination_1.len + (*err_1).Sup.message.len + 49);
appendString((&T24_), TM__FkASmaITY2HNgFUq3lkV7g_11);
appendString((&T24_), destination_1);
appendString((&T24_), TM__FkASmaITY2HNgFUq3lkV7g_13);
appendString((&T24_), (*err_1).Sup.message);
appendString((&T24_), TM__FkASmaITY2HNgFUq3lkV7g_15);
			colontmpD__3 = T24_;
			write__stdZsyncio_u231(stderr, colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
			{
				LA22_:;
			}
			{
				if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				eqdestroy___isp1181Zstub_u119(err_1);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA20_;
			popCurrentException();
			LA20_:;
		}
	}
	{
		close__stdZsyncio_u245(handle_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (destination_1.p && !(destination_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(destination_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(void, isp1181_destroy)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!!(((*ctx_p0).model == 0))) goto LA7_;
		writeTeardownReport__isp1181Zstub_u111((*ctx_p0).model);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		eqsink___isp1181Zisp1181_u414(&(*ctx_p0).model, ((tyObject_ISP1181colonObjectType___5sw8uL9czt48bYW1D2uCpzw*) NIM_NIL));
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(NU8, isp1181_read)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 address_p1) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
{	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		result = ((NU8)0);
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
		colontmpD_ = ((NU8)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		colontmpD__2 = portRead__isp1181Zisp1181_u1250((*ctx_p0).model, address_p1);
		result = colontmpD__2;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, isp1181_write)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU32 address_p1, NU8 value_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		portWrite__isp1181Zisp1181_u1243((*ctx_p0).model, address_p1, value_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(int, isp1181_rx)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int endpoint_p1, NU8* data_p2, size_t length_p3) {
	int result;
	int colontmpD_;
	int colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
		colontmpD_ = ((int)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		int colontmpD__3;
		int colontmpD__4;
		int colontmpD__5;
		colontmpD__3 = (int)0;
		colontmpD__4 = (int)0;
		colontmpD__5 = (int)0;
		{
			NIM_BOOL T10_;
			T10_ = (NIM_BOOL)0;
			T10_ = (data_p2 == 0);
			if (T10_) goto LA11_;
			T10_ = (length_p3 == ((NU)0));
LA11_: ;
			if (!T10_) goto LA12_;
			colontmpD__3 = ((int)0);
			colontmpD__2 = colontmpD__3;
		}
		goto LA8_;
LA12_: ;
		{
			NI TM__FkASmaITY2HNgFUq3lkV7g_16;
			NIM_BOOL T15_;
			if (length_p3 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto LA7_;
			}
			if (nimSubInt(((NI) (length_p3)), ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_16)) { raiseOverflow(); goto LA7_;
			};
			T15_ = (NIM_BOOL)0;
			T15_ = deliver__isp1181Zisp1181_u620((*ctx_p0).model, ((NI) (endpoint_p1)), (NU8*)(((NU8*) (data_p2)))+(((NI)0)), ((NI)(TM__FkASmaITY2HNgFUq3lkV7g_16))-(((NI)0))+1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
			if (!T15_) goto LA16_;
			colontmpD__4 = ((int)1);
			colontmpD__2 = colontmpD__4;
		}
		goto LA8_;
LA16_: ;
		{
			colontmpD__5 = ((int)0);
			colontmpD__2 = colontmpD__5;
		}
LA8_: ;
		result = colontmpD__2;
		{
			LA7_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, isp1181_setup)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NU8* data_p1, size_t length_p2) {
	int result;
	int colontmpD_;
	int colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
		colontmpD_ = ((int)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		int colontmpD__3;
		int colontmpD__4;
		int colontmpD__5;
		colontmpD__3 = (int)0;
		colontmpD__4 = (int)0;
		colontmpD__5 = (int)0;
		{
			NIM_BOOL T10_;
			T10_ = (NIM_BOOL)0;
			T10_ = (data_p1 == 0);
			if (T10_) goto LA11_;
			T10_ = (length_p2 == ((NU)0));
LA11_: ;
			if (!T10_) goto LA12_;
			colontmpD__3 = ((int)0);
			colontmpD__2 = colontmpD__3;
		}
		goto LA8_;
LA12_: ;
		{
			NI TM__FkASmaITY2HNgFUq3lkV7g_17;
			NIM_BOOL T15_;
			if (length_p2 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto LA7_;
			}
			if (nimSubInt(((NI) (length_p2)), ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_17)) { raiseOverflow(); goto LA7_;
			};
			T15_ = (NIM_BOOL)0;
			T15_ = deliverSetup__isp1181Zisp1181_u649((*ctx_p0).model, (NU8*)(((NU8*) (data_p1)))+(((NI)0)), ((NI)(TM__FkASmaITY2HNgFUq3lkV7g_17))-(((NI)0))+1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
			if (!T15_) goto LA16_;
			colontmpD__4 = ((int)1);
			colontmpD__2 = colontmpD__4;
		}
		goto LA8_;
LA16_: ;
		{
			colontmpD__5 = ((int)0);
			colontmpD__2 = colontmpD__5;
		}
LA8_: ;
		result = colontmpD__2;
		{
			LA7_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, isp1181_in_token)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int endpoint_p1) {
	int result;
	int colontmpD_;
	int colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*ctx_p0).backend) {
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0):
	{
		colontmpD_ = ((int)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1):
	{
		int colontmpD__3;
		int colontmpD__4;
		colontmpD__3 = (int)0;
		colontmpD__4 = (int)0;
		{
			NIM_BOOL T10_;
			T10_ = (NIM_BOOL)0;
			T10_ = transmit__isp1181Zisp1181_u688((*ctx_p0).model, ((NI) (endpoint_p1)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
			if (!T10_) goto LA11_;
			colontmpD__3 = ((int)1);
			colontmpD__2 = colontmpD__3;
		}
		goto LA8_;
LA11_: ;
		{
			colontmpD__4 = ((int)0);
			colontmpD__2 = colontmpD__4;
		}
LA8_: ;
		result = colontmpD__2;
		{
			LA7_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_written)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0) {
	size_t result;
	NI T7_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = ((*ctx_p0).model == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((size_t)0);
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = (NI)0;
	T7_ = logWritten__isp1181Zisp1181_u471((*ctx_p0).model);
	result = ((size_t) (T7_));
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_retained)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0) {
	size_t result;
	NI T7_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = ((*ctx_p0).model == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((size_t)0);
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = (NI)0;
	T7_ = logRetained__isp1181Zisp1181_u477((*ctx_p0).model);
	result = ((size_t) (T7_));
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(size_t, isp1181_log_line)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t index_p1, char* dst_p2, size_t capacity_p3) {
	size_t result;
	NimStringV2 line_1;
	NI TM__FkASmaITY2HNgFUq3lkV7g_19;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (size_t)0;
	line_1.len = 0; line_1.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = ((*ctx_p0).model == 0);
LA5_: ;
		if (!T4_) goto LA6_;
		result = ((size_t)0);
		if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
		goto BeforeRet_;
	}
LA6_: ;
	if (index_p1 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto LA1_;
	}
	line_1 = logLine__isp1181Zisp1181_u486((*ctx_p0).model, ((NI) (index_p1)));
	{
		if (!(line_1.len == ((NI)0))) goto LA10_;
		result = ((size_t)0);
		if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
		goto BeforeRet_;
	}
LA10_: ;
	{
		NIM_BOOL T14_;
		NI room_1;
		NI TM__FkASmaITY2HNgFUq3lkV7g_18;
		T14_ = (NIM_BOOL)0;
		T14_ = !((dst_p2 == 0));
		if (!(T14_)) goto LA15_;
		T14_ = ((NU64)(((NU)0)) < (NU64)(capacity_p3));
LA15_: ;
		if (!T14_) goto LA16_;
		if (capacity_p3 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto LA1_;
		}
		if (nimSubInt(((NI) (capacity_p3)), ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_18)) { raiseOverflow(); goto LA1_;
		};
		room_1 = ((line_1.len <= (NI)(TM__FkASmaITY2HNgFUq3lkV7g_18)) ? line_1.len : (NI)(TM__FkASmaITY2HNgFUq3lkV7g_18));
		{
			if (!(((NI)0) < room_1)) goto LA20_;
			if (((NI)0) < 0 || ((NI)0) >= line_1.len){ raiseIndexError2(((NI)0),line_1.len-1); goto LA1_;
			}
			if ((room_1) < ((NI)0) || (room_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(room_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
			}
			copyMem__system_u1755(((void*) (dst_p2)), ((void*) ((&line_1.p->data[((NI)0)]))), (room_1));
		}
LA20_: ;
		((char*) (dst_p2))[room_1] = 0;
	}
LA16_: ;
	if (nimAddInt(line_1.len, ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_19)) { raiseOverflow(); goto LA1_;
	};
	result = ((size_t) ((NI)(TM__FkASmaITY2HNgFUq3lkV7g_19)));
	{
		LA1_:;
	}
	{
		if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(size_t, isp1181_config_slots)(void) {
	size_t result;
	result = ((size_t)16);
	return result;
}
N_LIB_EXPORT N_CDECL(int, isp1181_config_slot)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t slot_p1, NU8* value_p2) {
	int result;
{	result = (int)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = ((*ctx_p0).model == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((int)-1);
		goto BeforeRet_;
	}
LA5_: ;
	{
		if (!((NU64)(((size_t)16)) <= (NU64)(slot_p1))) goto LA9_;
		result = ((int)-1);
		goto BeforeRet_;
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		if (slot_p1 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
		}
		T13_ = (NIM_BOOL)0;
		T13_ = configSlotWritten__isp1181Zisp1181_u506((*ctx_p0).model, ((NI) (slot_p1)));
		if (!!(T13_)) goto LA14_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA14_: ;
	{
		if (!!((value_p2 == 0))) goto LA18_;
		if (slot_p1 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
		}
		(*value_p2) = configSlotValue__isp1181Zisp1181_u513((*ctx_p0).model, ((NI) (slot_p1)));
	}
LA18_: ;
	result = ((int)1);
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, isp1181_slot_buffer)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, size_t slot_p1, size_t* max_packet_bytes_p2, size_t* buffer_count_p3) {
	int result;
	int colontmpD_;
	tyTuple__dvA2kj9bKNi9abr3Htzo9afFw shape_1;
{	result = (int)0;
	colontmpD_ = (int)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = ((*ctx_p0).model == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((int)-1);
		goto BeforeRet_;
	}
LA5_: ;
	{
		if (!((NU64)(((size_t)16)) <= (NU64)(slot_p1))) goto LA9_;
		result = ((int)-1);
		goto BeforeRet_;
	}
LA9_: ;
	if (slot_p1 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
	}
	shape_1 = slotBufferGeometry__isp1181Zisp1181_u541((*ctx_p0).model, ((NI) (slot_p1)));
	switch (shape_1.Field0) {
	case ((tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew)0):
	case ((tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew)2):
	{
		result = ((int)-1);
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew)1):
	{
		result = ((int)0);
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_SlotGeometryKind__fKXZiqHCcaaVQqsimlmLew)3):
	{
		{
			if (!!((max_packet_bytes_p2 == 0))) goto LA16_;
			(*max_packet_bytes_p2) = ((size_t) (shape_1.Field1));
		}
LA16_: ;
		{
			if (!!((buffer_count_p3 == 0))) goto LA20_;
			(*buffer_count_p3) = ((size_t) (shape_1.Field2));
		}
LA20_: ;
		colontmpD_ = ((int)1);
		result = colontmpD_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(size_t, isp1181_report)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, char* dst_p1, size_t capacity_p2) {
	size_t result;
	NimStringV2 text_1;
	NI TM__FkASmaITY2HNgFUq3lkV7g_21;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (size_t)0;
	text_1.len = 0; text_1.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = ((*ctx_p0).model == 0);
LA5_: ;
		if (!T4_) goto LA6_;
		result = ((size_t)0);
		if (text_1.p && !(text_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(text_1.p);
}
		goto BeforeRet_;
	}
LA6_: ;
	text_1 = reportText__isp1181Zreport_u11((*ctx_p0).model);
	{
		NIM_BOOL T10_;
		NI room_1;
		NI TM__FkASmaITY2HNgFUq3lkV7g_20;
		T10_ = (NIM_BOOL)0;
		T10_ = !((dst_p1 == 0));
		if (!(T10_)) goto LA11_;
		T10_ = ((NU64)(((NU)0)) < (NU64)(capacity_p2));
LA11_: ;
		if (!T10_) goto LA12_;
		if (capacity_p2 > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto LA1_;
		}
		if (nimSubInt(((NI) (capacity_p2)), ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_20)) { raiseOverflow(); goto LA1_;
		};
		room_1 = ((text_1.len <= (NI)(TM__FkASmaITY2HNgFUq3lkV7g_20)) ? text_1.len : (NI)(TM__FkASmaITY2HNgFUq3lkV7g_20));
		{
			if (!(((NI)0) < room_1)) goto LA16_;
			if (((NI)0) < 0 || ((NI)0) >= text_1.len){ raiseIndexError2(((NI)0),text_1.len-1); goto LA1_;
			}
			if ((room_1) < ((NI)0) || (room_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(room_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
			}
			copyMem__system_u1755(((void*) (dst_p1)), ((void*) ((&text_1.p->data[((NI)0)]))), (room_1));
		}
LA16_: ;
		((char*) (dst_p1))[room_1] = 0;
	}
LA12_: ;
	if (nimAddInt(text_1.len, ((NI)1), &TM__FkASmaITY2HNgFUq3lkV7g_21)) { raiseOverflow(); goto LA1_;
	};
	result = ((size_t) ((NI)(TM__FkASmaITY2HNgFUq3lkV7g_21)));
	{
		LA1_:;
	}
	{
		if (text_1.p && !(text_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(text_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setBackend__isp1181Zstub_u40)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw value_p1) {
{	{
		if (!(ctx_p0 == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	(*ctx_p0).backend = value_p1;
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(int, isp1181_set_backend)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, int backend_p1) {
	int result;
	int colontmpD_;
	int colontmpD__2;
	int colontmpD__3;
{	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	colontmpD__3 = (int)0;
	{
		if (!(ctx_p0 == 0)) goto LA3_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA3_: ;
	switch (backend_p1) {
	case ((NI32)0):
	{
		setBackend__isp1181Zstub_u40(ctx_p0, ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)0));
		colontmpD_ = ((int)1);
		result = colontmpD_;
	}
	break;
	case ((NI32)1):
	{
		setBackend__isp1181Zstub_u40(ctx_p0, ((tyEnum_ISP1181Backend__xB3kJzW8XK06eHYo1LoCrw)1));
		colontmpD__2 = ((int)1);
		result = colontmpD__2;
	}
	break;
	default:
	{
		colontmpD__3 = ((int)0);
		result = colontmpD__3;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, advanceFrames__isp1181Zstub_u52)(tyObject_ISP1181CtxcolonObjectType___FSFNH9c1AhQ9bz9cJi5l2suTA* ctx_p0, NI frames_p1) {
	NI TM__FkASmaITY2HNgFUq3lkV7g_22;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = (frames_p1 <= ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	if (nimAddInt(((NI) ((*ctx_p0).frameNumber)), frames_p1, &TM__FkASmaITY2HNgFUq3lkV7g_22)) { raiseOverflow(); goto BeforeRet_;
	};
	(*ctx_p0).frameNumber = ((NU16) ((NI)(((NI)(TM__FkASmaITY2HNgFUq3lkV7g_22)) % (((NI)2048)))));
	}BeforeRet_: ;
}
