/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdatomic.h>
#include <stdio.h>
#include <time.h>
#include <string.h>
#include <sched.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw;
typedef struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ;
struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ {
	_Atomic NI64 value;
};
struct tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw {
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ state;
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ reported;
};
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
static N_INLINE(NI, load__mcf5407Zlatch_u60)(tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ* location_p0, memory_order order_p1);
N_LIB_PRIVATE N_NIMCALL(void, reportStall__mcf5407Zlatch_u99)(tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw* latch_p0);
static N_INLINE(NIM_BOOL, compareExchange__mcf5407Zlatch_u114)(tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ* location_p0, NI* expected_p1, NI desired_p2, memory_order success_p3, memory_order failure_p4);
N_LIB_PRIVATE N_NIMCALL(NI64, monotonicMillis__mcf5407Zlatch_u10)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw runtimeLatch__mcf5407Zlatch_u49;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL initializing__mcf5407Zlatch_u50;
static N_INLINE(NI, load__mcf5407Zlatch_u60)(tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ* location_p0, memory_order order_p1) {
	NI result;
	NI64 T1_;
	T1_ = (NI64)0;
	T1_ = atomic_load_explicit((&(*location_p0).value), order_p1);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runtimeAbandoned__mcf5407Zlatch_u51)(tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw* latch_p0) {
	NIM_BOOL result;
	NI T1_;
	T1_ = (NI)0;
	T1_ = load__mcf5407Zlatch_u60((&(*latch_p0).state), ((memory_order)2));
	result = (T1_ == ((NI)3));
	return result;
}
static N_INLINE(NIM_BOOL, compareExchange__mcf5407Zlatch_u114)(tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ* location_p0, NI* expected_p1, NI desired_p2, memory_order success_p3, memory_order failure_p4) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = atomic_compare_exchange_strong_explicit((&(*location_p0).value), ((NI64*) (expected_p1)), ((NI64) (desired_p2)), success_p3, failure_p4);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, reportStall__mcf5407Zlatch_u99)(tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw* latch_p0) {
	NI expected_1;
	int T6_;
	int T7_;
	int T8_;
	int T9_;
	int T10_;
	int T11_;
{	expected_1 = ((NI)0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = compareExchange__mcf5407Zlatch_u114((&(*latch_p0).reported), (&expected_1), ((NI)1), ((memory_order)4), ((memory_order)2));
		if (!!(T3_)) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (int)0;
	T6_ = fputs("mcf5407_runtime_init: the Nim runtime initializer did not finish.\012", stderr);
	(void)(T6_);
	T7_ = (int)0;
	T7_ = fputs("Another thread claimed the one-time latch and did not release it.\012", stderr);
	(void)(T7_);
	T8_ = (int)0;
	T8_ = fputs("One known cause: module initialization waits for a thread.\012", stderr);
	(void)(T8_);
	T9_ = (int)0;
	T9_ = fputs("That thread then calls mcf5407_runtime_init itself.\012", stderr);
	(void)(T9_);
	T10_ = (int)0;
	T10_ = fputs("The runtime is not initialized, so this library will create no context.\012", stderr);
	(void)(T10_);
	T11_ = (int)0;
	T11_ = fputs("mcf5407_runtime_init reports 0 to this caller and to every later one.\012", stderr);
	(void)(T11_);
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI64, monotonicMillis__mcf5407Zlatch_u10)(void) {
	NI64 result;
	struct timespec now_1;
	int T1_;
	NI64 TM__xI5ihxDxL9a9cFUc1uij5EWg_2;
	NI64 TM__xI5ihxDxL9a9cFUc1uij5EWg_3;
{	result = (NI64)0;
	nimZeroMem((void*)(&now_1), sizeof(struct timespec));
	T1_ = (int)0;
	T1_ = clock_gettime(CLOCK_MONOTONIC, (&now_1));
	(void)(T1_);
	if (nimMulInt64(((NI64) (now_1.tv_sec)), IL64(1000), &TM__xI5ihxDxL9a9cFUc1uij5EWg_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__xI5ihxDxL9a9cFUc1uij5EWg_2), (NI64)((((NI64) (now_1.tv_nsec))) / (IL64(1000000))), &TM__xI5ihxDxL9a9cFUc1uij5EWg_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI64)(TM__xI5ihxDxL9a9cFUc1uij5EWg_3);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runtimeInitOnce__mcf5407Zlatch_u172)(tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw* latch_p0, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ initializer_p1, NI64 waitMillis_p2) {
	NIM_BOOL result;
	NI entryState_1;
	NI expected_1;
	NI64 deadline_1;
	NI64 T23_;
	NI64 TM__xI5ihxDxL9a9cFUc1uij5EWg_4;
{	result = (NIM_BOOL)0;
	entryState_1 = load__mcf5407Zlatch_u60((&(*latch_p0).state), ((memory_order)2));
	{
		if (!(entryState_1 == ((NI)2))) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(entryState_1 == ((NI)3))) goto LA7_;
		reportStall__mcf5407Zlatch_u99(latch_p0);
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA7_: ;
	{
		if (!initializing__mcf5407Zlatch_u50) goto LA11_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	expected_1 = ((NI)0);
	{
		NIM_BOOL T15_;
		NI running_1;
		T15_ = (NIM_BOOL)0;
		T15_ = compareExchange__mcf5407Zlatch_u114((&(*latch_p0).state), (&expected_1), ((NI)1), ((memory_order)4), ((memory_order)2));
		if (!T15_) goto LA16_;
		initializing__mcf5407Zlatch_u50 = NIM_TRUE;
		initializer_p1();
		initializing__mcf5407Zlatch_u50 = NIM_FALSE;
		running_1 = ((NI)1);
		{
			NIM_BOOL T20_;
			T20_ = (NIM_BOOL)0;
			T20_ = compareExchange__mcf5407Zlatch_u114((&(*latch_p0).state), (&running_1), ((NI)2), ((memory_order)4), ((memory_order)2));
			if (!T20_) goto LA21_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA21_: ;
		reportStall__mcf5407Zlatch_u99(latch_p0);
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA16_: ;
	T23_ = (NI64)0;
	T23_ = monotonicMillis__mcf5407Zlatch_u10();
	if (nimAddInt64(T23_, waitMillis_p2, &TM__xI5ihxDxL9a9cFUc1uij5EWg_4)) { raiseOverflow(); goto BeforeRet_;
	};
	deadline_1 = (NI64)(TM__xI5ihxDxL9a9cFUc1uij5EWg_4);
	{
		while (1) {
			NI waitedState_1;
			int T48_;
			waitedState_1 = load__mcf5407Zlatch_u60((&(*latch_p0).state), ((memory_order)2));
			{
				if (!(waitedState_1 == ((NI)2))) goto LA28_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA28_: ;
			{
				if (!(waitedState_1 == ((NI)3))) goto LA32_;
				reportStall__mcf5407Zlatch_u99(latch_p0);
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA32_: ;
			{
				NI64 T36_;
				NI running_2;
				T36_ = (NI64)0;
				T36_ = monotonicMillis__mcf5407Zlatch_u10();
				if (!(deadline_1 <= T36_)) goto LA37_;
				running_2 = ((NI)1);
				{
					NIM_BOOL T41_;
					T41_ = (NIM_BOOL)0;
					T41_ = compareExchange__mcf5407Zlatch_u114((&(*latch_p0).state), (&running_2), ((NI)3), ((memory_order)4), ((memory_order)2));
					if (!!(T41_)) goto LA42_;
					{
						if (!(running_2 == ((NI)2))) goto LA46_;
						result = NIM_TRUE;
						goto BeforeRet_;
					}
LA46_: ;
				}
LA42_: ;
				reportStall__mcf5407Zlatch_u99(latch_p0);
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA37_: ;
			T48_ = (int)0;
			T48_ = sched_yield();
		}
	}
	}BeforeRet_: ;
	return result;
}
