/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NI32 tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ;
typedef NU8 tyEnum_BusAccess__wgDGg9a9bkwjMJu8F2U1coOg;
N_LIB_PRIVATE N_NIMCALL(NU32, faultStatusFor__mcf5407Zbus_u21)(tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ status_p0, tyEnum_BusAccess__wgDGg9a9bkwjMJu8F2U1coOg access_p1) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	switch (status_p0) {
	case ((tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ)0):
	{
		colontmpD_ = ((NU32)0);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ)3):
	{
		colontmpD__2 = ((NU32)9);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ)1):
	case ((tyEnum_Mcf5407BusStatus__43j0esv0LdqAlYdrzE4qGQ)2):
	{
		NU32 colontmpD__4;
		NU32 colontmpD__5;
		colontmpD__4 = (NU32)0;
		colontmpD__5 = (NU32)0;
		switch (access_p1) {
		case ((tyEnum_BusAccess__wgDGg9a9bkwjMJu8F2U1coOg)0):
		{
			colontmpD__4 = ((NU32)12);
			colontmpD__3 = colontmpD__4;
		}
		break;
		case ((tyEnum_BusAccess__wgDGg9a9bkwjMJu8F2U1coOg)1):
		{
			colontmpD__5 = ((NU32)8);
			colontmpD__3 = colontmpD__5;
		}
		break;
		default: __builtin_unreachable();
		}
		result = colontmpD__3;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
