/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew;
typedef struct tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q;
typedef struct tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw;
typedef struct tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ;
typedef struct tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ;
typedef struct tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg;
typedef struct tyObject_I2cSlavecolonObjectType___mY1FFAQdRwZDF3yblr0kgg tyObject_I2cSlavecolonObjectType___mY1FFAQdRwZDF3yblr0kgg;
typedef NI32 tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA;
typedef N_CDECL_PTR(NU32, tyProc__m3YPy7Spfk9bnIuzLyo9bUPA) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* status_p3);
typedef N_CDECL_PTR(void, tyProc__DPk5mmlbc0hvn8CHsxMHlw) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew {
	void* user;
	void* sim;
	tyProc__m3YPy7Spfk9bnIuzLyo9bUPA readFn;
	tyProc__DPk5mmlbc0hvn8CHsxMHlw writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
typedef NU8 tyArray__Pu3SVivFPiiTdvogs5S4RQ[12];
typedef NIM_BOOL tyArray__v9awdnBJNClaxp5DAvHayvQ[10];
typedef NIM_BOOL tyArray__oQcYT9cTpIXElOJwwEHsv5g[4];
typedef NU8 tyArray__kAtU2KkWJ4IWiiLIkcMTHQ[10];
typedef NU8 tyArray__ZphrDPKIBlVgF9aQajgV8qQ[4];
struct tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw {
	void* ctx;
	NU8 irqpar;
	NU8 avr;
	tyArray__Pu3SVivFPiiTdvogs5S4RQ icr;
	NU32 ipr;
	NU32 imr;
	tyArray__v9awdnBJNClaxp5DAvHayvQ internalPending;
	tyArray__oQcYT9cTpIXElOJwwEHsv5g externalPending;
	tyArray__kAtU2KkWJ4IWiiLIkcMTHQ internalVector;
	tyArray__ZphrDPKIBlVgF9aQajgV8qQ externalVector;
	NI lastLevel;
	NU8 lastVector;
	NIM_BOOL lastAutovector;
	NIM_BOOL presentedToCore;
};
struct tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ {
	NI interruptIndex;
	tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc;
	NU16 tmr;
	NU16 trr;
	NU16 tcr;
	NU16 tcn;
	NU8 ter;
	NU32 prescaler;
	NIM_BOOL interruptAsserted;
};
typedef N_CDECL_PTR(void, tyProc__ojFZVXWdl1RoZhPnbPZUvQ) (void* user_p0, NU8 byte_p1);
struct tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ {
	NI interruptIndex;
	tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc;
	tyProc__ojFZVXWdl1RoZhPnbPZUvQ txCallback;
	void* txUser;
	NU8 umr1;
	NU8 umr2;
	NIM_BOOL modeUmr1;
	NU8 ucsr;
	NU8 uacr;
	NU8 uimr;
	NU8 ubg1;
	NU8 ubg2;
	NU8 uivr;
	tyArray__ZphrDPKIBlVgF9aQajgV8qQ rxFifo;
	NI rxCount;
	NI rxHead;
	NIM_BOOL txEnabled;
	NIM_BOOL rxEnabled;
	NU8 txHolding;
	NIM_BOOL txHoldingValid;
	NIM_BOOL interruptAsserted;
};
struct tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg {
	tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc;
	tyObject_I2cSlavecolonObjectType___mY1FFAQdRwZDF3yblr0kgg* slave;
	NU8 madr;
	NU8 mfdr;
	NU8 mbcr;
	NU8 received;
	NIM_BOOL busBusy;
	NIM_BOOL interrupt;
	NIM_BOOL notAcknowledged;
	NIM_BOOL addressPhase;
	NIM_BOOL interruptAsserted;
};
typedef NU8 tyArray__osRrsGVfszrH7KA2p8J9coA[1024];
struct tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q {
	void* ctx;
	tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw intc;
	tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ timer0;
	tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ timer1;
	tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ uart0;
	tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ uart1;
	tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg mbus;
	tyArray__osRrsGVfszrH7KA2p8J9coA space;
	tyArray__osRrsGVfszrH7KA2p8J9coA writeProtect;
};
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zsim_u58)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0);
N_LIB_PRIVATE N_NIMCALL(void, initRegisters__mcf5407Zsim_u45)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, registerRange__mcf5407Zsim_u18)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NI length_p2, NU8 protect_p3);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zintc_u184)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Ztimer_u31)(tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zuart_u60)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zmbus_u63)(tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg* m_p0);
N_LIB_PRIVATE N_NIMCALL(NU8, readByteInternal__mcf5407Zsim_u97)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, readRegister__mcf5407Zintc_u204)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0, NU32 offset_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__mcf5407Ztimer_u65)(tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* t_p0, NU32 offset_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__mcf5407Zuart_u110)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU32 offset_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__mcf5407Zmbus_u139)(tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg* m_p0, NU32 offset_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*, newSim__mcf5407Zsim_u60)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0);
static N_INLINE(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*, create__mcf5407Zsim_u63)(NI size_p1);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_u1773)(NI size_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, initIntc__mcf5407Zintc_u201)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0, void* ctx_p1);
N_LIB_PRIVATE N_NIMCALL(void, initTimer__mcf5407Ztimer_u33)(tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* t_p0, NI interruptIndex_p1, tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p2);
N_LIB_PRIVATE N_NIMCALL(void, initUart__mcf5407Zuart_u62)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NI interruptIndex_p1, tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p2);
N_LIB_PRIVATE N_NIMCALL(void, initMBus__mcf5407Zmbus_u65)(tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg* m_p0, tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p1, tyObject_I2cSlavecolonObjectType___mY1FFAQdRwZDF3yblr0kgg* slave_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeByteInternal__mcf5407Zsim_u101)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NU8 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeRegister__mcf5407Zintc_u208)(tyObject_IntcObj__kTm3cySf2gpO9cgORuQF9blw* intc_p0, NU32 offset_p1, NU8 value_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeByte__mcf5407Ztimer_u85)(tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* t_p0, NU32 offset_p1, NU8 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeByte__mcf5407Zuart_u119)(tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* u_p0, NU32 offset_p1, NU8 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeByte__mcf5407Zmbus_u144)(tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg* m_p0, NU32 offset_p1, NU8 val_p2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3456;
N_LIB_PRIVATE N_NIMCALL(void, freeSim__mcf5407Zsim_u92)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0) {
	{
		tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* s_1;
		if (!!(((*ctx_p0).sim == 0))) goto LA3_;
		s_1 = ((tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*) ((*ctx_p0).sim));
		dealloc(((void*) (s_1)));
		(*ctx_p0).sim = NIM_NIL;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, registerRange__mcf5407Zsim_u18)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NI length_p2, NU8 protect_p3) {
{	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI idx_1;
				NI TM__rkpJhYKNN78p3pf00lLULg_3;
				NI TM__rkpJhYKNN78p3pf00lLULg_4;
				if (!(i_2 < length_p2)) goto LA3;
				i_1 = i_2;
				if (nimAddInt(((NI) (offset_p1)), i_1, &TM__rkpJhYKNN78p3pf00lLULg_3)) { raiseOverflow(); goto BeforeRet_;
				};
				idx_1 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_3);
				{
					if (!(idx_1 < ((NI)1024))) goto LA6_;
					if ((NU)(idx_1) > (NU)(1023)){ raiseIndexError2(idx_1, 1023); goto BeforeRet_;
					}
					(*sim_p0).writeProtect[(idx_1)- 0] = protect_p3;
				}
LA6_: ;
				if (nimAddInt(i_2, ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_4)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_4);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initRegisters__mcf5407Zsim_u45)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0) {
{	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__rkpJhYKNN78p3pf00lLULg_2;
				if (!(i_2 < ((NI)1024))) goto LA3;
				i_1 = i_2;
				if ((NU)(i_1) > (NU)(1023)){ raiseIndexError2(i_1, 1023); goto BeforeRet_;
				}
				(*sim_p0).space[(i_1)- 0] = ((NU8)0);
				if ((NU)(i_1) > (NU)(1023)){ raiseIndexError2(i_1, 1023); goto BeforeRet_;
				}
				(*sim_p0).writeProtect[(i_1)- 0] = ((NU8)255);
				if (nimAddInt(i_2, ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_2);
			} LA3: ;
		}
	}
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)0), ((NI)4), ((NU8)0));
	(*sim_p0).space[(((NI)0))- 0] = ((NU8)128);
	(*sim_p0).space[(((NI)2))- 0] = ((NU8)15);
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)4), ((NI)2), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)6), ((NI)1), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)8), ((NI)1), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)12), ((NI)1), ((NU8)0));
	{
		NI cs_1;
		NI res_1;
		cs_1 = (NI)0;
		res_1 = ((NI)0);
		{
			while (1) {
				NU32 base_1;
				NI TM__rkpJhYKNN78p3pf00lLULg_5;
				NI TM__rkpJhYKNN78p3pf00lLULg_6;
				if (!(res_1 <= ((NI)7))) goto LA6;
				cs_1 = ((NI) (res_1));
				if (nimMulInt(cs_1, ((NI)12), &TM__rkpJhYKNN78p3pf00lLULg_5)) { raiseOverflow(); goto BeforeRet_;
				};
				base_1 = (NU32)((NU32)(((NU32)128)) + (NU32)(((NU32) ((NI)(TM__rkpJhYKNN78p3pf00lLULg_5)))));
				registerRange__mcf5407Zsim_u18(sim_p0, base_1, ((NI)2), ((NU8)0));
				registerRange__mcf5407Zsim_u18(sim_p0, (NU32)((NU32)(base_1) + (NU32)(((NU32)4))), ((NI)4), ((NU8)0));
				registerRange__mcf5407Zsim_u18(sim_p0, (NU32)((NU32)(base_1) + (NU32)(((NU32)10))), ((NI)2), ((NU8)0));
				if (nimAddInt(res_1, ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_6)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_6);
			} LA6: ;
		}
	}
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)256), ((NI)2), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)264), ((NI)4), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)268), ((NI)4), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)272), ((NI)4), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)276), ((NI)4), ((NU8)0));
	(*sim_p0).space[(((NI)464))- 0] = ((NU8)14);
	(*sim_p0).writeProtect[(((NI)464))- 0] = ((NU8)255);
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)580), ((NI)2), ((NU8)0));
	registerRange__mcf5407Zsim_u18(sim_p0, ((NU32)584), ((NI)2), ((NU8)0));
	(*sim_p0).writeProtect[(((NI)584))- 0] = ((NU8)2);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, reset__mcf5407Zsim_u58)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0) {
	initRegisters__mcf5407Zsim_u45(sim_p0);
	reset__mcf5407Zintc_u184((&(*sim_p0).intc));
	reset__mcf5407Ztimer_u31((&(*sim_p0).timer0));
	reset__mcf5407Ztimer_u31((&(*sim_p0).timer1));
	reset__mcf5407Zuart_u60((&(*sim_p0).uart0));
	reset__mcf5407Zuart_u60((&(*sim_p0).uart1));
	reset__mcf5407Zmbus_u63((&(*sim_p0).mbus));
}
N_LIB_PRIVATE N_NIMCALL(void, resetSim__mcf5407Zsim_u95)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0) {
	{
		if (!!(((*ctx_p0).sim == 0))) goto LA3_;
		reset__mcf5407Zsim_u58(((tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*) ((*ctx_p0).sim)));
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3456);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, readByteInternal__mcf5407Zsim_u97)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1) {
	NU8 result;
	NU8 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	T1_ = (NU8)0;
	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		NIM_BOOL T8_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (offset_p1 == ((NU32)6));
		if (T5_) goto LA6_;
		T5_ = (offset_p1 == ((NU32)75));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T8_ = (NIM_BOOL)0;
		T8_ = ((NU32)(((NU32)76)) <= (NU32)(offset_p1));
		if (!(T8_)) goto LA9_;
		T8_ = ((NU32)(offset_p1) < (NU32)(((NU32)88)));
LA9_: ;
		T4_ = T8_;
LA7_: ;
		if (!T4_) goto LA10_;
		result = readRegister__mcf5407Zintc_u204((&(*sim_p0).intc), offset_p1);
	}
	goto LA2_;
LA10_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = ((NU32)(((NU32)320)) <= (NU32)(offset_p1));
		if (!(T13_)) goto LA14_;
		T13_ = ((NU32)(offset_p1) <= (NU32)(((NU32)339)));
LA14_: ;
		if (!T13_) goto LA15_;
		result = readByte__mcf5407Ztimer_u65((&(*sim_p0).timer0), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)320))));
	}
	goto LA2_;
LA15_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = ((NU32)(((NU32)384)) <= (NU32)(offset_p1));
		if (!(T18_)) goto LA19_;
		T18_ = ((NU32)(offset_p1) <= (NU32)(((NU32)403)));
LA19_: ;
		if (!T18_) goto LA20_;
		result = readByte__mcf5407Ztimer_u65((&(*sim_p0).timer1), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)384))));
	}
	goto LA2_;
LA20_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = ((NU32)(((NU32)448)) <= (NU32)(offset_p1));
		if (!(T23_)) goto LA24_;
		T23_ = ((NU32)(offset_p1) < (NU32)(((NU32)512)));
LA24_: ;
		if (!T23_) goto LA25_;
		result = readByte__mcf5407Zuart_u110((&(*sim_p0).uart0), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)448))));
	}
	goto LA2_;
LA25_: ;
	{
		NIM_BOOL T28_;
		T28_ = (NIM_BOOL)0;
		T28_ = ((NU32)(((NU32)512)) <= (NU32)(offset_p1));
		if (!(T28_)) goto LA29_;
		T28_ = ((NU32)(offset_p1) < (NU32)(((NU32)576)));
LA29_: ;
		if (!T28_) goto LA30_;
		result = readByte__mcf5407Zuart_u110((&(*sim_p0).uart1), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)512))));
	}
	goto LA2_;
LA30_: ;
	{
		NIM_BOOL T33_;
		T33_ = (NIM_BOOL)0;
		T33_ = ((NU32)(((NU32)640)) <= (NU32)(offset_p1));
		if (!(T33_)) goto LA34_;
		T33_ = ((NU32)(offset_p1) <= (NU32)(((NU32)659)));
LA34_: ;
		if (!T33_) goto LA35_;
		result = readByte__mcf5407Zmbus_u139((&(*sim_p0).mbus), offset_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA35_: ;
	{
		if (!(((NI) (offset_p1)) < ((NI)1024))) goto LA38_;
		if ((NU)(((NI) (offset_p1))) > (NU)(1023)){ raiseIndexError2(((NI) (offset_p1)), 1023); goto BeforeRet_;
		}
		result = (*sim_p0).space[(((NI) (offset_p1)))- 0];
	}
	goto LA2_;
LA38_: ;
	{
		result = ((NU8)0);
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, simRead__mcf5407Zsim_u106)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NU8 size_p2, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* st_p3) {
	NU32 result;
	NU32 res_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	(*st_p3) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)0);
	{
		if (!((NU32)(((NU32)1024)) < (NU32)((NU32)((NU32)(offset_p1) + (NU32)(((NU32) (size_p2))))))) goto LA3_;
		(*st_p3) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)1);
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T8_ = !((size_p2 == ((NU8)1)));
		if (!(T8_)) goto LA9_;
		T8_ = !((size_p2 == ((NU8)2)));
LA9_: ;
		T7_ = T8_;
		if (!(T7_)) goto LA10_;
		T7_ = !((size_p2 == ((NU8)4)));
LA10_: ;
		if (!T7_) goto LA11_;
		(*st_p3) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)2);
		result = ((NU32)0);
		goto BeforeRet_;
	}
LA11_: ;
	{
		NIM_BOOL T15_;
		NIM_BOOL T16_;
		NIM_BOOL T19_;
		T15_ = (NIM_BOOL)0;
		T16_ = (NIM_BOOL)0;
		T16_ = ((NU32)(((NU32)448)) <= (NU32)(offset_p1));
		if (!(T16_)) goto LA17_;
		T16_ = ((NU32)(offset_p1) < (NU32)(((NU32)576)));
LA17_: ;
		T15_ = T16_;
		if (T15_) goto LA18_;
		T19_ = (NIM_BOOL)0;
		T19_ = ((NU32)(((NU32)640)) <= (NU32)(offset_p1));
		if (!(T19_)) goto LA20_;
		T19_ = ((NU32)(offset_p1) <= (NU32)(((NU32)659)));
LA20_: ;
		T15_ = T19_;
LA18_: ;
		if (!T15_) goto LA21_;
		{
			if (!!((size_p2 == ((NU8)1)))) goto LA25_;
			(*st_p3) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)2);
			result = ((NU32)0);
			goto BeforeRet_;
		}
LA25_: ;
	}
LA21_: ;
	res_1 = ((NU32)0);
	{
		NI b_1;
		NI colontmp_;
		NI i_1;
		b_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (size_p2));
		i_1 = ((NI)0);
		{
			while (1) {
				NU8 T30_;
				NI TM__rkpJhYKNN78p3pf00lLULg_7;
				if (!(i_1 < colontmp_)) goto LA29;
				b_1 = i_1;
				T30_ = (NU8)0;
				T30_ = readByteInternal__mcf5407Zsim_u97(sim_p0, (NU32)((NU32)(offset_p1) + (NU32)(((NU32) (b_1)))));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res_1 = (NU32)((NU32)((NU64)(res_1) << (NU64)(((NI)8) & (32 - 1))) | ((NU32) (T30_)));
				if (nimAddInt(i_1, ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_7)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_7);
			} LA29: ;
		}
	}
	result = res_1;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*, create__mcf5407Zsim_u63)(NI size_p1) {
	tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* result;
	NI TM__rkpJhYKNN78p3pf00lLULg_8;
	void* T1_;
{	result = (tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*)0;
	if (nimMulInt(((NI)2392), size_p1, &TM__rkpJhYKNN78p3pf00lLULg_8)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__rkpJhYKNN78p3pf00lLULg_8)) < ((NI)0) || ((NI)(TM__rkpJhYKNN78p3pf00lLULg_8)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__rkpJhYKNN78p3pf00lLULg_8), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	T1_ = (void*)0;
	T1_ = alloc0Impl__system_u1773(((NI)(TM__rkpJhYKNN78p3pf00lLULg_8)));
	result = ((tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*) (T1_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*, newSim__mcf5407Zsim_u60)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0) {
	tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* result;
	tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* T1_;
	tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ* T2_;
	tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* T3_;
	tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ* T4_;
	tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg* T5_;
	result = create__mcf5407Zsim_u63(((NI)1));
	(*result).ctx = ((void*) (ctx_p0));
	initIntc__mcf5407Zintc_u201((&(*result).intc), ((void*) (ctx_p0)));
	T1_ = (tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ*)0;
	T1_ = (&(*result).timer0);
	initTimer__mcf5407Ztimer_u33(T1_, ((NI)1), (&(*result).intc));
	T2_ = (tyObject_TimerObj__Zw9aTbg0iBpjvoaMdBDmkpQ*)0;
	T2_ = (&(*result).timer1);
	initTimer__mcf5407Ztimer_u33(T2_, ((NI)2), (&(*result).intc));
	T3_ = (tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ*)0;
	T3_ = (&(*result).uart0);
	initUart__mcf5407Zuart_u62(T3_, ((NI)4), (&(*result).intc));
	T4_ = (tyObject_UartObj__WN50qc5Vjup9bnmLqgJmwmQ*)0;
	T4_ = (&(*result).uart1);
	initUart__mcf5407Zuart_u62(T4_, ((NI)5), (&(*result).intc));
	T5_ = (tyObject_MBusObj__622p2UAp51RM4Oo3uDXqEg*)0;
	T5_ = (&(*result).mbus);
	initMBus__mcf5407Zmbus_u65(T5_, (&(*result).intc), ((tyObject_I2cSlavecolonObjectType___mY1FFAQdRwZDF3yblr0kgg*) NIM_NIL));
	reset__mcf5407Zsim_u58(result);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*, ensureSim__mcf5407Zsim_u88)(tyObject_MCF5407CtxcolonObjectType___waHAsSX2E8vFIGegH9axKew* ctx_p0) {
	tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* result;
	tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* T1_;
	T1_ = (tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*)0;
	{
		tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* s_1;
		if (!((*ctx_p0).sim == 0)) goto LA4_;
		s_1 = newSim__mcf5407Zsim_u60(ctx_p0);
		(*ctx_p0).sim = ((void*) (s_1));
		result = s_1;
	}
	goto LA2_;
LA4_: ;
	{
		result = ((tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q*) ((*ctx_p0).sim));
	}
LA2_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeByteInternal__mcf5407Zsim_u101)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NU8 val_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (offset_p1 == ((NU32)6));
		if (T4_) goto LA5_;
		T4_ = (offset_p1 == ((NU32)75));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = ((NU32)(((NU32)76)) <= (NU32)(offset_p1));
		if (!(T7_)) goto LA8_;
		T7_ = ((NU32)(offset_p1) < (NU32)(((NU32)88)));
LA8_: ;
		T3_ = T7_;
LA6_: ;
		if (!T3_) goto LA9_;
		writeRegister__mcf5407Zintc_u208((&(*sim_p0).intc), offset_p1, val_p2);
	}
	goto LA1_;
LA9_: ;
	{
		NIM_BOOL T12_;
		T12_ = (NIM_BOOL)0;
		T12_ = ((NU32)(((NU32)320)) <= (NU32)(offset_p1));
		if (!(T12_)) goto LA13_;
		T12_ = ((NU32)(offset_p1) <= (NU32)(((NU32)339)));
LA13_: ;
		if (!T12_) goto LA14_;
		writeByte__mcf5407Ztimer_u85((&(*sim_p0).timer0), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)320))), val_p2);
	}
	goto LA1_;
LA14_: ;
	{
		NIM_BOOL T17_;
		T17_ = (NIM_BOOL)0;
		T17_ = ((NU32)(((NU32)384)) <= (NU32)(offset_p1));
		if (!(T17_)) goto LA18_;
		T17_ = ((NU32)(offset_p1) <= (NU32)(((NU32)403)));
LA18_: ;
		if (!T17_) goto LA19_;
		writeByte__mcf5407Ztimer_u85((&(*sim_p0).timer1), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)384))), val_p2);
	}
	goto LA1_;
LA19_: ;
	{
		NIM_BOOL T22_;
		T22_ = (NIM_BOOL)0;
		T22_ = ((NU32)(((NU32)448)) <= (NU32)(offset_p1));
		if (!(T22_)) goto LA23_;
		T22_ = ((NU32)(offset_p1) < (NU32)(((NU32)512)));
LA23_: ;
		if (!T22_) goto LA24_;
		writeByte__mcf5407Zuart_u119((&(*sim_p0).uart0), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)448))), val_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA24_: ;
	{
		NIM_BOOL T27_;
		T27_ = (NIM_BOOL)0;
		T27_ = ((NU32)(((NU32)512)) <= (NU32)(offset_p1));
		if (!(T27_)) goto LA28_;
		T27_ = ((NU32)(offset_p1) < (NU32)(((NU32)576)));
LA28_: ;
		if (!T27_) goto LA29_;
		writeByte__mcf5407Zuart_u119((&(*sim_p0).uart1), (NU32)((NU32)(offset_p1) - (NU32)(((NU32)512))), val_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA29_: ;
	{
		NIM_BOOL T32_;
		T32_ = (NIM_BOOL)0;
		T32_ = ((NU32)(((NU32)640)) <= (NU32)(offset_p1));
		if (!(T32_)) goto LA33_;
		T32_ = ((NU32)(offset_p1) <= (NU32)(((NU32)659)));
LA33_: ;
		if (!T32_) goto LA34_;
		writeByte__mcf5407Zmbus_u144((&(*sim_p0).mbus), offset_p1, val_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA34_: ;
	{
		NU8 prot_1;
		if (!(((NI) (offset_p1)) < ((NI)1024))) goto LA37_;
		if ((NU)(((NI) (offset_p1))) > (NU)(1023)){ raiseIndexError2(((NI) (offset_p1)), 1023); goto BeforeRet_;
		}
		prot_1 = (*sim_p0).writeProtect[(((NI) (offset_p1)))- 0];
		if ((NU)(((NI) (offset_p1))) > (NU)(1023)){ raiseIndexError2(((NI) (offset_p1)), 1023); goto BeforeRet_;
		}
		if ((NU)(((NI) (offset_p1))) > (NU)(1023)){ raiseIndexError2(((NI) (offset_p1)), 1023); goto BeforeRet_;
		}
		(*sim_p0).space[(((NI) (offset_p1)))- 0] = (NU8)((NU8)((*sim_p0).space[(((NI) (offset_p1)))- 0] & prot_1) | (NU8)(val_p2 & (NU8)((NU8) ~(prot_1))));
	}
	goto LA1_;
LA37_: ;
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, simWrite__mcf5407Zsim_u138)(tyObject_SimObj__9aHDmoh5U3Mfka849bwaz68Q* sim_p0, NU32 offset_p1, NU8 size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA* st_p4) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	(*st_p4) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)0);
	{
		if (!((NU32)(((NU32)1024)) < (NU32)((NU32)((NU32)(offset_p1) + (NU32)(((NU32) (size_p2))))))) goto LA3_;
		(*st_p4) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)1);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T8_ = !((size_p2 == ((NU8)1)));
		if (!(T8_)) goto LA9_;
		T8_ = !((size_p2 == ((NU8)2)));
LA9_: ;
		T7_ = T8_;
		if (!(T7_)) goto LA10_;
		T7_ = !((size_p2 == ((NU8)4)));
LA10_: ;
		if (!T7_) goto LA11_;
		(*st_p4) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)2);
		goto BeforeRet_;
	}
LA11_: ;
	{
		NIM_BOOL T15_;
		NIM_BOOL T16_;
		NIM_BOOL T19_;
		T15_ = (NIM_BOOL)0;
		T16_ = (NIM_BOOL)0;
		T16_ = ((NU32)(((NU32)448)) <= (NU32)(offset_p1));
		if (!(T16_)) goto LA17_;
		T16_ = ((NU32)(offset_p1) < (NU32)(((NU32)576)));
LA17_: ;
		T15_ = T16_;
		if (T15_) goto LA18_;
		T19_ = (NIM_BOOL)0;
		T19_ = ((NU32)(((NU32)640)) <= (NU32)(offset_p1));
		if (!(T19_)) goto LA20_;
		T19_ = ((NU32)(offset_p1) <= (NU32)(((NU32)659)));
LA20_: ;
		T15_ = T19_;
LA18_: ;
		if (!T15_) goto LA21_;
		{
			if (!!((size_p2 == ((NU8)1)))) goto LA25_;
			(*st_p4) = ((tyEnum_Mcf5407BusStatus__E21jspC9bK8E36Hb9blXpukA)2);
			goto BeforeRet_;
		}
LA25_: ;
	}
LA21_: ;
	{
		NI b_1;
		NI colontmp_;
		NI i_1;
		b_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (size_p2));
		i_1 = ((NI)0);
		{
			while (1) {
				NI shift_1;
				NI TM__rkpJhYKNN78p3pf00lLULg_9;
				NI TM__rkpJhYKNN78p3pf00lLULg_10;
				NI TM__rkpJhYKNN78p3pf00lLULg_11;
				NU8 byteVal_1;
				NI TM__rkpJhYKNN78p3pf00lLULg_12;
				if (!(i_1 < colontmp_)) goto LA29;
				b_1 = i_1;
				if (nimSubInt(((NI) (size_p2)), ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_9)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__rkpJhYKNN78p3pf00lLULg_9), b_1, &TM__rkpJhYKNN78p3pf00lLULg_10)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimMulInt((NI)(TM__rkpJhYKNN78p3pf00lLULg_10), ((NI)8), &TM__rkpJhYKNN78p3pf00lLULg_11)) { raiseOverflow(); goto BeforeRet_;
				};
				shift_1 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_11);
				byteVal_1 = ((NU8) ((NU32)((NU32)((NU32)(value_p3) >> (NU64)(shift_1 & (32 - 1))) & ((NU32)255))));
				writeByteInternal__mcf5407Zsim_u101(sim_p0, (NU32)((NU32)(offset_p1) + (NU32)(((NU32) (b_1)))), byteVal_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(i_1, ((NI)1), &TM__rkpJhYKNN78p3pf00lLULg_12)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__rkpJhYKNN78p3pf00lLULg_12);
			} LA29: ;
		}
	}
	}BeforeRet_: ;
}
