/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdatomic.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw;
typedef struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ;
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ {
	_Atomic NI64 value;
};
struct tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw {
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ state;
	tyObject_Atomic__bx9bL9c7GTpG6vY8xhUjCeDQ reported;
};
N_LIB_EXPORT N_CDECL(int, mcf5407_runtime_init)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runtimeInitOnce__mcf5407Zlatch_u172)(tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw* latch_p0, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ initializer_p1, NI64 waitMillis_p2);
N_CDECL(void, mcf5407_NimMain)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, mcf5407_NimMainModule)(void);
extern tyObject_RuntimeLatch__mz5kX9cAtVZhGSkxOBId9bRw runtimeLatch__mcf5407Zlatch_u49;
N_LIB_EXPORT N_CDECL(int, mcf5407_runtime_init)(void) {
	int result;
	int colontmpD_;
	int colontmpD__2;
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = runtimeInitOnce__mcf5407Zlatch_u172((&runtimeLatch__mcf5407Zlatch_u49), mcf5407_NimMain, IL64(5000));
		if (!T3_) goto LA4_;
		colontmpD_ = ((int)1);
		result = colontmpD_;
	}
	goto LA1_;
LA4_: ;
	{
		colontmpD__2 = ((int)0);
		result = colontmpD__2;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, mcf5407_NimDestroyGlobals)(void) {
}

N_LIB_PRIVATE void mcf5407_PreMainInner(void) {
}

N_LIB_PRIVATE void mcf5407_PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = mcf5407_PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	mcf5407_PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, mcf5407_NimMainInner)(void) {
	mcf5407_NimMainModule();
}

N_CDECL(void, mcf5407_NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	mcf5407_PreMain();
	inner = mcf5407_NimMainInner;
	(*inner)();
#else
	mcf5407_PreMain();
	mcf5407_NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, mcf5407_NimMainModule)(void) {
{
}
}

