/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg;
typedef struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw;
typedef struct tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw;
typedef struct tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg;
struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw {
	NI rc;
};
typedef NI32 tyEnum_Mcf5407BusStatus__PXh9bgQ7mscHySRyy79cZ8iQ;
typedef N_CDECL_PTR(NU32, tyProc__9c6bdimjqGzFoFIVbwzKepg) (void* user_p0, NU32 address_p1, int size_p2, tyEnum_Mcf5407BusStatus__PXh9bgQ7mscHySRyy79cZ8iQ* status_p3);
typedef N_CDECL_PTR(void, tyProc__oP2B9c9aPTWYy364XFkdG2IA) (void* user_p0, NU32 address_p1, int size_p2, NU32 value_p3, tyEnum_Mcf5407BusStatus__PXh9bgQ7mscHySRyy79cZ8iQ* status_p4);
typedef N_CDECL_PTR(void, tyProc__f9aaH9agUw9cXBXOefXPK4BRg) (void* user_p0, int level_p1, NU8 vector_p2);
typedef NU32 tyArray__QZtz52L9cGJIYGgnaekdblw[8];
typedef NU32 tyArray__pIlUFYzWYz8RAGWkyxci4w[7];
struct tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg {
	void* user;
	void* sim;
	void* cfgIsa;
	void* cfgVbrMask;
	tyProc__9c6bdimjqGzFoFIVbwzKepg readFn;
	tyProc__oP2B9c9aPTWYy364XFkdG2IA writeFn;
	tyProc__f9aaH9agUw9cXBXOefXPK4BRg iackFn;
	NU32 pc;
	NU32 sp;
	NU32 sr;
	tyArray__QZtz52L9cGJIYGgnaekdblw dRegs;
	tyArray__pIlUFYzWYz8RAGWkyxci4w aRegs;
	NIM_BOOL halted;
	NIM_BOOL fault;
	NU32 vbr;
	NU32 cacr;
	NU32 acr0;
	NU32 acr1;
	NU32 acr2;
	NU32 acr3;
	NU32 rambar0;
	NU32 rambar1;
	NU32 mbar;
	int irqLevel;
	NU8 irqVector;
	NIM_BOOL irqAutovector;
	NIM_BOOL irq7Armed;
	NU8 irq7Vector;
	NIM_BOOL irq7Autovector;
	NIM_BOOL atHandlerEntry;
	NIM_BOOL pendingWriteFault;
	NU32 pendingFaultStatus;
	NU32 pendingStackedSr;
};
typedef NU8 tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w;
typedef NU8 tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ;
struct tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw {
	tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ mode;
	NU8 reg;
};
typedef NU8 tySet_tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ;
typedef NU8 tySet_tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ;
struct tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg {
	tySet_tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ modes;
	tySet_tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ ea7;
};
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mcf5407Zintc_u135)(tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eaIsLegalFor__mcf5407Zdecode95types_u232)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0, tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw ea_p1, NU8 size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg, eaLegalityFor__mcf5407Zdecode95types_u176)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0, NU8 size_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEaLegal__mcf5407Zea_u90)(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg leg_p0, tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw ea_p1);
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaDataAddressing__mcf5407Zdecode95types_u164 = {253, 31}
;
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaBitDynamic__mcf5407Zdecode95types_u170 = {253, 15}
;
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaJumpTarget__mcf5407Zdecode95types_u172 = {228, 15}
;
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaLeaPeaTarget__mcf5407Zdecode95types_u173 = {228, 15}
;
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaMemoryAlterable__mcf5407Zdecode95types_u163 = {252, 3}
;
N_LIB_PRIVATE NIM_CONST tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg eaBitStatic__mcf5407Zdecode95types_u171 = {61, 0}
;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T5_));
		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)3) & (64 - 1))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)8));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mcf5407Zintc_u135)(tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mcf5407Zintc_u120)(tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___mcf5407Zintc_u135((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	(*((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T2_))).rc, ((NI)8));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg*, eqdup___mcf5407Zintc_u126)(tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg* src_p0) {
	tyObject_MCF5407CtxcolonObjectType___VGfFhbRt15I3NKMtoSXYcg* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg, eaLegalityFor__mcf5407Zdecode95types_u176)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0, NU8 size_p1) {
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg result;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD_;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__2;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__3;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__4;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__5;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__6;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__7;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__8;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__9;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__10;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__11;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__12;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__13;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__14;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__15;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__16;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__17;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__4), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__5), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__7), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__8), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__9), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__10), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__11), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__12), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__13), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__14), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__15), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__16), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	nimZeroMem((void*)(&colontmpD__17), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
	switch (op_p0) {
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)1):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)2):
	{
		colontmpD_.modes = 255;
		colontmpD_.ea7 = 31;
		result = colontmpD_;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)11):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)12):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)13):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)14):
	{
		colontmpD__2.modes = 255;
		colontmpD__2.ea7 = 31;
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)9):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)10):
	{
		colontmpD__3.modes = 255;
		colontmpD__3.ea7 = 3;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)17):
	{
		colontmpD__4.modes = 253;
		colontmpD__4.ea7 = 3;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)20):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)21):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)22):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)23):
	{
		tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__18;
		tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg colontmpD__19;
		nimZeroMem((void*)(&colontmpD__18), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
		nimZeroMem((void*)(&colontmpD__19), sizeof(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg));
		{
			if (!(size_p1 == ((NU8)2))) goto LA8_;
			colontmpD__18.modes = 253;
			colontmpD__18.ea7 = 31;
			colontmpD__5 = colontmpD__18;
		}
		goto LA6_;
LA8_: ;
		{
			colontmpD__19.modes = 61;
			colontmpD__19.ea7 = 0;
			colontmpD__5 = colontmpD__19;
		}
LA6_: ;
		result = colontmpD__5;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)24):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)25):
	{
		colontmpD__6 = eaDataAddressing__mcf5407Zdecode95types_u164;
		result = colontmpD__6;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)30):
	{
		colontmpD__7 = eaBitDynamic__mcf5407Zdecode95types_u170;
		result = colontmpD__7;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)43):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)31):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)32):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)33):
	{
		colontmpD__8.modes = 253;
		colontmpD__8.ea7 = 3;
		result = colontmpD__8;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)27):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)44):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)45):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)46):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)47):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)48):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)49):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)50):
	{
		colontmpD__9.modes = 1;
		colontmpD__9.ea7 = 0;
		result = colontmpD__9;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)15):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)16):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)19):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)41):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)18):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)42):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)39):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)40):
	{
		colontmpD__10.modes = 1;
		colontmpD__10.ea7 = 0;
		result = colontmpD__10;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)52):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)53):
	{
		colontmpD__11 = eaJumpTarget__mcf5407Zdecode95types_u172;
		result = colontmpD__11;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)29):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)57):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)58):
	{
		colontmpD__12.modes = 255;
		colontmpD__12.ea7 = 31;
		result = colontmpD__12;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)36):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)59):
	{
		colontmpD__13.modes = 1;
		colontmpD__13.ea7 = 0;
		result = colontmpD__13;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)5):
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)6):
	{
		colontmpD__14 = eaLeaPeaTarget__mcf5407Zdecode95types_u173;
		result = colontmpD__14;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)4):
	{
		colontmpD__15.modes = 36;
		colontmpD__15.ea7 = 0;
		result = colontmpD__15;
	}
	break;
	case ((tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w)28):
	{
		colontmpD__16.modes = 1;
		colontmpD__16.ea7 = 0;
		result = colontmpD__16;
	}
	break;
	default:
	{
		colontmpD__17.modes = 0;
		colontmpD__17.ea7 = 0;
		result = colontmpD__17;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eaIsLegalFor__mcf5407Zdecode95types_u232)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0, tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw ea_p1, NU8 size_p2) {
	NIM_BOOL result;
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg legality_1;
	NIM_BOOL T1_;
	tySet_tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ T2_;
	legality_1 = eaLegalityFor__mcf5407Zdecode95types_u176(op_p0, size_p2);
	T1_ = (NIM_BOOL)0;
	T2_ = 0;
	T1_ = !((legality_1.modes == T2_));
	if (!(T1_)) goto LA3_;
	T1_ = isEaLegal__mcf5407Zea_u90(legality_1, ea_p1);
LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eaIsLegalFor__mcf5407Zdecode95types_u243)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0, tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw ea_p1) {
	NIM_BOOL result;
	result = eaIsLegalFor__mcf5407Zdecode95types_u232(op_p0, ea_p1, ((NU8)4));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg, eaLegalityFor__mcf5407Zdecode95types_u229)(tyEnum_Operation__1LWYhAqiC7NPdUA5Ucn03w op_p0) {
	tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg result;
	result = eaLegalityFor__mcf5407Zdecode95types_u176(op_p0, ((NU8)4));
	return result;
}
