/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw;
typedef struct tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg;
typedef NU8 tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ;
struct tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw {
	tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ mode;
	NU8 reg;
};
typedef NU8 tySet_tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ;
typedef NU8 tySet_tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ;
struct tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg {
	tySet_tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ modes;
	tySet_tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ ea7;
};
typedef NU8 tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ;
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimSetMem__system_u2179)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2179(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw, decodeEa__mcf5407Zea_u28)(NU16 field_p0) {
	tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw result;
{	nimZeroMem((void*)(&result), sizeof(tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw));
	if (((NU16)((NU16)((NU16)(field_p0) >> (NU64)(((NI)3) & (16 - 1))) & ((NU16)7))) < ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ)0) || ((NU16)((NU16)((NU16)(field_p0) >> (NU64)(((NI)3) & (16 - 1))) & ((NU16)7))) > ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ)7)){ raiseRangeErrorI((NU16)((NU16)((NU16)(field_p0) >> (NU64)(((NI)3) & (16 - 1))) & ((NU16)7)), ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ)0), ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ)7)); goto BeforeRet_;
	}
	result.mode = ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ) ((NU16)((NU16)((NU16)(field_p0) >> (NU64)(((NI)3) & (16 - 1))) & ((NU16)7))));
	result.reg = ((NU8) ((NU16)(field_p0 & ((NU16)7))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw, eqdup___mcf5407Zea_u60)(tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw src_p0) {
	tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw));
	result.mode = src_p0.mode;
	result.reg = src_p0.reg;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEaLegal__mcf5407Zea_u90)(tyObject_EaLegality__XgK39bwaQxCy1rrFBAevbvg leg_p0, tyObject_EA__d9aX2tTY9aA4MgUXPrMF36hw ea_p1) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!!(((leg_p0.modes &((NU8)1<<((NU)((ea_p1.mode))&7U)))!=0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(ea_p1.mode == ((tyEnum_EAMode__9aUC7GQ0wWluKjO87pfT4FQ)7))) goto LA7_;
		if ((ea_p1.reg) < ((tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ)0) || (ea_p1.reg) > ((tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ)7)){ raiseRangeErrorI(ea_p1.reg, ((tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ)0), ((tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ)7)); goto BeforeRet_;
		}
		result = ((leg_p0.ea7 &((NU8)1<<((NU)((((tyEnum_EA7__ROvqCsKcdac0S0YYVD8QZQ) (ea_p1.reg))))&7U)))!=0);
	}
	goto LA5_;
LA7_: ;
	{
		result = NIM_TRUE;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
