/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA;
typedef struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw;
typedef struct tyObject_Defect__BqN81v581jmOWyLfkgmixA tyObject_Defect__BqN81v581jmOWyLfkgmixA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__vrjNl4awzOmCciafmd8lLQ tySequence__vrjNl4awzOmCciafmd8lLQ;
typedef struct tySequence__vrjNl4awzOmCciafmd8lLQ_Content tySequence__vrjNl4awzOmCciafmd8lLQ_Content;
typedef struct tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg;
typedef struct tyObject_ArithmeticDefect__gszmQNGgGMDTjegKrKPFNA tyObject_ArithmeticDefect__gszmQNGgGMDTjegKrKPFNA;
typedef struct tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w;
typedef struct tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ;
typedef struct tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg;
typedef struct tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg;
typedef struct tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ;
typedef struct tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw {
	NI rc;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__vrjNl4awzOmCciafmd8lLQ {
  NI len; tySequence__vrjNl4awzOmCciafmd8lLQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__vrjNl4awzOmCciafmd8lLQ trace;
	Exception* up;
};
struct tyObject_Defect__BqN81v581jmOWyLfkgmixA {
	Exception Sup;
};
struct tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA {
	tyObject_Defect__BqN81v581jmOWyLfkgmixA Sup;
};
struct tyObject_ArithmeticDefect__gszmQNGgGMDTjegKrKPFNA {
	tyObject_Defect__BqN81v581jmOWyLfkgmixA Sup;
};
struct tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg {
	tyObject_ArithmeticDefect__gszmQNGgGMDTjegKrKPFNA Sup;
};
struct tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w {
	tyObject_Defect__BqN81v581jmOWyLfkgmixA Sup;
};
struct tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ {
	tyObject_ArithmeticDefect__gszmQNGgGMDTjegKrKPFNA Sup;
};
struct tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg {
	Exception Sup;
};
struct tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg {
	tyObject_CatchableError__0bRZ4X5ZULV3Nw3cc55Jgg Sup;
};
struct tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ {
	tyObject_Defect__BqN81v581jmOWyLfkgmixA Sup;
};
struct tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__vrjNl4awzOmCciafmd8lLQ_Content { NI cap; tyObject_StackTraceEntry__H2mszH5tR6s19a9c7VBraDTQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3773)(tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3057)(tySequence__vrjNl4awzOmCciafmd8lLQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4161)(tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3825)(tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4210)(tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u8085)(tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ* dest_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__in3acHRzIMQLRhBbJM7T9aA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__F23GBccIoz6Crr2vWGudFg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__fBIodcxTiyoHUmbOIRbM4w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__yMsVk0wROJoXQ6kGYmXDUQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__qHTJpUiwp9bYgLH9aiBfd6Hg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bxoo9cu9cP5xLlKgJ9bkLNNqQ_;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[4] = {3701606400, 1285336064, 2742867456, 2111467520};
N_LIB_PRIVATE TNimTypeV2 NTIv2__in3acHRzIMQLRhBbJM7T9aA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 2742867456, 3437641728, 1841693952};
N_LIB_PRIVATE TNimTypeV2 NTIv2__F23GBccIoz6Crr2vWGudFg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 2742867456, 304641280};
N_LIB_PRIVATE TNimTypeV2 NTIv2__fBIodcxTiyoHUmbOIRbM4w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[5] = {3701606400, 1285336064, 2742867456, 3437641728, 3407188736};
N_LIB_PRIVATE TNimTypeV2 NTIv2__yMsVk0wROJoXQ6kGYmXDUQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 3025789184, 1959372032};
N_LIB_PRIVATE TNimTypeV2 NTIv2__qHTJpUiwp9bYgLH9aiBfd6Hg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 2742867456, 438894080};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bxoo9cu9cP5xLlKgJ9bkLNNqQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__Bp7bmWv1aLOvl19bz8dx8hw*) (T5_));
		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)3) & (64 - 1))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)8));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3773)(tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
	eqdestroy___system_u3773(((tyObject_RangeDefect__in3acHRzIMQLRhBbJM7T9aA*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4161)(tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
	eqdestroy___system_u4161(((tyObject_OverflowDefect__F23GBccIoz6Crr2vWGudFg*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3825)(tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
	eqdestroy___system_u3825(((tyObject_IndexDefect__fBIodcxTiyoHUmbOIRbM4w*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4210)(tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
	eqdestroy___system_u4210(((tyObject_DivByZeroDefect__yMsVk0wROJoXQ6kGYmXDUQ*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u8085)(tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
	eqdestroy___system_u8085(((tyObject_IOError__qHTJpUiwp9bYgLH9aiBfd6Hg*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3057((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
	eqdestroy___stdZassertions_u37(((tyObject_AssertionDefect__9bxoo9cu9cP5xLlKgJ9bkLNNqQ*) (dest_p0)));
}
