/* Generated by Nim Compiler v2.2.10 */
#ifndef __coldfire_nim__
#define __coldfire_nim__
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ;
typedef struct tyObject_CfConfig__H6u3pHuGsPH4Ay0lZIilPw tyObject_CfConfig__H6u3pHuGsPH4Ay0lZIilPw;
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign_p0);
N_LIB_IMPORT N_CDECL(int, cf_set_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1, NU32 value_p2);
N_LIB_IMPORT N_CDECL(NU32, cf_get_reg)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int index_p1);
N_LIB_IMPORT N_CDECL(int, cf_halted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_IMPORT N_CDECL(int, cf_faulted)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_IMPORT N_CDECL(void, cf_set_irq)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, int level_p1, NU8 vector_p2, int autovector_p3);
N_LIB_IMPORT N_CDECL(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ*, cf_create)(tyObject_CfConfig__H6u3pHuGsPH4Ay0lZIilPw* config_p0);
N_LIB_IMPORT N_CDECL(void, cf_destroy)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0);
N_LIB_IMPORT N_CDECL(void, cf_reset)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 initialSp_p1, NU32 initialPc_p2);
N_LIB_IMPORT N_CDECL(NU32, cf_exec)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, NU32 maxCycles_p1);
N_LIB_IMPORT N_CDECL(size_t, cf_state_size)(void);
N_LIB_IMPORT N_CDECL(void, cf_state_save)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, void* dst_p1);
N_LIB_IMPORT N_CDECL(void, cf_state_load)(tyObject_MCF5407CtxcolonObjectType___m5aCvzByibF3dd3pf8T9cOQ* ctx_p0, void* src_p1);
N_LIB_IMPORT N_CDECL(int, cf_runtime_init)(void);
N_CDECL(void, coldfire_NimMain)(void);
#endif /* __coldfire_nim__ */
